/**
 * Generates `src/styles/tokens.css`.
 *
 * Foundations follow the Untitled UI open-source design system (colour ramps,
 * type scale, radii, shadows). Motion and the productive spacing steps come from
 * IBM Carbon's token packages, which is what the dense application surfaces use.
 * Primer's functional tokens are re-pointed at these values so the components we
 * keep for their accessibility behaviour inherit this palette instead of GitHub's.
 *
 *   node scripts/build-tokens.mjs
 */
import { writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import * as motion from '@carbon/motion'
import * as layout from '@carbon/layout'

const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)))
const OUT = path.join(ROOT, 'src', 'styles', 'tokens.css')

/* ── Untitled UI ramps ──────────────────────────────────────────────────── */
const RAMPS = {
  gray: ['#fcfcfd', '#f9fafb', '#f2f4f7', '#eaecf0', '#d0d5dd', '#98a2b3', '#667085', '#475467', '#344054', '#182230', '#101828', '#0c111d'],
  brand: ['#fcfaff', '#f9f5ff', '#f4ebff', '#e9d7fe', '#d6bbfb', '#b692f6', '#9e77ed', '#7f56d9', '#6941c6', '#53389e', '#42307d', '#2c1c5f'],
  error: ['#fffbfa', '#fef3f2', '#fee4e2', '#fecdca', '#fda29b', '#f97066', '#f04438', '#d92d20', '#b42318', '#912018', '#7a271a', '#55160c'],
  warning: ['#fffcf5', '#fffaeb', '#fef0c7', '#fedf89', '#fec84b', '#fdb022', '#f79009', '#dc6803', '#b54708', '#93370d', '#7a2e0e', '#4e1d09'],
  success: ['#f6fef9', '#ecfdf3', '#dcfae6', '#abefc6', '#75e0a7', '#47cd89', '#17b26a', '#079455', '#067647', '#085d3a', '#074d31', '#053321'],
}
const STEPS = [25, 50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950]

const ramp = (name) => RAMPS[name].map((hex, i) => `    --${name}-${STEPS[i]}: ${hex};`).join('\n')

/* ── Untitled UI shadows ────────────────────────────────────────────────── */
const SHADOW = {
  xs: '0 1px 2px 0 rgb(10 13 18 / 0.05)',
  sm: '0 1px 3px 0 rgb(10 13 18 / 0.10), 0 1px 2px -1px rgb(10 13 18 / 0.06)',
  md: '0 4px 8px -2px rgb(10 13 18 / 0.10), 0 2px 4px -2px rgb(10 13 18 / 0.06)',
  lg: '0 12px 16px -4px rgb(10 13 18 / 0.08), 0 4px 6px -2px rgb(10 13 18 / 0.03)',
  xl: '0 20px 24px -4px rgb(10 13 18 / 0.08), 0 8px 8px -4px rgb(10 13 18 / 0.03)',
  '2xl': '0 24px 48px -12px rgb(10 13 18 / 0.18)',
  '3xl': '0 32px 64px -12px rgb(10 13 18 / 0.14)',
}
const SHADOW_DARK = {
  xs: '0 1px 2px 0 rgb(0 0 0 / 0.30)',
  sm: '0 1px 3px 0 rgb(0 0 0 / 0.40), 0 1px 2px -1px rgb(0 0 0 / 0.30)',
  md: '0 4px 8px -2px rgb(0 0 0 / 0.45), 0 2px 4px -2px rgb(0 0 0 / 0.30)',
  lg: '0 12px 16px -4px rgb(0 0 0 / 0.50), 0 4px 6px -2px rgb(0 0 0 / 0.30)',
  xl: '0 20px 24px -4px rgb(0 0 0 / 0.55), 0 8px 8px -4px rgb(0 0 0 / 0.30)',
  '2xl': '0 24px 48px -12px rgb(0 0 0 / 0.65)',
  '3xl': '0 32px 64px -12px rgb(0 0 0 / 0.70)',
}

/* ── Untitled UI type scale (size / line-height / tracking) ─────────────── */
const TYPE = [
  ['display-2xl', '4.5rem', '5.625rem', '-0.02em'],
  ['display-xl', '3.75rem', '4.5rem', '-0.02em'],
  ['display-lg', '3rem', '3.75rem', '-0.02em'],
  ['display-md', '2.25rem', '2.75rem', '-0.02em'],
  ['display-sm', '1.875rem', '2.375rem', '-0.01em'],
  ['display-xs', '1.5rem', '2rem', '-0.01em'],
  ['text-xl', '1.25rem', '1.875rem', '0'],
  ['text-lg', '1.125rem', '1.75rem', '0'],
  ['text-md', '1rem', '1.5rem', '0'],
  ['text-sm', '0.875rem', '1.25rem', '0'],
  ['text-xs', '0.75rem', '1.125rem', '0'],
]

const SPACING = [
  ['0', '0'], ['0-5', '0.125rem'], ['1', '0.25rem'], ['1-5', '0.375rem'], ['2', '0.5rem'], ['3', '0.75rem'],
  ['4', '1rem'], ['5', '1.25rem'], ['6', '1.5rem'], ['8', '2rem'], ['10', '2.5rem'], ['12', '3rem'],
  ['16', '4rem'], ['20', '5rem'], ['24', '6rem'], ['32', '8rem'], ['40', '10rem'],
]

const RADIUS = [['xs', '4px'], ['sm', '6px'], ['md', '8px'], ['lg', '10px'], ['xl', '12px'], ['2xl', '16px'], ['3xl', '20px'], ['4xl', '24px'], ['full', '9999px']]

const css = `/* ═══════════════════════════════════════════════════════════════════════════
   Design tokens — GENERATED by scripts/build-tokens.mjs. Do not edit by hand.

   Foundations: Untitled UI (colour ramps, type scale, radii, shadows).
   Motion and productive spacing: IBM Carbon token packages.
   Primer's functional tokens are re-pointed here so the components kept for
   their accessibility behaviour take this palette rather than GitHub's.
   ═══════════════════════════════════════════════════════════════════════════ */

:root {
  color-scheme: light;

  /* ── Ramps ─────────────────────────────────────────────────────────────── */
${Object.keys(RAMPS).map(ramp).join('\n\n')}

  /* Per-product accent. Set --brand on a subtree to re-tint everything below. */
  --brand: var(--brand-600);
  --brand-contrast: #ffffff;

  /* ── Semantic colour ───────────────────────────────────────────────────── */
  --bg-primary: #ffffff;
  --bg-secondary: var(--gray-50);
  --bg-tertiary: var(--gray-100);
  --bg-quaternary: var(--gray-200);
  --bg-inverse: var(--gray-950);
  --bg-brand-subtle: var(--brand-50);
  --bg-success-subtle: var(--success-50);
  --bg-warning-subtle: var(--warning-50);
  --bg-error-subtle: var(--error-50);
  --bg-overlay: rgb(10 13 18 / 0.6);

  --text-primary: var(--gray-900);
  --text-secondary: var(--gray-700);
  --text-tertiary: var(--gray-600);
  --text-quaternary: var(--gray-500);
  --text-placeholder: var(--gray-400);
  --text-inverse: #ffffff;
  --text-brand: var(--brand-700);
  --text-success: var(--success-700);
  --text-warning: var(--warning-700);
  --text-error: var(--error-700);

  --border-primary: var(--gray-300);
  --border-secondary: var(--gray-200);
  --border-tertiary: var(--gray-100);
  --border-brand: var(--brand-300);
  --border-error: var(--error-300);

  /* ── Type ──────────────────────────────────────────────────────────────── */
  --font-sans: 'Inter Variable', 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  --font-mono: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;
${TYPE.map(([n, s, lh, t]) => `  --${n}-size: ${s};\n  --${n}-line: ${lh};\n  --${n}-tracking: ${t};`).join('\n')}

  /* ── Spacing (Untitled UI scale, 4px base — matches Carbon's grid) ─────── */
${SPACING.map(([n, v]) => `  --space-${n}: ${v};`).join('\n')}

  /* ── Radius ────────────────────────────────────────────────────────────── */
${RADIUS.map(([n, v]) => `  --radius-${n}: ${v};`).join('\n')}
  /* Carbon keeps data surfaces nearly square; the app uses these. */
  --radius-data: ${layout.borderRadius02 ?? '2px'};
  --radius-data-lg: ${layout.borderRadius04 ?? '4px'};

  /* ── Elevation ─────────────────────────────────────────────────────────── */
${Object.entries(SHADOW).map(([n, v]) => `  --shadow-${n}: ${v};`).join('\n')}
  --ring-brand: 0 0 0 4px color-mix(in srgb, var(--brand) 24%, transparent);
  --ring-error: 0 0 0 4px var(--error-100);

  /* ── Motion (IBM Carbon) ───────────────────────────────────────────────── */
  --duration-fast-01: ${motion.durationFast01};
  --duration-fast-02: ${motion.durationFast02};
  --duration-moderate-01: ${motion.durationModerate01};
  --duration-moderate-02: ${motion.durationModerate02};
  --duration-slow-01: ${motion.durationSlow01};
  --ease-productive: ${motion.easings.standard.productive};
  --ease-expressive: ${motion.easings.standard.expressive};
  --ease-entrance: ${motion.easings.entrance.expressive};
  --ease-exit: ${motion.easings.exit.expressive};

  /* ── Layout ────────────────────────────────────────────────────────────── */
  --container-max: 1216px;
  --container-wide: 1400px;
  --container-pad: var(--space-6);
  --app-sidebar: 260px;
  --header-h: 68px;
}

@media (max-width: 767px) {
  :root { --container-pad: var(--space-4); }
}

/* ── Dark theme ──────────────────────────────────────────────────────────── */
:root[data-color-mode='dark'] {
  color-scheme: dark;

  --bg-primary: var(--gray-950);
  --bg-secondary: #131820;
  --bg-tertiary: #1a212b;
  --bg-quaternary: #232c38;
  --bg-inverse: var(--gray-25);
  --bg-brand-subtle: color-mix(in srgb, var(--brand) 16%, var(--gray-950));
  --bg-success-subtle: color-mix(in srgb, var(--success-500) 14%, var(--gray-950));
  --bg-warning-subtle: color-mix(in srgb, var(--warning-500) 14%, var(--gray-950));
  --bg-error-subtle: color-mix(in srgb, var(--error-500) 14%, var(--gray-950));
  --bg-overlay: rgb(0 0 0 / 0.7);

  --text-primary: var(--gray-25);
  --text-secondary: var(--gray-300);
  --text-tertiary: var(--gray-400);
  --text-quaternary: var(--gray-500);
  --text-placeholder: var(--gray-500);
  --text-inverse: var(--gray-950);
  --text-brand: color-mix(in srgb, var(--brand) 70%, #ffffff);
  --text-success: var(--success-400);
  --text-warning: var(--warning-400);
  --text-error: var(--error-400);

  --border-primary: #2c3644;
  --border-secondary: #232c38;
  --border-tertiary: #1a212b;
  --border-brand: color-mix(in srgb, var(--brand) 45%, transparent);
  --border-error: var(--error-800);

${Object.entries(SHADOW_DARK).map(([n, v]) => `  --shadow-${n}: ${v};`).join('\n')}
  --ring-brand: 0 0 0 4px color-mix(in srgb, var(--brand) 32%, transparent);
}

/* ═══════════════════════════════════════════════════════════════════════════
   Primer bridge — the components we keep inherit the tokens above.
   ═══════════════════════════════════════════════════════════════════════════ */
:root,
:root[data-color-mode='dark'] {
  --fontStack-sansSerif: var(--font-sans);
  --fontStack-system: var(--font-sans);
  --fontStack-monospace: var(--font-mono);

  --bgColor-default: var(--bg-primary);
  --bgColor-muted: var(--bg-secondary);
  --bgColor-inset: var(--bg-secondary);
  --bgColor-emphasis: var(--gray-900);
  --bgColor-neutral-muted: var(--bg-tertiary);
  --bgColor-accent-muted: var(--bg-brand-subtle);
  --bgColor-accent-emphasis: var(--brand);
  --bgColor-success-muted: var(--bg-success-subtle);
  --bgColor-success-emphasis: var(--success-600);
  --bgColor-attention-muted: var(--bg-warning-subtle);
  --bgColor-attention-emphasis: var(--warning-600);
  --bgColor-danger-muted: var(--bg-error-subtle);
  --bgColor-danger-emphasis: var(--error-600);
  --bgColor-done-muted: var(--bg-brand-subtle);
  --bgColor-done-emphasis: var(--brand-600);

  --fgColor-default: var(--text-primary);
  --fgColor-muted: var(--text-tertiary);
  --fgColor-onEmphasis: var(--text-inverse);
  --fgColor-accent: var(--text-brand);
  --fgColor-link: var(--text-brand);
  --fgColor-success: var(--text-success);
  --fgColor-attention: var(--text-warning);
  --fgColor-danger: var(--text-error);
  --fgColor-done: var(--text-brand);

  --borderColor-default: var(--border-secondary);
  --borderColor-muted: var(--border-tertiary);
  --borderColor-emphasis: var(--border-primary);
  --borderColor-accent-emphasis: var(--brand);
  --borderColor-success-emphasis: var(--success-600);
  --borderColor-attention-emphasis: var(--warning-600);
  --borderColor-danger-emphasis: var(--error-600);

  --borderRadius-small: var(--radius-sm);
  --borderRadius-medium: var(--radius-md);
  --borderRadius-large: var(--radius-xl);
  --borderRadius-full: var(--radius-full);

  --shadow-resting-small: var(--shadow-xs);
  --shadow-resting-medium: var(--shadow-sm);
  --shadow-floating-small: var(--shadow-md);
  --shadow-floating-medium: var(--shadow-lg);
  --shadow-floating-large: var(--shadow-xl);

  --header-bgColor: var(--bg-primary);
  --overlay-bgColor: var(--bg-primary);

  --button-primary-bgColor-rest: var(--brand);
  --button-primary-bgColor-hover: color-mix(in srgb, var(--brand) 86%, #000);
  --button-primary-bgColor-active: color-mix(in srgb, var(--brand) 78%, #000);
  --button-primary-borderColor-rest: color-mix(in srgb, var(--brand) 80%, #000);
  --button-primary-fgColor-rest: var(--brand-contrast);
  --button-default-bgColor-rest: var(--bg-primary);
  --button-default-bgColor-hover: var(--bg-secondary);
  --button-default-borderColor-rest: var(--border-primary);
}

/* Data-viz slots keep the validated categorical order, re-tinted per theme. */
:root {
  --viz-1: var(--brand);
  --viz-2: var(--warning-600);
  --viz-3: #6941c6;
  --viz-4: var(--success-600);
  --viz-5: #ce2c85;
  --viz-6: #b88700;
  --viz-gray: var(--gray-400);
  --viz-pos: var(--brand);
  --viz-neg: var(--error-500);
}
:root[data-color-mode='dark'] {
  --viz-1: color-mix(in srgb, var(--brand) 78%, #fff);
  --viz-2: var(--warning-400);
  --viz-3: #a78bfa;
  --viz-4: var(--success-400);
  --viz-5: #f472b6;
  --viz-6: #fbbf24;
  --viz-gray: var(--gray-500);
  --viz-pos: color-mix(in srgb, var(--brand) 78%, #fff);
  --viz-neg: var(--error-400);
}
`

writeFileSync(OUT, css)
console.log(`[tokens] ${css.split('\n').length} lines → src/styles/tokens.css`)
