/**
 * Brand photography, from Pexels.
 *
 * Product UI carries most of the visual weight, but a landing page still needs
 * one or two images that say what industry this is for. Three per product,
 * chosen from the domain's own photo brief, written as WebP at two widths with
 * the photographer credit recorded alongside (Pexels asks for attribution).
 *
 *   PEXELS_API_KEY=… node scripts/fetch-photos.mjs [slug…]
 */
import { execFileSync } from 'node:child_process'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)))
const OUT = path.join(ROOT, 'public', 'brand')

/** The env file lives at the repository root, outside this app. */
function apiKey() {
  if (process.env.PEXELS_API_KEY) return process.env.PEXELS_API_KEY
  const envPath = path.join(path.dirname(ROOT), '.env.local')
  const m = readFileSync(envPath, 'utf8').match(/^PEXELS_API_KEY=(.+)$/m)
  if (!m) throw new Error('PEXELS_API_KEY not found in env or ../.env.local')
  return m[1].trim()
}
const KEY = apiKey()

/** curl, because Node's TLS store rejects some CDNs in this environment. */
const curl = (url, headers = []) =>
  execFileSync('curl', ['-sL', '--max-time', '60', ...headers.flatMap((h) => ['-H', h]), url], {
    maxBuffer: 64 * 1024 * 1024, encoding: 'buffer',
  })

const domainSrc = readFileSync(path.join(ROOT, 'src', 'content', 'domain.ts'), 'utf8')
// Each top-level entry, then its own `photo:` line. Reading them separately
// means a new field in Domain cannot silently empty this, and the throw
// below means a stale parser fails loudly instead of writing an empty file.
const briefs = {}
for (const m of domainSrc.matchAll(/^ {2}'?([a-z-]+)'?: \{\r?\n([\s\S]*?)\r?\n {2}\},/gm)) {
  const photo = m[2].match(/\bphoto:\s*'([^']+)'/)
  if (photo) briefs[m[1]] = photo[1]
}
if (!Object.keys(briefs).length) throw new Error('No photo briefs parsed from domain.ts')

const slugs = process.argv.slice(2).length ? process.argv.slice(2) : Object.keys(briefs)
const ROLES = [
  { role: 'context', suffix: '' },
  { role: 'cta', suffix: ' wide' },
  { role: 'team', suffix: ' team working' },
  { role: 'detail', suffix: ' close up detail' },
  { role: 'people', suffix: ' professional portrait working' },
  { role: 'workspace', suffix: ' desk laptop workspace' },
]

const credits = {}

for (const slug of slugs) {
  const brief = briefs[slug]
  if (!brief) { console.warn(`[photos] no brief for ${slug}`); continue }
  const dir = path.join(OUT, slug)
  mkdirSync(dir, { recursive: true })
  credits[slug] = {}

  for (const { role, suffix } of ROLES) {
    const q = encodeURIComponent(brief + suffix)
    const url = `https://api.pexels.com/v1/search?query=${q}&per_page=8&orientation=landscape&size=large`
    let json
    try {
      json = JSON.parse(curl(url, [`Authorization: ${KEY}`]).toString('utf8'))
    } catch (e) {
      console.warn(`[photos] ${slug}/${role}: search failed — ${String(e).slice(0, 120)}`)
      continue
    }
    const photos = (json.photos ?? []).filter((p) => p.width / p.height > 1.3)
    // Deterministic pick per role so re-running does not churn the assets.
    const pick = photos[(slug.length + role.length) % Math.max(1, photos.length)]
    if (!pick) { console.warn(`[photos] ${slug}/${role}: nothing landscape for "${brief}${suffix}"`); continue }

    for (const [name, w] of [[`${role}.jpg`, 1600], [`${role}-800.jpg`, 800]]) {
      const src = `${pick.src.original}?auto=compress&cs=tinysrgb&fit=crop&w=${w}&h=${Math.round(w * 0.5625)}`
      const bytes = curl(src)
      writeFileSync(path.join(dir, name), bytes)
    }
    credits[slug][role] = { photographer: pick.photographer, url: pick.url, alt: pick.alt || brief }
    console.log(`[photos] ${slug}/${role} ← ${pick.photographer} (${pick.id})`)
  }
}

writeFileSync(path.join(OUT, 'credits.json'), JSON.stringify(credits, null, 2))

// Emit a typed module so components can render the attribution Pexels asks for.
const roles = [...new Set(Object.values(credits).flatMap((o) => Object.keys(o)))]
const lines = [
  '/**',
  ' * GENERATED by scripts/fetch-photos.mjs — do not edit by hand.',
  ' * Brand photography from Pexels, with the attribution their licence asks for.',
  ' */',
  "import type { Slug } from './types'",
  '',
  'export type PhotoRole = ' + roles.map((r) => "'" + r + "'").join(' | '),
  '',
  'export interface Photo { photographer: string; url: string; alt: string }',
  '',
  'export const PHOTOS: Partial<Record<Slug, Partial<Record<PhotoRole, Photo>>>> = ' + JSON.stringify(credits, null, 2),
  '',
  'export const photo = (slug: Slug, role: PhotoRole) => PHOTOS[slug]?.[role]',
  '',
  'export function photoSrc(slug: Slug, role: PhotoRole, small = false) {',
  '  return [String(slug), String(role) + (small ? String("-800") : String("")) + String(".jpg")]',
  '    .reduce((a, b) => a + "/" + b, "/brand")',
  '}',
  '',
].join(String.fromCharCode(10))
writeFileSync(path.join(ROOT, 'src', 'content', 'photos.ts'), lines)
console.log(`[photos] credits → public/brand/credits.json + src/content/photos.ts`)
