import puppeteer from "puppeteer";
import { clickExact, dialogText } from "./_vmem_lib2.mjs";
const BASE="http://localhost:3015";
const browser = await puppeteer.launch({headless:"new",args:["--no-sandbox"]});
const page = await browser.newPage(); await page.setViewport({width:1280,height:900});
page.on("pageerror",e=>console.log("PAGEERROR:",e.message.slice(0,120)));
await page.goto(BASE+"/",{waitUntil:"domcontentloaded"});
await page.evaluate(()=>{localStorage.setItem("wafe:mode","demo");localStorage.setItem("wafe:demo:view-as","mem-ife");});
await page.goto(BASE+"/create/memories/albums/album-garden",{waitUntil:"domcontentloaded"});
await new Promise(x=>setTimeout(x,4000));
console.log("share:", await clickExact(page,"Share"));
await new Promise(x=>setTimeout(x,1500));
console.log("DIALOG:", (await dialogText(page)).slice(0,700).replace(/\n+/g," / "));
const btn = await page.evaluate(()=>{ const d=Array.from(document.querySelectorAll("dialog")).find(x=>x.open); if(!d) return "no dialog"; const b=Array.from(d.querySelectorAll("button")).map(b=>JSON.stringify(b.innerText.trim())); return b.join(", "); });
console.log("BUTTONS:", btn);
const r = await page.evaluate(()=>{ const d=Array.from(document.querySelectorAll("dialog")).find(x=>x.open); const b=Array.from(d.querySelectorAll("button")).find(b=>b.innerText.trim()==="Make a link"); if(!b) return "not found"; b.click(); return "clicked"; });
console.log("make:", r);
await new Promise(x=>setTimeout(x,2500));
console.log("AFTER:", (await dialogText(page)).slice(-500).replace(/\n+/g," / "));
console.log("links:", await page.evaluate(()=>JSON.parse(localStorage.getItem("wafe:demo:memories:v1")).links.length));
await browser.close();
