import { boot, go, shot } from "./_vmem_lib.mjs";
import { clickExact, dialogText } from "./_vmem_lib2.mjs";
const { browser, page, errors } = await boot({ width: 390, height: 844 });
await go(page, "/create/memories", 2500);
console.log("new album:", await clickExact(page, "New album"));
await new Promise(r=>setTimeout(r,900));
const typed = await page.evaluate(()=>{
  const d = Array.from(document.querySelectorAll("dialog")).find(x=>x.open); if(!d) return "no dialog";
  const inp = d.querySelector('input[type=text], input:not([type]):not([type=date])');
  if(!inp) return "no input: "+Array.from(d.querySelectorAll("input")).map(i=>i.type).join(",");
  const set = Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype,"value").set;
  set.call(inp, "Verifier test album"); inp.dispatchEvent(new Event("input",{bubbles:true}));
  return "ok";
});
console.log("typed:", typed);
await new Promise(r=>setTimeout(r,400));
console.log("create:", await clickExact(page, "Create the album"));
await new Promise(r=>setTimeout(r,2500));
console.log("URL after create:", page.url());
const main1 = await page.evaluate(()=>document.querySelector("main")?.innerText||"");
console.log("PAGE:", main1.slice(0,400).replace(/\n+/g," / "));
await shot(page,"17-new-album-empty");
await page.reload({waitUntil:"domcontentloaded"}); await new Promise(r=>setTimeout(r,3500));
console.log("AFTER RELOAD:", (await page.evaluate(()=>document.querySelector("main")?.innerText||"")).slice(0,200).replace(/\n+/g," / "));
console.log("delete clicked:", await clickExact(page, "Delete"));
await new Promise(r=>setTimeout(r,1000));
console.log("CONFIRM:", (await dialogText(page)).slice(0,260).replace(/\n+/g," / "));
await shot(page,"18-confirm");
console.log("errors:", errors.filter(e=>e.startsWith("pageerror")).slice(0,3).join(" ~ ")||"none");
await browser.close();
