import { Link } from 'react-router-dom';
import PageMeta from '@/seo/PageMeta';
import { ButtonLink, PageHeading, useLoad, Loading, Notice, ActionButton } from '@/components/opportunities/UI';
import { checkout, plans } from '@/lib/opportunities/repository';
import { useAuth } from '@/auth/AuthProvider';

export function OpportunityPricingPage() {
    const state = useLoad(plans, 'plans'); const { user } = useAuth();
    return <><PageMeta title="Phoxta plans | Free, Explorer, Builder and Studio" description="Start discovering for free. Choose more depth, tools or team capacity as your opportunity develops." path="/pricing" /><PageHeading eyebrow="Plans for your next chapter" title="Start with curiosity. Add depth as you go.">Discovery, research and venture creation subscriptions. Business packages and cohort services are separate purchases.</PageHeading>{state.loading && <Loading />}{state.error && <Notice danger>{state.error}</Notice>}<div className="p2-grid two">{state.data?.map(p => <article className="p2-card" key={p.plan_key}><span className="p2-eyebrow">{p.label}</span><p className="p2-price">{p.monthly_gbp === 0 ? 'Free' : `£${p.monthly_gbp}`}<small>{p.monthly_gbp > 0 ? ' / month' : ''}</small></p><h2>{({ free: 'Find a place to start.', explorer: 'Investigate with more depth.', builder: 'Turn learning into a business.', studio: 'Build together, across ventures.' } as Record<string, string>)[p.plan_key]}</h2><div className="p2-detail-list"><div>{p.limits.active} active opportunities</div><div>{p.limits.research} deep research jobs / month</div><div>{p.limits.evidence} evidence items per opportunity</div><div>{p.limits.experiments ?? 'Unlimited fair-use'} experiments{p.limits.experiment_period === 'month' ? ' / month' : ' total'}</div><div>Shape: {p.limits.shape} · Build: {p.limits.build}</div><div>{p.limits.seats} {p.limits.seats === 1 ? 'seat' : 'seats'} · School: {p.limits.school}</div></div>{p.plan_key === 'free' || !user ? <ButtonLink to={user ? '/app/discover' : '/signup'}>{p.plan_key === 'free' ? 'Start free' : 'Create an account'}</ButtonLink> : <ActionButton secondary={false} action={async () => { window.location.assign(await checkout(p.plan_key)); }}>Choose {p.label}</ActionButton>}</article>)}</div><section className="p2-public-section" style={{ marginTop: 35 }}><h2>Your work stays yours when your plan changes.</h2><p>A lower plan limits new work beyond its allowance. It does not delete existing opportunity records. Research usage resets monthly; Free experiments are a lifetime allowance.</p><Link to="/dashboard/billing">Manage an existing Operating Console subscription ↗</Link></section></>;
}
