import { useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { useAuth } from '@/auth/AuthProvider';
import { supabase } from '@/lib/supabaseClient';
import { workspaces } from '@/lib/opportunities/repository';
import { SCHOOL_MODULES } from '@/lib/opportunities/school';
import { ActionButton, Badge, ButtonLink, Loading, Notice, PageHeading, useLoad } from '@/components/opportunities/UI';

export default function OpportunitySchoolPage() {
    const path = useLocation().pathname; const course = path.match(/^\/app\/school\/([^/]+)/)?.[1]; const { user } = useAuth(); const [workspace, setWorkspace] = useState('');
    const state = useLoad(async () => { const [all, progress] = await Promise.all([workspaces(), supabase.from('opportunity_school_progress').select('module_id,workspace_id,completed_at')]); if (progress.error) throw new Error(progress.error.message); return { all, progress: progress.data }; }, user?.id ?? '');
    const module = SCHOOL_MODULES.find(m => m.id === course);
    const selected = workspace || state.data?.all[0]?.id || '';
    async function complete() { const { error } = await supabase.rpc('opportunity_complete_lesson', { p_module: module!.id, p_workspace: selected }); if (error) throw new Error(error.message); }
    return <><PageHeading eyebrow="Phoxta Startup School - Free" title={module?.title ?? 'Learn by building something real.'}>{module?.outcome ?? 'Recognise, investigate and build business opportunities while you work on a real opportunity inside Phoxta. Every module is free.'}</PageHeading>{state.loading && <Loading />}{state.error && <Notice danger>{state.error}</Notice>}{module ? <div className="p2-stack"><section className="p2-panel"><p className="p2-readable">{module.lesson}</p></section><section className="p2-panel"><h2>Illustrative example</h2><p className="p2-readable">{module.example}</p></section><section className="p2-panel"><h2>Create your {module.artifact}</h2><p className="p2-readable">{module.exercise}</p><div className="p2-detail-list">{module.template.map(t => <div key={t}>{t}</div>)}</div>{state.data?.all.length ? <><label className="p2-field" style={{ margin: '20px 0' }}><span>Apply this to an opportunity</span><select value={selected} onChange={e => setWorkspace(e.target.value)}>{state.data.all.map(w => <option value={w.id} key={w.id}>{w.title}</option>)}</select></label><div className="p2-actions"><ButtonLink to={`/app/opportunities/${selected}/${module.target}?lesson=${module.id}`}>Create or revise artifact</ButtonLink><ActionButton action={complete} onSuccess={state.reload}>Check artifact and complete lesson</ActionButton></div></> : <div style={{ marginTop: 20 }}><ButtonLink to="/app/discover">Create an opportunity to practise</ButtonLink></div>}<p className="p2-muted" style={{ marginTop: 20 }}>Completion requires the artifact or decision this lesson teaches. Reading alone does not complete the module.</p></section><Link to="/app/school">← All modules</Link></div> : <><Notice>All twelve modules, exercises and saved progress are free. Enter wherever your current business question takes you.</Notice><div className="p2-grid">{SCHOOL_MODULES.map((m, index) => <article className="p2-card" key={m.id}><div className="p2-card-top"><span className="p2-eyebrow">Module {String(index + 1).padStart(2, '0')}</span>{state.data?.progress.some(p => p.module_id === m.id) && <Badge>Artifact completed</Badge>}</div><h2>{m.title}</h2><p>{m.outcome}</p><div className="p2-uncertainty"><strong>You will create</strong>{m.artifact}</div><ButtonLink to={`/app/school/${m.id}/practice`} secondary>Start learning</ButtonLink></article>)}</div></>}</>;
}
