import type { Blueprint } from "@/lib/db/marketplace";

/**
 * Homepage-safe catalogue data used while the live catalogue is loading or
 * unavailable. Keep this aligned with the businesses currently presented on
 * the public homepage so discovery never falls back to invented products.
 */
export const HOMEPAGE_BLUEPRINTS: Blueprint[] = [
  {
    id: "niche-apparel",
    slug: "niche-apparel",
    name: "Fashion Store",
    tagline: "A modern fashion store with online ordering, checkout and an AI stylist.",
    description: "A ready-to-launch fashion commerce business.",
    vertical: "E-commerce",
    tier: "standard",
    price_cents: 250000,
    currency: "GBP",
    cover_url: null,
    demo_url: "https://aurelia-demo.aurelia.phoxta.com/",
    verified: true,
    ai_included: true,
    metrics: {},
  },
  {
    id: "restaurant-orders",
    slug: "restaurant-orders",
    name: "Restaurant + Orders",
    tagline: "Online ordering, order tracking, catering requests and an AI concierge.",
    description: "A digital-first restaurant business.",
    vertical: "Restaurant",
    tier: "standard",
    price_cents: 250000,
    currency: "GBP",
    cover_url: null,
    demo_url: "https://saveur-demo.dine.phoxta.com/",
    verified: true,
    ai_included: true,
    metrics: {},
  },
  {
    id: "gearo",
    slug: "gearo",
    name: "Furniture Store",
    tagline: "A furniture and workspace store with checkout and an AI shopping assistant.",
    description: "A ready-to-launch furniture commerce business.",
    vertical: "Furniture",
    tier: "standard",
    price_cents: 250000,
    currency: "GBP",
    cover_url: null,
    demo_url: "https://gearo-demo.gearo.phoxta.com/",
    verified: true,
    ai_included: true,
    metrics: {},
  },
  {
    id: "coir-six",
    slug: "coir-six",
    name: "Coir Six Learning",
    tagline: "Courses, live sessions, quizzes, groups, certificates and a learner dashboard.",
    description: "A ready-to-launch online education business.",
    vertical: "Education",
    tier: "standard",
    price_cents: 250000,
    currency: "GBP",
    cover_url: null,
    demo_url: "https://demo.coir-six.phoxta.com/",
    verified: true,
    ai_included: true,
    metrics: {},
  },
  {
    id: "ferne",
    slug: "ferne",
    name: "Ferne Botanical Skincare",
    tagline: "An editorial skincare storefront with refills and a guided skin adviser.",
    description: "A ready-to-launch botanical skincare business.",
    vertical: "Beauty",
    tier: "premium",
    price_cents: 300000,
    currency: "GBP",
    cover_url: null,
    demo_url: "https://demo.ferne.phoxta.com/",
    verified: true,
    ai_included: true,
    metrics: {},
  },
  {
    id: "wamwam",
    slug: "wamwam",
    name: "WamWam Experiences",
    tagline: "A bookable experiences storefront for tours, workshops and days out.",
    description: "A ready-to-launch experiences business.",
    vertical: "Experiences",
    tier: "premium",
    price_cents: 360000,
    currency: "GBP",
    cover_url: null,
    demo_url: "https://demo.wamwam.phoxta.com/",
    verified: true,
    ai_included: true,
    metrics: {},
  },
];
