import { useEffect, useState } from "react";
import { Camera, CreditCard, Headphones, LogOut, Maximize2, Minimize2, Settings, UserRound, Users, X } from "lucide-react";
import { supabase } from "@/lib/supabaseClient";
import { getSubscriptionForOrg, type Subscription } from "@/lib/db/billing";
import { inviteMember, listInvitations, type Invitation } from "@/lib/db/collaboration";
import { listMembers, type OrgMember } from "@/lib/db/ops/agent";
import { clearBehaviorMemory, getLearningSettings, saveLearningSettings, type LearningSettings } from "@/lib/db/productWorkspace";

export type AccountView = "profile" | "billing" | "settings" | "team" | "invite" | "support" | "logout";
type Props = { view: AccountView; expanded: boolean; avatar: string; identity: string; business: string; businessId: string; userId: string; onClose: () => void; onExpand: () => void; onUpload: () => void; onSignOut: () => void };
const initials = (value: string) => value.split(/[@\s._-]+/).filter(Boolean).slice(0, 2).map((part) => part[0]?.toUpperCase()).join("") || "PX";

export default function AccountPanel(props: Props) {
  const { view, expanded, avatar, identity, business, businessId, userId, onClose, onExpand, onUpload, onSignOut } = props;
  const [name, setName] = useState(""); const [notice, setNotice] = useState(""); const [subscription, setSubscription] = useState<Subscription | null>(null); const [members, setMembers] = useState<OrgMember[]>([]); const [invites, setInvites] = useState<Invitation[]>([]); const [inviteEmail, setInviteEmail] = useState(""); const [inviteRole, setInviteRole] = useState<Invitation["role"]>("staff"); const [support, setSupport] = useState(""); const [learning, setLearning] = useState<LearningSettings | null>(null);
  const titles: Record<AccountView, string> = { profile: "Profile", billing: "Billing", settings: "Settings & privacy", team: "Team", invite: "Invite users", support: "Support", logout: "Log out" };
  useEffect(() => { setNotice(""); void supabase.auth.getUser().then(({ data }) => setName(String(data.user?.user_metadata?.full_name ?? data.user?.user_metadata?.name ?? ""))); }, [view]);
  useEffect(() => { if (view === "billing") void getSubscriptionForOrg(businessId).then((result) => { setSubscription(result.data); setNotice(result.error ?? ""); }); }, [businessId, view]);
  useEffect(() => { if (view === "team" || view === "invite") void Promise.all([listMembers(businessId), listInvitations(businessId)]).then(([memberResult, inviteResult]) => { setMembers(memberResult.data); setInvites(inviteResult.data); setNotice(memberResult.error || inviteResult.error || ""); }); }, [businessId, view]);
  useEffect(() => { if (view === "settings") void getLearningSettings(businessId, userId).then((result) => { setLearning(result.data); setNotice(result.error ?? ""); }); }, [businessId, userId, view]);
  async function saveProfile() { const { error } = await supabase.auth.updateUser({ data: { full_name: name.trim(), avatar_url: avatar || undefined } }); setNotice(error?.message ?? "Profile saved."); }
  async function sendInvite() { const result = await inviteMember(businessId, userId, inviteEmail, inviteRole); setNotice(result.error ?? "Invitation sent."); if (!result.error) { setInviteEmail(""); const refreshed = await listInvitations(businessId); setInvites(refreshed.data); } }
  async function savePrivacy() { if (!learning) return; const result = await saveLearningSettings(learning); setNotice(result.error ?? "Privacy settings saved."); if (!result.error) window.dispatchEvent(new CustomEvent("phoxta:learning-settings-changed", { detail: { businessId, userId, enabled: learning.enabled } })); }
  async function clearLearning() { const result = await clearBehaviorMemory(businessId, userId); setNotice(result.error ?? "Your learned work patterns were deleted."); if (!result.error) window.dispatchEvent(new CustomEvent("phoxta:learning-settings-changed", { detail: { businessId, userId, enabled: learning?.enabled ?? false } })); }
  async function sendSupport() { const { error } = await supabase.functions.invoke("platform-lead", { body: { source: "in_app_support", email: identity, organization_id: businessId, message: support } }); setNotice(error?.message ?? "Support request sent."); if (!error) setSupport(""); }
  const icon = view === "billing" ? <CreditCard size={17} /> : view === "team" || view === "invite" ? <Users size={17} /> : view === "support" ? <Headphones size={17} /> : view === "logout" ? <LogOut size={17} /> : view === "settings" ? <Settings size={17} /> : <UserRound size={17} />;
  return <><button className="pxc-account-scrim" aria-label="Close account popup" onClick={onClose} /><section className={`pxc-account-popup${expanded ? " is-expanded" : ""}`} role="dialog" aria-modal="true" aria-label={titles[view]}><header><div><span className="pxc-popup-icon">{icon}</span><div><strong>{titles[view]}</strong><small>{business}</small></div></div><div><button onClick={onExpand} aria-label={expanded ? "Reduce popup" : "Expand popup"}>{expanded ? <Minimize2 size={17} /> : <Maximize2 size={17} />}</button><button onClick={onClose} aria-label="Close popup"><X size={18} /></button></div></header><div className="pxc-account-popup-body">
    {view === "profile" && <><div className="pxc-profile-photo"><span>{avatar ? <img src={avatar} alt="Current profile" /> : initials(identity)}</span><div><strong>Profile image</strong><small>JPG, PNG or WebP</small><button onClick={onUpload}><Camera size={14} /> Upload image</button></div></div><div className="pxc-popup-form"><label>Email<input value={identity} disabled /></label><label>Display name<input value={name} onChange={(event) => setName(event.target.value)} /></label><button onClick={() => void saveProfile()}>Save profile</button></div></>}
    {view === "billing" && <><div className="pxc-popup-summary"><span>Current plan</span><strong>{subscription?.plan ?? "No active plan"}</strong><small>{subscription?.status ?? "Choose a plan when this business is ready"}</small></div>{subscription && <div className="pxc-popup-list"><div><span>Billing status</span><strong>{subscription.status}</strong></div><div><span>Current period</span><strong>{subscription.current_period_end ? new Date(subscription.current_period_end).toLocaleDateString() : "No renewal date"}</strong></div><div><span>Amount</span><strong>{new Intl.NumberFormat(undefined, { style: "currency", currency: subscription.currency }).format(subscription.amount_cents / 100)}</strong></div></div>}</>}
    {view === "settings" && learning && <div className="pxc-popup-form"><label className="pxc-account-check"><input type="checkbox" checked={learning.enabled} onChange={(event) => setLearning({ ...learning, enabled: event.target.checked })} />Learn from my work patterns</label><label className="pxc-account-check"><input type="checkbox" checked={learning.capture_navigation} onChange={(event) => setLearning({ ...learning, capture_navigation: event.target.checked })} />Use navigation patterns</label><label className="pxc-account-check"><input type="checkbox" checked={learning.capture_response_metrics} onChange={(event) => setLearning({ ...learning, capture_response_metrics: event.target.checked })} />Use response timing and outcome metrics</label><label>Retention<select value={learning.retention_days} onChange={(event) => setLearning({ ...learning, retention_days: Number(event.target.value) })}><option value={7}>7 days</option><option value={30}>30 days</option><option value={90}>90 days</option></select></label><small>Typed text, message bodies, passwords, payment fields and file contents are never stored as learning analytics.</small><button onClick={() => void savePrivacy()}>Save privacy settings</button><button className="secondary" onClick={() => void clearLearning()}>Delete learned patterns</button></div>}
    {view === "team" && <div className="pxc-popup-list">{members.map((member) => <div key={member.user_id}><span>{member.full_name || member.user_id.slice(0, 8)}</span><strong>{member.role}</strong></div>)}{invites.filter((invite) => invite.status === "pending").map((invite) => <div key={invite.id}><span>{invite.email}</span><strong>Invited · {invite.role}</strong></div>)}</div>}
    {view === "invite" && <div className="pxc-popup-form"><label>Email address<input type="email" value={inviteEmail} onChange={(event) => setInviteEmail(event.target.value)} placeholder="name@company.com" /></label><label>Role<select value={inviteRole} onChange={(event) => setInviteRole(event.target.value as Invitation["role"])}><option value="staff">Member</option><option value="admin">Administrator</option><option value="viewer">Viewer</option></select></label><button disabled={!inviteEmail.trim()} onClick={() => void sendInvite()}>Send invitation</button></div>}
    {view === "support" && <div className="pxc-popup-form"><label>How can we help?<textarea value={support} onChange={(event) => setSupport(event.target.value)} placeholder="Describe what you need help with" /></label><button disabled={!support.trim()} onClick={() => void sendSupport()}>Send to support</button></div>}
    {view === "logout" && <div className="pxc-logout-confirm"><p>Sign out of Phoxta on this device?</p><div><button onClick={onClose}>Cancel</button><button onClick={onSignOut}>Log out</button></div></div>}
    {notice && <p className="pxc-account-notice" role="status">{notice}</p>}
  </div></section></>;
}
