import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';
import path from 'node:path';

const library = process.env.PHOXTA_PGLITE_PATH || 'node_modules/@electric-sql/pglite/dist/index.js';
const { PGlite } = await import(pathToFileURL(path.resolve(library)).href);
const db = new PGlite();
await db.exec(`
 create role anon; create role authenticated; create role service_role bypassrls;
 create schema auth;
 create schema storage;
 create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 grant usage on schema public,auth to anon,authenticated,service_role;
 grant execute on function auth.uid() to anon,authenticated,service_role;
 create table public.user_profiles(user_id uuid unique references auth.users(id),onboarding_completed boolean,onboarding_completed_at timestamptz);
 create table public.organizations(id uuid primary key default gen_random_uuid(),owner_user_id uuid references auth.users(id),name text,metadata jsonb);
 create table public.organization_memberships(organization_id uuid references organizations(id),user_id uuid references auth.users(id),role text,primary key(organization_id,user_id));
 create table public.ideas(id uuid primary key,user_id uuid,title text,idea_seed text,ai_profile jsonb,report jsonb,status text);
 create table public.platform_admins(user_id uuid primary key);
 create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
 create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text references storage.buckets(id),name text);
 create function storage.foldername(p_name text) returns text[] language sql immutable as $$select (regexp_split_to_array(p_name,'/'))[1:greatest(array_length(regexp_split_to_array(p_name,'/'),1)-1,0)]$$;
 alter table storage.objects enable row level security;
 grant usage on schema storage to anon,authenticated,service_role;
 grant select,insert,update,delete on storage.objects to authenticated;
 create function public.app_is_platform_admin() returns boolean language sql stable security definer as $$select exists(select 1 from platform_admins where user_id=auth.uid())$$;
 insert into auth.users values('10000000-0000-4000-8000-000000000001','owner@example.test',now()),('10000000-0000-4000-8000-000000000002','stranger@example.test',now()),('10000000-0000-4000-8000-000000000003','viewer@example.test',now()),('10000000-0000-4000-8000-000000000004','invitee@example.test',now());
`);
// Use the actual catalogue table definitions, not approximate School stubs.
for (const file of ['0147_coir_six.sql', '0155_startup_school_seed.sql']) {
    const sql = await readFile(`supabase/migrations/${file}`, 'utf8');
    for (const match of sql.matchAll(/create table if not exists public\.cs_(?:categories|mentors|courses|modules|lessons|profiles|lesson_progress|lesson_blocks) \([\s\S]*?\n\);/g)) await db.exec(match[0]);
}
await db.exec(`alter table cs_courses add column final_project_title text not null default ''; alter table cs_courses add column final_project_description text not null default ''; alter table organizations add column slug text, add column vertical text, add column app_path text;`);
for (const file of ['0180_phoxta_opportunity_foundation.sql','0181_phoxta_opportunity_commands.sql','0182_phoxta_school_artifact_progress.sql','0183_phoxta_editorial_businesses.sql','0184_phoxta_research_queue.sql','0185_phoxta_opportunity_billing.sql','0186_phoxta_legacy_migration.sql','0187_phoxta_school_curriculum.sql','0188_phoxta_account_workflows.sql','0189_phoxta_discovery_search.sql','0190_phoxta_collaboration.sql','0191_phoxta_workflow_dry_runs.sql','0192_phoxta_storage.sql','0193_phoxta_account_deletion.sql']) {
    await db.exec(await readFile(`supabase/migrations/${file}`, 'utf8'));
    console.log(`Applied ${file}`);
}
const owner = '10000000-0000-4000-8000-000000000001';
const stranger = '10000000-0000-4000-8000-000000000002';
const viewer = '10000000-0000-4000-8000-000000000003';
const invitee = '10000000-0000-4000-8000-000000000004';
async function asUser(id) { await db.exec(`reset role; set role authenticated; select set_config('request.jwt.claim.sub','${id}',false);`); }
async function command(action,data={}) { return (await db.query('select public.opportunity_command($1,$2::jsonb) as result',[action,JSON.stringify(data)])).rows[0].result; }
async function rpcTeam(action,data={}) { return (await db.query('select public.opportunity_team_action($1,$2::jsonb) as result',[action,JSON.stringify(data)])).rows[0].result; }
await asUser(owner);
const workspace = (await command('create',{title:'Test opportunity',thesis:'A customer problem to investigate',origin:'problem'})).id;
await assert.rejects(command('create',{title:'Over the free limit',origin:'idea'}),/plan limit/);
await assert.rejects(db.query('insert into opportunity_workspaces(org_id,owner_user_id,title,origin) select org_id,owner_user_id,$1,$2 from opportunity_workspaces limit 1',['Bypass','idea']),/permission denied/);
await asUser(stranger);
assert.equal((await db.query('select * from opportunity_workspaces')).rows.length,0);
await assert.rejects(command('assumption',{workspace_id:workspace,class:'problem',statement:'Cross-user write',importance:5,uncertainty:5}),/access denied/);
await asUser(owner);
const assumption=(await command('assumption',{workspace_id:workspace,class:'problem',statement:'The customer experiences the problem',importance:5,uncertainty:5})).id;
await assert.rejects(command('assumption',{workspace_id:workspace,id:assumption,status:'supported'}),/Link observed/);
const ai=(await command('evidence',{workspace_id:workspace,evidence_type:'ai_hypothesis',claim:'An AI thinks the problem exists'})).id;
await assert.rejects(command('brief',{workspace_id:workspace,section_key:'problem',version:0,content:{text:'The problem is proven',kind:'known',evidence_ids:[ai]}}),/Known claims require/);
await assert.rejects(command('evidence',{workspace_id:workspace,evidence_type:'external',claim:'Unsourced claim'}),/check constraint/);
const evidence=(await command('evidence',{workspace_id:workspace,evidence_type:'customer_interview',claim:'Observed a workflow',source_title:'Interview reference 1'})).id;
await command('link_evidence',{workspace_id:workspace,evidence_id:evidence,assumption_id:assumption,relation:'support'});
await command('assumption',{workspace_id:workspace,id:assumption,status:'supported'});
await command('brief',{workspace_id:workspace,section_key:'problem',version:0,content:{text:'An interview described the workflow',kind:'known',evidence_ids:[evidence]}});
await assert.rejects(command('brief',{workspace_id:workspace,section_key:'problem',version:0,content:{text:'Stale edit',kind:'inferred',evidence_ids:[]}}),/changed/);
const experiment=(await command('experiment',{workspace_id:workspace,type:'interview',hypothesis:'A second customer has the same problem',method:'Interview one customer',success_criteria:'Observed example of the same friction'})).id;
await assert.rejects(command('experiment',{workspace_id:workspace,id:experiment,status:'completed',learning:'Skipped the test'}),/Invalid experiment/);
await command('experiment',{workspace_id:workspace,id:experiment,status:'ready'});
await command('experiment',{workspace_id:workspace,id:experiment,status:'running'});
await assert.rejects(command('experiment',{workspace_id:workspace,id:experiment,status:'completed'}),/Record what/);
await command('experiment',{workspace_id:workspace,id:experiment,status:'inconclusive',learning:'No concrete example yet'});
await assert.rejects(command('decision',{workspace_id:workspace,decision:'pause',rationale:'Need evidence'}),/Confirm/);
await command('decision',{workspace_id:workspace,decision:'pause',rationale:'Need evidence',confirmed:true});
assert.equal((await db.query('select lifecycle_state from opportunity_workspaces where id=$1',[workspace])).rows[0].lifecycle_state,'paused');
await db.exec('reset role');
await assert.rejects(db.query('update decision_reviews set rationale=$1',['Rewrite history']),/immutable/);
await db.query('insert into workspace_members(workspace_id,user_id,role) values($1,$2,$3)',[workspace,viewer,'viewer']);
await asUser(viewer);
assert.equal((await db.query('select * from opportunity_workspaces')).rows.length,1);
await assert.rejects(command('evidence',{workspace_id:workspace,evidence_type:'user_note',claim:'Viewer mutation'}),/read-only/);
await asUser(owner);
const workspaceOrg = (await db.query('select org_id from opportunity_workspaces where id=$1',[workspace])).rows[0].org_id;
await db.query("insert into storage.objects(bucket_id,name) values('phoxta-opportunity-private',$1)",[`${workspaceOrg}/${workspace}/evidence.pdf`]);
await asUser(viewer);
assert.equal((await db.query("select count(*)::integer count from storage.objects where bucket_id='phoxta-opportunity-private'")).rows[0].count,1);
await asUser(stranger);
assert.equal((await db.query("select count(*)::integer count from storage.objects where bucket_id='phoxta-opportunity-private'")).rows[0].count,0);
console.log('PASS: private storage paths follow workspace read and write roles.');
await db.exec('reset role');
await db.query("insert into opportunity_entitlement_overrides(org_id,limits) select org_id,'{\"seats\":5}'::jsonb from opportunity_workspaces where id=$1 on conflict(org_id) do update set limits=excluded.limits",[workspace]);
await asUser(owner);
const invitation = (await rpcTeam('invite',{ workspace_id: workspace, email: 'invitee@example.test', role: 'researcher' })).id;
await asUser(invitee);
assert.equal((await db.query('select * from opportunity_workspaces')).rows.length,0);
assert.equal((await db.query('select opportunity_team_inbox() as inbox')).rows[0].inbox.invitations.length,1);
await rpcTeam('accept',{ id: invitation });
assert.equal((await db.query('select * from opportunity_workspaces')).rows.length,1);
await asUser(owner);
const transfer = (await rpcTeam('transfer',{ workspace_id: workspace, user_id: invitee, confirmed: true })).id;
await asUser(invitee);
await rpcTeam('accept_transfer',{ id: transfer, confirmed: true });
assert.equal((await db.query('select owner_user_id from opportunity_workspaces where id=$1',[workspace])).rows[0].owner_user_id,invitee);
const transferBack = (await rpcTeam('transfer',{ workspace_id: workspace, user_id: owner, confirmed: true })).id;
await asUser(owner);
await rpcTeam('accept_transfer',{ id: transferBack, confirmed: true });
assert.equal((await db.query('select owner_user_id from opportunity_workspaces where id=$1',[workspace])).rows[0].owner_user_id,owner);
console.log('PASS: invitations require acceptance and ownership transfer requires both parties.');
await db.exec('reset role; set role anon;');
assert.equal((await db.query('select * from global_opportunities')).rows.length,0);
await assert.rejects(db.query('select * from opportunity_workspaces'),/permission denied/);
// Durable research: pre-spend limits, repeated sources and stale worker leases.
await asUser(owner);
const job = (await command('research', { workspace_id: workspace, question: 'What changed in this market?', job_type: 'opportunity', idempotency_key: '30000000-0000-4000-8000-000000000001' })).id;
await db.exec('reset role');
const rpc = async (sql, args = []) => (await db.query(sql, args)).rows[0];
let claimed = (await rpc('select opportunity_claim_research() as job')).job;
assert.equal(claimed.id, job);
await db.query('select opportunity_research_stage($1,$2,$3,$4)', [job, claimed.lease_token, 'fetching', .49]);
await assert.rejects(db.query('select opportunity_research_stage($1,$2,$3,$4)', [job, claimed.lease_token, 'synthesizing', .02]), /budget exceeded/);
const candidate = { evidence_id: '40000000-0000-4000-8000-000000000001', url: 'https://example.org/research', title: 'Original study', publisher: 'Example', published_at: null, excerpt: 'An observed signal requiring review.' };
const artifact = id => ({ claims: [{ text: candidate.excerpt, kind: 'sourced', evidence_ids: [id] }] });
await db.query('select opportunity_finish_research($1,$2,$3::jsonb,$4::jsonb)', [job, claimed.lease_token, JSON.stringify([candidate]), JSON.stringify(artifact(candidate.evidence_id))]);
await asUser(owner);
const refresh = (await command('research', { workspace_id: workspace, question: 'Refresh the original source', job_type: 'refresh', idempotency_key: '30000000-0000-4000-8000-000000000002' })).id;
await db.exec('reset role');
assert.equal((await rpc("select quantity from opportunity_usage where feature_key='refresh'")).quantity, 1);
assert.equal((await rpc("select quantity from opportunity_usage where feature_key='research'")).quantity, 1);
claimed = (await rpc('select opportunity_claim_research() as job')).job;
const repeatId = '40000000-0000-4000-8000-000000000002';
await db.query('select opportunity_finish_research($1,$2,$3::jsonb,$4::jsonb)', [refresh, claimed.lease_token, JSON.stringify([{ ...candidate, evidence_id: repeatId }]), JSON.stringify(artifact(repeatId))]);
assert.equal((await rpc('select count(*)::integer as count from evidence_items where source_id is not null and claim=$1', [candidate.excerpt])).count, 1);
assert.equal((await rpc('select content from research_artifacts where research_job_id=$1', [refresh])).content.claims[0].evidence_ids[0], candidate.evidence_id);
const draftId = (await rpc('select id from research_artifacts where research_job_id=$1', [refresh])).id;
await asUser(owner);
await assert.rejects(db.query('select opportunity_accept_research($1,$2,$3,$4,false)', [draftId, 'why_now', 0, 0]), /confirm/);
await db.query('select opportunity_accept_research($1,$2,$3,$4,true)', [draftId, 'why_now', 0, 0]);
const accepted = (await rpc("select content from brief_sections where workspace_id=$1 and section_key='why_now'", [workspace])).content;
assert.equal(accepted.kind, 'inferred'); assert.deepEqual(accepted.evidence_ids, [candidate.evidence_id]);
await assert.rejects(db.query('select opportunity_accept_research($1,$2,$3,$4,true)', [draftId, 'why_now', 0, 0]), /changed/);
await db.exec('reset role');

await db.query("update research_jobs set status='synthesizing',attempts=max_attempts,lease_expires_at=now()-interval '1 minute' where id=$1", [refresh]);
assert.equal((await rpc('select opportunity_claim_research() as job')).job, null);
assert.equal((await rpc('select status from research_jobs where id=$1', [refresh])).status, 'failed');
// Signed webhook handlers call this service-only, transactional reconciliation.
await db.query('select opportunity_apply_subscription($1,$2,$3,$4,$5,$6,$7)', ['event1', 100, owner, 'customer', 'subscription', 'builder', 'active']);
await asUser(owner);
const workflow = (await command('workflow',{ workspace_id: workspace, name:'Review-required outreach', trigger:{ description:'New qualified lead' }, graph:[{ steps:'Draft a response',human_approval:'Owner approves before sending',outputs:'A draft only' }] })).id;
const dryRun = (await db.query("select opportunity_test_workflow($1,'{\"lead\":\"Example Co\"}'::jsonb) as result",[workflow])).rows[0].result;
assert.equal(dryRun.external_actions_executed,false);
assert.equal(dryRun.steps[0].status,'simulated');
await db.exec('reset role');
await db.query('select opportunity_apply_subscription($1,$2,$3,$4,$5,$6,$7)', ['event2', 101, owner, 'customer', 'subscription', 'builder', 'past_due']);
assert.equal((await rpc('select opportunity_limits(org_id) as limits from opportunity_accounts where user_id=$1', [owner])).limits.active, 15);
await db.query("update opportunity_accounts set billing_grace_ends_at=now()-interval '1 minute' where user_id=$1", [owner]);
assert.equal((await rpc('select opportunity_limits(org_id) as limits from opportunity_accounts where user_id=$1', [owner])).limits.active, 1);
await db.query('select opportunity_apply_subscription($1,$2,$3,$4,$5,$6,$7)', ['event1', 100, owner, 'customer', 'subscription', 'studio', 'active']);
assert.equal((await rpc('select plan_key from opportunity_accounts where user_id=$1', [owner])).plan_key, 'builder');
const lease = (await rpc('select opportunity_claim_billing($1) as token', [owner])).token;
assert(lease); assert.equal((await rpc('select opportunity_claim_billing($1) as token', [owner])).token, null);
await db.query('select opportunity_release_billing($1,$2)', [owner, lease]);
assert((await rpc('select opportunity_claim_billing($1) as token', [owner])).token);
// A business author cannot approve their own package, even as an administrator.
await db.query('insert into platform_admins values($1),($2)', [owner, stranger]);
await asUser(owner);
const disclosures = Object.fromEntries(['included_assets','dependencies','ongoing_costs','tested_evidence','untested_assumptions','licences','limitations','handover'].map(key => [key, 'Explicit reviewed disclosure']));
const listing = (await rpc('select opportunity_admin_command($1,$2::jsonb) as result', ['business', JSON.stringify({ title: 'Reviewed package', slug: 'reviewed-package', disclosures, terms: { scope: 'Defined scope', version: 'v1' } })])).result.id;
await assert.rejects(db.query('select opportunity_admin_command($1,$2::jsonb)', ['publish_business', JSON.stringify({ id: listing, confirmed: true })]), /second administrator/);
await asUser(stranger);
await db.query('select opportunity_admin_command($1,$2::jsonb)', ['publish_business', JSON.stringify({ id: listing, confirmed: true })]);
assert.equal((await rpc('select reviewed_by from business_listings where id=$1', [listing])).reviewed_by, stranger);
// Activation executes against real School columns and keeps historical credit.
await db.exec('reset role');
const schoolOrg = '60000000-0000-4000-8000-000000000001';
await db.query("insert into organizations(id,owner_user_id,name,slug) values($1,$2,'School','startup-school')", [schoolOrg, owner]);
await db.query("insert into cs_categories(organization_id,id,name) values($1,'legacy','Legacy')", [schoolOrg]);
await db.query("insert into cs_mentors(organization_id,id,name) values($1,'legacy','Legacy mentor')", [schoolOrg]);
await db.query("insert into cs_courses(organization_id,id,slug,title,category_id,mentor_id) values($1,'legacy-course','legacy-course','Legacy course','legacy','legacy')", [schoolOrg]);
await db.query("insert into cs_modules(organization_id,id,course_id,title) values($1,'legacy-module','legacy-course','Legacy module')", [schoolOrg]);
await db.query("insert into cs_lessons(organization_id,id,course_id,module_id,title) values($1,'legacy-lesson','legacy-course','legacy-module','Legacy lesson')", [schoolOrg]);
await db.query("insert into cs_lesson_progress(organization_id,user_id,lesson_id,completed_at) values($1,$2,'legacy-lesson',now())", [schoolOrg, owner]);
await db.query('insert into cs_profiles(organization_id,user_id) values($1,$2)', [schoolOrg, owner]);
await asUser(owner);
const preview = (await rpc('select ss_activate_opportunity_curriculum($1,false) as preview', [schoolOrg])).preview;
assert.equal(preview.records[0].action, 'preserve_legacy_progress_for_review');
await db.query('select ss_activate_opportunity_curriculum($1,true)', [schoolOrg]);
await db.query('select ss_activate_opportunity_curriculum($1,true)', [schoolOrg]);
await db.exec('reset role');
assert.equal((await rpc('select count(*)::integer as count from cs_courses where organization_id=$1 and published', [schoolOrg])).count, 12);
assert.equal((await rpc("select count(*)::integer as count from cs_lesson_blocks where organization_id=$1", [schoolOrg])).count, 72);
assert((await rpc("select completed_at from cs_lesson_progress where lesson_id='legacy-lesson'")).completed_at);
assert.equal((await rpc("select count(*)::integer as count from cs_lesson_progress where lesson_id like 'v2-%'")).count, 0);
await asUser(owner);
await assert.rejects(db.query('select opportunity_complete_lesson($1,$2)', ['mvp-delivery', workspace]), /required artifact/);
await db.query('select opportunity_complete_lesson($1,$2)', ['finding-problems', workspace]);
await db.exec('reset role');
assert.equal((await rpc("select count(*)::integer as count from cs_lesson_progress where lesson_id='v2-finding-problems-practice' and completed_at is not null")).count, 1);
console.log('PASS: twelve-module activation, 72 lesson blocks, idempotence, preserved historical progress and artifact-gated completion.');
await asUser(owner);
await db.query('select opportunity_save_notifications(false,true,true,false)');
await db.exec('reset role');
const before = (await rpc("select count(*)::integer as count from opportunity_notifications where user_id=$1 and type='research_completed'", [owner])).count;
await db.query("insert into opportunity_notifications(user_id,type,title) values($1,'research_completed','Optional alert')", [owner]);
assert.equal((await rpc("select count(*)::integer as count from opportunity_notifications where user_id=$1 and type='research_completed'", [owner])).count, before);
await asUser(owner);
await assert.rejects(db.query('select opportunity_track_event($1,$2::jsonb)', ['workspace_created', '{"raw_interview":"private text"}']), /Private/);
await db.query('select opportunity_track_event($1,$2::jsonb)', ['workspace_created', '{"origin":"problem"}']);
await assert.rejects(command('privacy', { request_type: 'delete_workspace', workspace_id: workspace }), /Confirm/);
const deletion = (await command('privacy', { request_type: 'delete_workspace', workspace_id: workspace, confirmed: true })).id;
await asUser(viewer);
await assert.rejects(db.query('select opportunity_delete_requested_workspace($1,true)', [deletion]), /administrator/);
await asUser(stranger);
await db.query('select opportunity_delete_requested_workspace($1,true)', [deletion]);
await db.exec('reset role');
assert.equal((await rpc('select count(*)::integer as count from opportunity_workspaces where id=$1', [workspace])).count, 0);
assert.equal((await rpc('select status from opportunity_privacy_requests where id=$1', [deletion])).status, 'completed');
console.log('PASS: notification preferences, categorical telemetry and requested workspace deletion.');
await db.exec('reset role');
await db.exec(`insert into global_opportunities(slug,title,thesis,customer,primary_industry,status) select 'test-'||n,'Test opportunity '||n,'Investigate coordination','Repair businesses',case when n=26 then 'Specialist' else 'Services' end,'published' from generate_series(1,26) n;
insert into global_opportunities(slug,title,thesis,primary_industry,status) values('private-draft','Hidden draft','Private content','Secret category','draft');`);
await db.exec('set role anon');
const firstPage = (await rpc('select opportunity_search() as result')).result;
const secondPage = (await rpc("select opportunity_search('','','','','browse',1) as result")).result;
assert.equal(firstPage.total, 26); assert.equal(firstPage.items.length, 24); assert.equal(secondPage.items.length, 2);
assert.equal(new Set([...firstPage.items, ...secondPage.items].map(item => item.id)).size, 26);
assert(!firstPage.filters.primary_industry.includes('Secret category'));
assert(!('created_by' in firstPage.items[0]));
assert.equal((await rpc("select opportunity_search('Repair','Specialist') as result")).result.total, 1);
await asUser(owner);
await command('save', { opportunity_id: firstPage.items[0].id });
await command('feedback', { opportunity_id: firstPage.items[0].id, action: 'dismiss' });
assert.equal((await rpc("select opportunity_search('','','','','saved') as result")).result.total, 1);
assert.equal((await rpc("select opportunity_search('','','','','dismissed') as result")).result.total, 1);
assert.equal((await rpc("select opportunity_search('','','','','for_you') as result")).result.total, 25);
await asUser(stranger);
assert.equal((await rpc("select opportunity_search('','','','','saved') as result")).result.total, 0);
console.log('PASS: paginated search, whole-library filters, public draft isolation and private saved/dismissed feeds.');
const accountDeletion = (await command('privacy',{ request_type:'delete_account',confirmed:true })).id;
await db.exec("reset role; set role service_role; select set_config('request.jwt.claim.role','service_role',false);");
const preparedDeletion = (await db.query('select opportunity_prepare_account_deletion($1,true,true) as result',[accountDeletion])).rows[0].result;
assert.equal(preparedDeletion.ready,true);
await db.exec('reset role');
assert.equal((await rpc('select user_id,status from opportunity_privacy_requests where id=$1',[accountDeletion])).user_id,null);
console.log('PASS: confirmed account deletion prepares an anonymous receipt after product-data cleanup.');
await db.close();
console.log('PASS: migrations, limits, isolation, provenance, concurrency, experiments, immutable decisions, research budgets and deduplication, exhausted leases, billing grace and locks, two-person publication.');
