/** B §9.2: module names, outcomes and required artifacts are source requirements.
 * Explanations and fictional examples below are teaching content, not market evidence.
 * This file has no UI dependencies and is shared by the app and Startup School.
 */
export type SchoolModule = { id: string; title: string; outcome: string; artifact: string; target: string; kind: string; section?: string; lesson: string; example: string; exercise: string; template: string[] };
export const SCHOOL_MODULES: SchoolModule[] = [
    {
        id: 'opportunity-thinking', title: 'Opportunity Thinking', outcome: 'Understand the difference between an idea, problem, trend and opportunity.', artifact: 'Opportunity thesis', target: 'brief', kind: 'brief', section: 'thesis',
        lesson: 'An idea proposes something to build. A problem describes an outcome someone struggles to achieve. A trend describes a change. An opportunity connects a specific customer and problem to a plausible way of creating value. None of these establishes demand on its own.\n\nStart with the customer and their situation. Describe the job they need to accomplish, what they do today and why an alternative might matter. Keep the proposed solution provisional: several different businesses could address the same problem.\n\nWrite a thesis that another person can challenge. Separate what you observed from what you infer and what remains unknown. A useful thesis makes your next investigation obvious; it does not make the opportunity sound certain.',
        example: 'Fictional service-business example: a founder proposes an AI scheduling app. Their opportunity thesis instead asks whether independent repair businesses lose work while coordinating appointments. The founder has not yet observed the workflow or established willingness to pay. Both remain unknown.',
        exercise: 'Write a two-to-four-sentence thesis naming the customer, problem, current alternative and why the opportunity may matter. Label it as inferred until you can link real evidence.',
        template: ['Customer and context', 'Problem or desired outcome', 'Current alternative', 'Why this may matter', 'What remains unknown'],
    },
    {
        id: 'finding-problems', title: 'Finding Problems Worth Investigating', outcome: 'Observe jobs, pain, friction and workarounds.', artifact: 'Problem evidence log', target: 'evidence', kind: 'evidence',
        lesson: 'Look for work people already do, delays they accept and workarounds they maintain. A complaint is a starting signal, not proof that a person will change behaviour or buy a solution. Observe the work in its context wherever possible.\n\nAsk about a recent specific incident: what triggered it, what happened next, what tools were used and what the consequences were. Avoid suggesting your product or asking whether someone likes your idea. Record the customer’s account separately from your explanation of it.\n\nA useful evidence record includes the observation, the source or interview reference, the date, the market and the limits of what it tells you. Ask permission before recording personal information. An AI-generated customer story is a hypothesis, never an interview.',
        example: 'Fictional local-business example: an operator watches a shopkeeper reconcile orders against messages. The observation concerns that shopkeeper on that day. It does not establish that every shopkeeper has the same problem.',
        exercise: 'Record one real observation or sourced problem signal. Include its date and context, then state what it does and does not support.',
        template: ['Observed job', 'Friction or workaround', 'Who and where', 'Source and date', 'Interpretation', 'Limits of the evidence'],
    },
    {
        id: 'customers-context', title: 'Customers & Context', outcome: 'Define who experiences the problem and when.', artifact: 'ICP + context map', target: 'market', kind: 'artifact', section: 'icp',
        lesson: 'A customer segment is useful when its members share a relevant job, context or constraint. A broad label such as small business hides differences in buying behaviour, budget and access. Narrow the segment enough to identify people you can actually speak with.\n\nThe user, buyer and approver can be different people. Map who experiences the problem, who pays, who can block adoption and what event triggers a search for an alternative. Do not infer budget merely from job title or company size.\n\nDescribe one primary segment and record adjacent segments separately. Revisit your choice when observations contradict it. Your profile is a working hypothesis, not a demographic persona invented to fill a template.',
        example: 'Fictional SaaS example: an operations employee uses a reporting tool, a department head approves it and finance pays. A problem experienced by the user may not be important enough for the buyer to fund.',
        exercise: 'Create an ideal customer profile with the user, buyer, job, context, trigger and route to a real conversation. Mark unsupported attributes as assumptions.',
        template: ['Primary segment', 'User', 'Buyer and approver', 'Job and context', 'Trigger', 'Reachable channel', 'Evidence and unknowns'],
    },
    {
        id: 'market-alternatives', title: 'Market & Alternatives', outcome: 'Understand how value is currently delivered.', artifact: 'Alternative/competitor map', target: 'market', kind: 'artifact', section: 'alternatives',
        lesson: 'Competition includes direct products, services, internal processes, spreadsheets and doing nothing. Begin with how the customer handles the job today. An alternative can be inconvenient and still be good enough to prevent switching.\n\nMap the value chain: who supplies inputs, who delivers the outcome, who controls access and who captures payment. Describe alternatives using verifiable sources. A model’s suggestion that a competitor exists is not sufficient evidence.\n\nCompare outcomes and constraints rather than building a feature-count contest. Keep observed facts, your interpretation of a gap and the switching hypothesis separate. Record source dates because product capabilities and prices change.',
        example: 'Fictional ecommerce example: a seller handles returns through email and a spreadsheet. Their alternative is a familiar process with no new subscription. A new returns product must justify the disruption of switching.',
        exercise: 'Map at least the current workaround and one direct or indirect alternative. Link sources for factual statements, and name what you still need to ask customers.',
        template: ['Current workaround', 'Direct alternatives', 'Indirect alternatives', 'Value chain', 'Switching cost', 'Sources and dates', 'Unanswered questions'],
    },
    {
        id: 'why-now', title: 'Why Now?', outcome: 'Identify enabling changes and timing.', artifact: 'Why-now thesis', target: 'brief', kind: 'brief', section: 'why_now',
        lesson: 'A timing thesis explains what changed and how that change affects a customer’s options. Changes can involve technology, regulation, behaviour, economics or distribution. A fashionable topic is not enough: describe the mechanism connecting the change to the problem.\n\nRecord when the change occurred, its geography and the source. Separate the existence of a change from your belief about its commercial effect. A cheaper technical capability does not establish that customers need or want the resulting product.\n\nAsk what would make the timing thesis wrong. The customer might not be ready, adoption might be costly or the change may already be reflected in existing alternatives. Use those uncertainties to guide research.',
        example: 'Fictional AI-enabled-business example: a new document-processing capability might reduce a manual step. The team still needs to test accuracy, review effort and whether the affected customer sees enough value to change.',
        exercise: 'Write a why-now claim with a dated source where available. Explain the causal link to the customer problem and identify one reason that link may fail.',
        template: ['Change', 'Date and geography', 'Source', 'Effect on the customer', 'Commercial hypothesis', 'What would contradict it'],
    },
    {
        id: 'critical-assumptions', title: 'Critical Assumptions', outcome: 'State what must be true.', artifact: 'Assumption map', target: 'assumptions', kind: 'assumption',
        lesson: 'An assumption is a statement that must hold for your opportunity to work. It should be specific enough to support or contradict. “Customers will love it” is hard to test; a statement about a particular customer, behaviour and situation is more useful.\n\nConsider problem, customer, value, behaviour, payment, distribution, solution, operations and regulatory assumptions. Importance asks how much the opportunity depends on a claim. Uncertainty asks how little you currently know about it. Prioritise high-importance, high-uncertainty claims.\n\nThese ratings order learning; they do not predict business success. Evidence can support, contradict or provide context. Preserve disagreement rather than averaging it into a reassuring score.',
        example: 'Fictional service example: the team believes buyers will switch from an existing supplier. This assumption could invalidate the offer even if delivery is technically easy. It deserves testing before adding more features.',
        exercise: 'Add your critical assumptions and rate their importance and uncertainty. Choose the one whose failure would most change your decision.',
        template: ['Must-be-true statement', 'Class', 'Importance', 'Uncertainty', 'Existing evidence', 'Cheapest useful test'],
    },
    {
        id: 'validation', title: 'Validation', outcome: 'Design evidence-generating tests.', artifact: 'Experiment plan', target: 'experiments', kind: 'experiment',
        lesson: 'Validation is an investigation, not a one-time verdict. Choose a test that can change your view of a critical assumption. Interviews, prototypes, concierge delivery, landing pages, waitlists and paid pilots answer different questions.\n\nDefine the hypothesis, method and success criteria before running the test. State who will participate, what action or observation matters and when you will review the result. Choose the smallest credible test rather than the most impressive prototype.\n\nRecord observations separately from interpretation. An inconclusive result is useful when it shows what your test could not establish. Avoid changing the success threshold after seeing the result. Do not treat stated enthusiasm as equivalent to usage or payment.',
        example: 'Fictional local-service example: a concierge test delivers the proposed outcome manually before software exists. It can reveal whether the outcome matters, while leaving automation cost and scalability unproven.',
        exercise: 'Create a draft experiment linked to an assumption, with a method, predetermined success criteria and a review date. Run it only after checking consent and any real-world obligations.',
        template: ['Linked assumption', 'Hypothesis', 'Participants', 'Method', 'Success criteria', 'Review date', 'Learning'],
    },
    {
        id: 'value-proposition', title: 'Value Proposition', outcome: 'Translate learning into a compelling outcome.', artifact: 'Value proposition', target: 'shape', kind: 'artifact', section: 'value_proposition',
        lesson: 'A value proposition describes a meaningful customer outcome and why this offer may deliver it better than current alternatives. Begin with what you have learned about the customer’s job and context. A technology label is not itself a customer benefit.\n\nConnect the desired outcome to concrete deliverables and a reason to believe. Be explicit about constraints: what the offer does not promise, what the customer must contribute and which parts remain hypotheses.\n\nUse customer language from actual observations where available. Test whether the promise is understood and whether it motivates a relevant action. Revise the promise when the evidence changes instead of making it broader.',
        example: 'Fictional SaaS example: “AI-powered reports” becomes a proposed outcome of preparing a reviewable report from existing records. The accuracy and time benefit remain assumptions until tested with real users.',
        exercise: 'Save a value proposition naming the customer, desired outcome, alternative, distinction and evidence. Include the next claim to test.',
        template: ['Customer', 'Desired outcome', 'Current alternative', 'Differentiated promise', 'Reason to believe', 'Constraints', 'Next test'],
    },
    {
        id: 'business-model', title: 'Business Model', outcome: 'Define who pays and how value is captured.', artifact: 'Business model', target: 'shape', kind: 'artifact', section: 'business_model',
        lesson: 'A business model connects the customer outcome to payment and delivery. Identify who pays, what they pay for, how often, how the offer reaches them and what it costs to deliver. A price without a payer and buying situation is an unsupported number.\n\nSeparate revenue hypotheses from observed transactions. Record direct delivery costs, acquisition effort, recurring infrastructure and human work. In an AI-enabled service, include review, exception handling and provider usage in the delivery model.\n\nExplore how the model changes when a key assumption is wrong. A useful first model shows which inputs need evidence; it does not turn a spreadsheet into a forecast you can trust.',
        example: 'Fictional ecommerce example: a subscription may create recurring revenue, but replenishment frequency, returns and repeat demand still need testing. The team records those as assumptions rather than filling a growth forecast with unsupported rates.',
        exercise: 'Save a versioned model showing payer, pricing mechanism, revenue frequency, costs, delivery and the unit-economics assumptions to test next.',
        template: ['Payer', 'What is purchased', 'Pricing hypothesis', 'Revenue frequency', 'Cost drivers', 'Delivery model', 'Unit economics assumptions'],
    },
    {
        id: 'mvp-delivery', title: 'MVP & Delivery', outcome: 'Design the smallest credible delivery system.', artifact: 'MVP scope', target: 'shape', kind: 'artifact', section: 'mvp',
        lesson: 'An MVP is a boundary around the smallest credible way to deliver and test the proposed value. It is not simply a large product with fewer features. Decide which uncertainty the first version must resolve.\n\nMap the customer journey to the first useful outcome. Identify what must work, what can be delivered manually and what can wait. Include support, failures and human review where they affect that outcome.\n\nFor an automated workflow, define inputs, permitted tools, outputs, logs and approval points. Planning a workflow does not authorize it to send messages, publish content or spend money. Test with controlled inputs before requesting production activation.',
        example: 'Fictional AI-enabled-service example: a founder reviews every generated draft before delivery. That manual review is part of the MVP, allowing the team to learn about quality without claiming autonomous reliability.',
        exercise: 'Write the MVP scope with the value to test, necessary work, manual steps, exclusions and acceptance criteria. Make external-action approvals explicit.',
        template: ['Value to test', 'Core journey', 'Must exist', 'Manual steps', 'Not yet', 'Failure handling', 'Acceptance criteria'],
    },
    {
        id: 'go-to-market', title: 'Go-to-Market', outcome: 'Choose channels and sales motion.', artifact: 'Launch plan', target: 'launch', kind: 'artifact', section: 'launch_plan',
        lesson: 'A launch is a plan to reach a defined customer, help them experience value and learn from what happens. Start with a target cohort and an objective. Choose channels because you have a plausible route to that customer, not because every business is expected to use them.\n\nConnect the offer, message, sales conversation, onboarding and measurement. Define the action that represents activation and the follow-up that reveals continued value. Keep channel performance and revenue expectations labelled as hypotheses until observed.\n\nPlan the review before the announcement. Record what you will measure, who owns it and which result would change your approach. Drafting a campaign is separate from authorizing publication, outreach or spending.',
        example: 'Fictional service-business example: a founder plans a small set of consent-based discovery conversations through an existing professional community. The plan specifies the customer, offer, desired next action and learning review without assuming a conversion rate.',
        exercise: 'Create a launch plan containing objective, target cohort, channels, message, activation, measurement and a post-launch learning review.',
        template: ['Objective', 'Target cohort', 'Offer', 'Channel hypothesis', 'Sales motion', 'Onboarding', 'Measurement', 'Review and next decision'],
    },
    {
        id: 'decision-iteration', title: 'Decision & Iteration', outcome: 'Proceed, revise, pause or stop based on evidence.', artifact: 'Decision review', target: 'decisions', kind: 'decision',
        lesson: 'A decision review connects what you learned to what you will do next. It does not require the system to declare the opportunity good or bad. Review the original thesis, new evidence, supported and contradicted assumptions, and unresolved questions.\n\nProceed means continuing with a stated next objective. Revise means changing the thesis or approach. Pause preserves the work while priorities or evidence develop. Stop records why further effort is not justified now. These are decisions under uncertainty, not predictions.\n\nWrite a rationale that a future reader can understand. Preserve the evidence available at that moment. If later evidence changes your view, create another review instead of rewriting the earlier decision. The venture loop can move backward or sideways as learning changes the work.',
        example: 'Fictional local-business example: interviews support the problem, but a pilot has not shown willingness to pay. The founder pauses building, records that uncertainty and identifies a smaller payment test. The problem evidence remains useful even though the decision changes.',
        exercise: 'Finalise a review stating what changed, what remains unknown, your decision and the next learning action. Confirm the snapshot yourself.',
        template: ['What was learned', 'Supported assumptions', 'Contradictions', 'Open questions', 'Proceed / revise / pause / stop', 'Rationale', 'Next action'],
    },
];
export const schoolCourseId = (id: string) => `v2-${id}`;
export const schoolLessonId = (id: string) => `v2-${id}-practice`;
