/**
 * GENERATED by scripts/build-icon-shim.mjs — do not edit by hand.
 *
 * Vite aliases `@primer/octicons-react` here, so every icon in the app is drawn
 * from the Untitled UI set (MIT) while the content modules keep the names they
 * were written with. The wrapper preserves the Octicon call signature.
 */
import { forwardRef, type ComponentType, type SVGProps } from 'react'
import {
  Activity,
  AlertCircle,
  AlertTriangle,
  Announcement02,
  Archive,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Atom01,
  BankNote01,
  BarChart09,
  BarChart10,
  BarChartSquare02,
  Beaker02,
  Bell01,
  BookOpen01,
  Bookmark,
  Briefcase01,
  Building02,
  Calendar,
  Camera01,
  Check,
  CheckCircle,
  CheckCircleBroken,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleCut,
  Clock,
  ClockRewind,
  ClockStopwatch,
  Code01,
  Coins03,
  Copy01,
  CpuChip01,
  CpuChip02,
  CreditCard02,
  CurrencyDollarCircle,
  Database01,
  Dataflow03,
  Dataflow04,
  DotsHorizontal,
  Download01,
  Edit05,
  Expand01,
  Eye,
  EyeOff,
  FaceSmile,
  File02,
  FileCheck02,
  FileSearch02,
  FilterFunnel01,
  FilterLines,
  Flag01,
  Folder,
  FolderCheck,
  GitBranch01,
  GitBranch02,
  GitMerge,
  GitPullRequest,
  Globe02,
  GraduationHat02,
  HardDrive,
  Heart,
  HelpCircle,
  Home01,
  Hourglass03,
  Image01,
  Inbox01,
  InfoCircle,
  Key01,
  LayersThree01,
  Lightbulb02,
  Link01,
  LinkExternal02,
  Lock01,
  LogOut01,
  Mail01,
  MarkerPin01,
  Menu02,
  MessageChatCircle,
  MessageTextSquare01,
  Microphone01,
  Minus,
  Monitor04,
  Moon01,
  Package,
  PackageCheck,
  Phone01,
  PieChart03,
  PlayCircle,
  Plus,
  PuzzlePiece01,
  RefreshCw05,
  Rocket02,
  Route,
  Scales02,
  SearchLg,
  Send01,
  Server01,
  Settings01,
  Shield01,
  ShieldOff,
  ShieldTick,
  SkipForward,
  Sliders04,
  Speedometer03,
  Stars01,
  Stars02,
  StopCircle,
  Sun,
  SwitchHorizontal01,
  Table,
  Tag01,
  Target04,
  Telescope,
  Terminal,
  ThumbsUp,
  Trash01,
  Trophy01,
  UploadCloud01,
  User01,
  Users01,
  VideoRecorder,
  VolumeMax,
  Wallet02,
  XCircle,
  XClose,
  Zap,
} from '@untitledui/icons'

type Base = ComponentType<SVGProps<SVGSVGElement>>

export interface IconProps extends Omit<SVGProps<SVGSVGElement>, 'ref'> {
  /** Octicon-compatible: pixels, or one of its named sizes. */
  size?: number | 'small' | 'medium' | 'large'
  /** Accepted for source compatibility; the icons align on the text baseline already. */
  verticalAlign?: string
}

const NAMED: Record<string, number> = { small: 16, medium: 20, large: 24 }

function icon(Base: Base, name: string) {
  const Component = forwardRef<SVGSVGElement, IconProps>(function Icon(props, ref) {
    const { size = 16, verticalAlign: _ignored, ...rest } = props
    const px = typeof size === 'number' ? size : (NAMED[size] ?? 16)
    // Untitled UI draws on a 24px grid; thicken the stroke a little at small sizes.
    const strokeWidth = px <= 16 ? 2 : px <= 20 ? 1.9 : 1.75
    return (
      <Base
        ref={ref}
        width={px}
        height={px}
        strokeWidth={strokeWidth}
        aria-hidden={props['aria-label'] ? undefined : true}
        focusable="false"
        {...rest}
      />
    )
  })
  Component.displayName = name
  return Component
}

export const AccessibilityIcon = /* Activity */ icon(Activity, 'AccessibilityIcon')
export const AgentIcon = /* Stars02 */ icon(Stars02, 'AgentIcon')
export const AiModelIcon = /* CpuChip01 */ icon(CpuChip01, 'AiModelIcon')
export const AlertIcon = /* AlertTriangle */ icon(AlertTriangle, 'AlertIcon')
export const ArchiveIcon = /* Archive */ icon(Archive, 'ArchiveIcon')
export const ArrowLeftIcon = /* ArrowLeft */ icon(ArrowLeft, 'ArrowLeftIcon')
export const ArrowRightIcon = /* ArrowRight */ icon(ArrowRight, 'ArrowRightIcon')
export const ArrowUpRightIcon = /* ArrowUpRight */ icon(ArrowUpRight, 'ArrowUpRightIcon')
export const AtomIcon = /* Atom01 */ icon(Atom01, 'AtomIcon')
export const BankIcon = /* BankNote01 */ icon(BankNote01, 'BankIcon')
export const BeakerIcon = /* Beaker02 */ icon(Beaker02, 'BeakerIcon')
export const BellIcon = /* Bell01 */ icon(Bell01, 'BellIcon')
export const BookIcon = /* BookOpen01 */ icon(BookOpen01, 'BookIcon')
export const BookmarkIcon = /* Bookmark */ icon(Bookmark, 'BookmarkIcon')
export const BriefcaseIcon = /* Briefcase01 */ icon(Briefcase01, 'BriefcaseIcon')
export const BroadcastIcon = /* Announcement02 */ icon(Announcement02, 'BroadcastIcon')
export const CacheIcon = /* HardDrive */ icon(HardDrive, 'CacheIcon')
export const CalendarIcon = /* Calendar */ icon(Calendar, 'CalendarIcon')
export const CheckCircleFillIcon = /* CheckCircle */ icon(CheckCircle, 'CheckCircleFillIcon')
export const CheckCircleIcon = /* CheckCircleBroken */ icon(CheckCircleBroken, 'CheckCircleIcon')
export const CheckIcon = /* Check */ icon(Check, 'CheckIcon')
export const ChecklistIcon = /* FileCheck02 */ icon(FileCheck02, 'ChecklistIcon')
export const ChevronDownIcon = /* ChevronDown */ icon(ChevronDown, 'ChevronDownIcon')
export const ChevronLeftIcon = /* ChevronLeft */ icon(ChevronLeft, 'ChevronLeftIcon')
export const ChevronRightIcon = /* ChevronRight */ icon(ChevronRight, 'ChevronRightIcon')
export const CircuitBoardIcon = /* CpuChip02 */ icon(CpuChip02, 'CircuitBoardIcon')
export const ClockIcon = /* Clock */ icon(Clock, 'ClockIcon')
export const CodeIcon = /* Code01 */ icon(Code01, 'CodeIcon')
export const CoinsIcon = /* Coins03 */ icon(Coins03, 'CoinsIcon')
export const CommentDiscussionIcon = /* MessageChatCircle */ icon(MessageChatCircle, 'CommentDiscussionIcon')
export const ContainerIcon = /* Package */ icon(Package, 'ContainerIcon')
export const CopyIcon = /* Copy01 */ icon(Copy01, 'CopyIcon')
export const CpuIcon = /* CpuChip01 */ icon(CpuChip01, 'CpuIcon')
export const CreditCardIcon = /* CreditCard02 */ icon(CreditCard02, 'CreditCardIcon')
export const DashIcon = /* Minus */ icon(Minus, 'DashIcon')
export const DatabaseIcon = /* Database01 */ icon(Database01, 'DatabaseIcon')
export const DependabotIcon = /* Stars02 */ icon(Stars02, 'DependabotIcon')
export const DeviceCameraIcon = /* Camera01 */ icon(Camera01, 'DeviceCameraIcon')
export const DeviceCameraVideoIcon = /* VideoRecorder */ icon(VideoRecorder, 'DeviceCameraVideoIcon')
export const DeviceDesktopIcon = /* Monitor04 */ icon(Monitor04, 'DeviceDesktopIcon')
export const DeviceMobileIcon = /* Phone01 */ icon(Phone01, 'DeviceMobileIcon')
export const DotsIcon = /* DotsHorizontal */ icon(DotsHorizontal, 'DotsIcon')
export const DownloadIcon = /* Download01 */ icon(Download01, 'DownloadIcon')
export const EditIcon = /* Edit05 */ icon(Edit05, 'EditIcon')
export const EyeClosedIcon = /* EyeOff */ icon(EyeOff, 'EyeClosedIcon')
export const EyeIcon = /* Eye */ icon(Eye, 'EyeIcon')
export const FileBadgeIcon = /* FileCheck02 */ icon(FileCheck02, 'FileBadgeIcon')
export const FileIcon = /* File02 */ icon(File02, 'FileIcon')
export const FileMediaIcon = /* Image01 */ icon(Image01, 'FileMediaIcon')
export const FilterIcon = /* FilterFunnel01 */ icon(FilterFunnel01, 'FilterIcon')
export const FilterRemoveIcon = /* FilterLines */ icon(FilterLines, 'FilterRemoveIcon')
export const FlameIcon = /* Zap */ icon(Zap, 'FlameIcon')
export const FlowchartIcon = /* Dataflow04 */ icon(Dataflow04, 'FlowchartIcon')
export const GearIcon = /* Settings01 */ icon(Settings01, 'GearIcon')
export const GitBranchIcon = /* GitBranch01 */ icon(GitBranch01, 'GitBranchIcon')
export const GitCompareIcon = /* SwitchHorizontal01 */ icon(SwitchHorizontal01, 'GitCompareIcon')
export const GlobeIcon = /* Globe02 */ icon(Globe02, 'GlobeIcon')
export const GoalIcon = /* Target04 */ icon(Target04, 'GoalIcon')
export const GraphIcon = /* BarChartSquare02 */ icon(BarChartSquare02, 'GraphIcon')
export const HelpIcon = /* HelpCircle */ icon(HelpCircle, 'HelpIcon')
export const HeartIcon = /* Heart */ icon(Heart, 'HeartIcon')
export const HistoryIcon = /* ClockRewind */ icon(ClockRewind, 'HistoryIcon')
export const HomeIcon = /* Home01 */ icon(Home01, 'HomeIcon')
export const HourglassIcon = /* Hourglass03 */ icon(Hourglass03, 'HourglassIcon')
export const HubotIcon = /* Stars02 */ icon(Stars02, 'HubotIcon')
export const ImageIcon = /* Image01 */ icon(Image01, 'ImageIcon')
export const InboxIcon = /* Inbox01 */ icon(Inbox01, 'InboxIcon')
export const InfoIcon = /* InfoCircle */ icon(InfoCircle, 'InfoIcon')
export const IssueOpenedIcon = /* AlertCircle */ icon(AlertCircle, 'IssueOpenedIcon')
export const LawIcon = /* Scales02 */ icon(Scales02, 'LawIcon')
export const LightBulbIcon = /* Lightbulb02 */ icon(Lightbulb02, 'LightBulbIcon')
export const LinkExternalIcon = /* LinkExternal02 */ icon(LinkExternal02, 'LinkExternalIcon')
export const LinkIcon = /* Link01 */ icon(Link01, 'LinkIcon')
export const LocationIcon = /* MarkerPin01 */ icon(MarkerPin01, 'LocationIcon')
export const LockIcon = /* Lock01 */ icon(Lock01, 'LockIcon')
export const MailIcon = /* Mail01 */ icon(Mail01, 'MailIcon')
export const MarkGithubIcon = /* GitBranch01 */ icon(GitBranch01, 'MarkGithubIcon')
export const MegaphoneIcon = /* Announcement02 */ icon(Announcement02, 'MegaphoneIcon')
export const MeterIcon = /* Speedometer03 */ icon(Speedometer03, 'MeterIcon')
export const MicrophoneIcon = /* Microphone01 */ icon(Microphone01, 'MicrophoneIcon')
export const MilestoneIcon = /* Flag01 */ icon(Flag01, 'MilestoneIcon')
export const MoonIcon = /* Moon01 */ icon(Moon01, 'MoonIcon')
export const MortarBoardIcon = /* GraduationHat02 */ icon(GraduationHat02, 'MortarBoardIcon')
export const NoteIcon = /* MessageTextSquare01 */ icon(MessageTextSquare01, 'NoteIcon')
export const NumberIcon = /* CurrencyDollarCircle */ icon(CurrencyDollarCircle, 'NumberIcon')
export const OrganizationIcon = /* Building02 */ icon(Building02, 'OrganizationIcon')
export const PackageDependenciesIcon = /* PackageCheck */ icon(PackageCheck, 'PackageDependenciesIcon')
export const PackageIcon = /* Package */ icon(Package, 'PackageIcon')
export const PaperAirplaneIcon = /* Send01 */ icon(Send01, 'PaperAirplaneIcon')
export const PeopleIcon = /* Users01 */ icon(Users01, 'PeopleIcon')
export const PersonIcon = /* User01 */ icon(User01, 'PersonIcon')
export const PlayCircleIcon = /* PlayCircle */ icon(PlayCircle, 'PlayCircleIcon')
export const PlayIcon = /* PlayCircle */ icon(PlayCircle, 'PlayIcon')
export const PlugIcon = /* PuzzlePiece01 */ icon(PuzzlePiece01, 'PlugIcon')
export const PlusIcon = /* Plus */ icon(Plus, 'PlusIcon')
export const ProjectIcon = /* PieChart03 */ icon(PieChart03, 'ProjectIcon')
export const PulseIcon = /* Activity */ icon(Activity, 'PulseIcon')
export const ReportIcon = /* FileSearch02 */ icon(FileSearch02, 'ReportIcon')
export const RocketIcon = /* Rocket02 */ icon(Rocket02, 'RocketIcon')
export const ScreenFullIcon = /* Expand01 */ icon(Expand01, 'ScreenFullIcon')
export const SearchIcon = /* SearchLg */ icon(SearchLg, 'SearchIcon')
export const ServerIcon = /* Server01 */ icon(Server01, 'ServerIcon')
export const ShieldCheckIcon = /* ShieldTick */ icon(ShieldTick, 'ShieldCheckIcon')
export const ShieldIcon = /* Shield01 */ icon(Shield01, 'ShieldIcon')
export const ShieldLockIcon = /* Key01 */ icon(Key01, 'ShieldLockIcon')
export const ShieldSlashIcon = /* ShieldOff */ icon(ShieldOff, 'ShieldSlashIcon')
export const SignOutIcon = /* LogOut01 */ icon(LogOut01, 'SignOutIcon')
export const SlidersIcon = /* Sliders04 */ icon(Sliders04, 'SlidersIcon')
export const SmileyIcon = /* FaceSmile */ icon(FaceSmile, 'SmileyIcon')
export const SortDescIcon = /* BarChart10 */ icon(BarChart10, 'SortDescIcon')
export const SparkleFillIcon = /* Stars02 */ icon(Stars02, 'SparkleFillIcon')
export const SparkleIcon = /* Stars01 */ icon(Stars01, 'SparkleIcon')
export const StackIcon = /* LayersThree01 */ icon(LayersThree01, 'StackIcon')
export const StopIcon = /* StopCircle */ icon(StopCircle, 'StopIcon')
export const StopwatchIcon = /* ClockStopwatch */ icon(ClockStopwatch, 'StopwatchIcon')
export const SunIcon = /* Sun */ icon(Sun, 'SunIcon')
export const SyncIcon = /* RefreshCw05 */ icon(RefreshCw05, 'SyncIcon')
export const TableIcon = /* Table */ icon(Table, 'TableIcon')
export const TagIcon = /* Tag01 */ icon(Tag01, 'TagIcon')
export const TelescopeIcon = /* Telescope */ icon(Telescope, 'TelescopeIcon')
export const TerminalIcon = /* Terminal */ icon(Terminal, 'TerminalIcon')
export const ThreeBarsIcon = /* Menu02 */ icon(Menu02, 'ThreeBarsIcon')
export const ThumbsupIcon = /* ThumbsUp */ icon(ThumbsUp, 'ThumbsupIcon')
export const TrashIcon = /* Trash01 */ icon(Trash01, 'TrashIcon')
export const TrophyIcon = /* Trophy01 */ icon(Trophy01, 'TrophyIcon')
export const UndoIcon = /* RefreshCw05 */ icon(RefreshCw05, 'UndoIcon')
export const UnmuteIcon = /* VolumeMax */ icon(VolumeMax, 'UnmuteIcon')
export const UploadIcon = /* UploadCloud01 */ icon(UploadCloud01, 'UploadIcon')
export const VerifiedIcon = /* ShieldTick */ icon(ShieldTick, 'VerifiedIcon')
export const VersionsIcon = /* GitBranch01 */ icon(GitBranch01, 'VersionsIcon')
export const WalletIcon = /* Wallet02 */ icon(Wallet02, 'WalletIcon')
export const WebhookIcon = /* Dataflow03 */ icon(Dataflow03, 'WebhookIcon')
export const WorkflowIcon = /* Route */ icon(Route, 'WorkflowIcon')
export const XCircleIcon = /* XCircle */ icon(XCircle, 'XCircleIcon')
export const XIcon = /* XClose */ icon(XClose, 'XIcon')
export const ZapIcon = /* Zap */ icon(Zap, 'ZapIcon')
export const AlertFillIcon = /* AlertCircle */ icon(AlertCircle, 'AlertFillIcon')
export const FileDirectoryFillIcon = /* Folder */ icon(Folder, 'FileDirectoryFillIcon')
export const FileDirectoryOpenFillIcon = /* FolderCheck */ icon(FolderCheck, 'FileDirectoryOpenFillIcon')
export const GitMergeIcon = /* GitMerge */ icon(GitMerge, 'GitMergeIcon')
export const GitMergeQueueIcon = /* GitBranch02 */ icon(GitBranch02, 'GitMergeQueueIcon')
export const GitPullRequestIcon = /* GitPullRequest */ icon(GitPullRequest, 'GitPullRequestIcon')
export const GitPullRequestClosedIcon = /* GitPullRequest */ icon(GitPullRequest, 'GitPullRequestClosedIcon')
export const GitPullRequestDraftIcon = /* GitPullRequest */ icon(GitPullRequest, 'GitPullRequestDraftIcon')
export const IssueClosedIcon = /* CheckCircle */ icon(CheckCircle, 'IssueClosedIcon')
export const IssueDraftIcon = /* CircleCut */ icon(CircleCut, 'IssueDraftIcon')
export const KebabHorizontalIcon = /* DotsHorizontal */ icon(DotsHorizontal, 'KebabHorizontalIcon')
export const ShieldXIcon = /* ShieldOff */ icon(ShieldOff, 'ShieldXIcon')
export const SkipIcon = /* SkipForward */ icon(SkipForward, 'SkipIcon')
export const SortAscIcon = /* BarChart09 */ icon(BarChart09, 'SortAscIcon')
export const TriangleDownIcon = /* ChevronDown */ icon(ChevronDown, 'TriangleDownIcon')
export const XCircleFillIcon = /* XCircle */ icon(XCircle, 'XCircleFillIcon')
