/**
 * Generated by scripts/build-product-index.mjs — do not edit by hand.
 * The commercial name and one-line pitch for each product that has a written
 * positioning module, so the hub can list them without importing all of them.
 */
import type { Slug } from './types'

export interface ProductBrief {
  name: string
  tagline?: string
  category?: string
}

export const PRODUCT_INDEX: Partial<Record<Slug, ProductBrief>> = {
  'clv': { name: 'Counterlift', tagline: 'Retention budget graded on incremental margin, against a holdout that is never switched off', category: 'Incremental retention platform' },
  'emotion': { name: 'Assentia', tagline: 'Second-by-second audience response to creative, measured only on people who said yes', category: 'Consented audience-response measurement for creative testing' },
  'ergonomics': { name: 'Plumbline', tagline: 'Ergonomic risk scored continuously, and honest about when it cannot be', category: 'Industrial ergonomics and MSD risk intelligence' },
  'people': { name: 'Qini', tagline: 'The incremental effect of every retention decision, and the evidence a regulator will ask for, from the same model', category: 'Causal people analytics and workforce-compliance platform' },
  'retail': { name: 'Facingly', tagline: 'On-shelf availability from the cameras a store already owns', category: 'Shelf intelligence and on-shelf availability platform' },
  'reviews': { name: 'Taxon', tagline: 'Read every review, not a 2% sample — for less than the sample costs', category: 'Voice-of-customer intelligence' },
}

export const productBrief = (slug: Slug): ProductBrief | undefined => PRODUCT_INDEX[slug]
