// AUTO-GENERATED by scripts/gen-section-registry.mjs — do not edit by hand.
// 227 sections registered render-as-is. Editable fields are layered
// on in manifests.tsx (which overrides these by `source`).
// Static imports (not lazy import()) on purpose: 200+ dynamic-import chunks OOM
// Vercel's build, and per-chunk grouping broke React's JSX runtime. The registry
// only loads in lazy routes (Studio/preview/published), never the marketing entry.
import type { ComponentType } from "react";
import type { SectionManifest } from "./types";

import C0 from "@/shared/sections/about-1/Section1";
import C1 from "@/shared/sections/about-1/Section2";
import C2 from "@/shared/sections/about-1/Section3";
import C3 from "@/shared/sections/about-1/Section4";
import C4 from "@/shared/sections/about-1/Section5";
import C5 from "@/shared/sections/about-2/Section1";
import C6 from "@/shared/sections/about-2/Section2";
import C7 from "@/shared/sections/about-2/Section3";
import C8 from "@/shared/sections/about-2/Section4";
import C9 from "@/shared/sections/about-2/Section5";
import C10 from "@/shared/sections/about-3/Section1";
import C11 from "@/shared/sections/about-3/Section2";
import C12 from "@/shared/sections/about-3/Section3";
import C13 from "@/shared/sections/about-3/Section4";
import C14 from "@/shared/sections/about-3/Section5";
import C15 from "@/shared/sections/about-3/Section6";
import C16 from "@/shared/sections/about-3/Section7";
import C17 from "@/shared/sections/archive-1/Section1";
import C18 from "@/shared/sections/archive-1/Section2";
import C19 from "@/shared/sections/archive-2/Section1";
import C20 from "@/shared/sections/archive-3/Section1";
import C21 from "@/shared/sections/archive-4/Section1";
import C22 from "@/shared/sections/blog-details/Section1";
import C23 from "@/shared/sections/blog-details/Section2";
import C24 from "@/shared/sections/careers/Section1";
import C25 from "@/shared/sections/careers/Section2";
import C26 from "@/shared/sections/coming-soon/Section1";
import C27 from "@/shared/sections/contact-1/Section1";
import C28 from "@/shared/sections/faqs/Section1";
import C29 from "@/shared/sections/faqs/Section2";
import C30 from "@/shared/sections/faqs/Section3";
import C31 from "@/shared/sections/faqs/Section4";
import C32 from "@/shared/sections/index-10/Section1";
import C33 from "@/shared/sections/index-10/Section2";
import C34 from "@/shared/sections/index-10/Section3";
import C35 from "@/shared/sections/index-10/Section4";
import C36 from "@/shared/sections/index-10/Section5";
import C37 from "@/shared/sections/index-10/Section6";
import C38 from "@/shared/sections/index-11/Section1";
import C39 from "@/shared/sections/index-11/Section2";
import C40 from "@/shared/sections/index-11/Section3";
import C41 from "@/shared/sections/index-11/Section4";
import C42 from "@/shared/sections/index-11/Section5";
import C43 from "@/shared/sections/index-11/Section6";
import C44 from "@/shared/sections/index-11/Section7";
import C45 from "@/shared/sections/index-11/Section8";
import C46 from "@/shared/sections/index-12/Section1";
import C47 from "@/shared/sections/index-12/Section2";
import C48 from "@/shared/sections/index-12/Section3";
import C49 from "@/shared/sections/index-12/Section4";
import C50 from "@/shared/sections/index-12/Section5";
import C51 from "@/shared/sections/index-12/Section6";
import C52 from "@/shared/sections/index-12/Section7";
import C53 from "@/shared/sections/index-12/Section8";
import C54 from "@/shared/sections/index-13/Section1";
import C55 from "@/shared/sections/index-13/Section2";
import C56 from "@/shared/sections/index-13/Section3";
import C57 from "@/shared/sections/index-13/Section4";
import C58 from "@/shared/sections/index-13/Section5";
import C59 from "@/shared/sections/index-13/Section6";
import C60 from "@/shared/sections/index-13/Section7";
import C61 from "@/shared/sections/index-13/Section8";
import C62 from "@/shared/sections/index-13/SectionCalc";
import C63 from "@/shared/sections/index-13/SectionFaq";
import C64 from "@/shared/sections/index-13/SectionTrust";
import C65 from "@/shared/sections/index-14/Section1";
import C66 from "@/shared/sections/index-14/Section2";
import C67 from "@/shared/sections/index-14/Section3";
import C68 from "@/shared/sections/index-14/Section4";
import C69 from "@/shared/sections/index-14/Section5";
import C70 from "@/shared/sections/index-14/Section6";
import C71 from "@/shared/sections/index-14/Section7";
import C72 from "@/shared/sections/index-14/Section8";
import C73 from "@/shared/sections/index-14/Section9";
import C74 from "@/shared/sections/index-15/Section1";
import C75 from "@/shared/sections/index-15/Section2";
import C76 from "@/shared/sections/index-15/Section3";
import C77 from "@/shared/sections/index-15/Section4";
import C78 from "@/shared/sections/index-15/Section5";
import C79 from "@/shared/sections/index-15/Section6";
import C80 from "@/shared/sections/index-15/Section7";
import C81 from "@/shared/sections/index-15/Section8";
import C82 from "@/shared/sections/index-15/Section9";
import C83 from "@/shared/sections/index-1/Section1";
import C84 from "@/shared/sections/index-1/Section10";
import C85 from "@/shared/sections/index-1/Section11";
import C86 from "@/shared/sections/index-1/Section12";
import C87 from "@/shared/sections/index-1/Section13";
import C88 from "@/shared/sections/index-1/Section2";
import C89 from "@/shared/sections/index-1/Section3";
import C90 from "@/shared/sections/index-1/Section4";
import C91 from "@/shared/sections/index-1/Section5";
import C92 from "@/shared/sections/index-1/Section6";
import C93 from "@/shared/sections/index-1/Section7";
import C94 from "@/shared/sections/index-1/Section8";
import C95 from "@/shared/sections/index-1/Section9";
import C96 from "@/shared/sections/index-2/Section1";
import C97 from "@/shared/sections/index-2/Section10";
import C98 from "@/shared/sections/index-2/Section11";
import C99 from "@/shared/sections/index-2/Section12";
import C100 from "@/shared/sections/index-2/Section12Pricing";
import C101 from "@/shared/sections/index-2/Section13";
import C102 from "@/shared/sections/index-2/Section2";
import C103 from "@/shared/sections/index-2/Section3";
import C104 from "@/shared/sections/index-2/Section4";
import C105 from "@/shared/sections/index-2/Section5";
import C106 from "@/shared/sections/index-2/Section6";
import C107 from "@/shared/sections/index-2/Section7";
import C108 from "@/shared/sections/index-2/Section8";
import C109 from "@/shared/sections/index-2/Section9";
import C110 from "@/shared/sections/index-3/Section1";
import C111 from "@/shared/sections/index-3/Section10";
import C112 from "@/shared/sections/index-3/Section11";
import C113 from "@/shared/sections/index-3/Section12";
import C114 from "@/shared/sections/index-3/Section2";
import C115 from "@/shared/sections/index-3/Section3";
import C116 from "@/shared/sections/index-3/Section4";
import C117 from "@/shared/sections/index-3/Section5";
import C118 from "@/shared/sections/index-3/Section6";
import C119 from "@/shared/sections/index-3/Section7";
import C120 from "@/shared/sections/index-3/Section8";
import C121 from "@/shared/sections/index-3/Section9";
import C122 from "@/shared/sections/index-4/Section1";
import C123 from "@/shared/sections/index-4/Section2";
import C124 from "@/shared/sections/index-4/Section3";
import C125 from "@/shared/sections/index-4/Section4";
import C126 from "@/shared/sections/index-4/Section5";
import C127 from "@/shared/sections/index-4/Section6";
import C128 from "@/shared/sections/index-4/Section7";
import C129 from "@/shared/sections/index-4/Section8";
import C130 from "@/shared/sections/index-5/Section1";
import C131 from "@/shared/sections/index-5/Section2";
import C132 from "@/shared/sections/index-5/Section3";
import C133 from "@/shared/sections/index-5/Section4";
import C134 from "@/shared/sections/index-5/Section5";
import C135 from "@/shared/sections/index-5/Section6";
import C136 from "@/shared/sections/index-5/Section7";
import C137 from "@/shared/sections/index-5/Section8";
import C138 from "@/shared/sections/index-6/Section1";
import C139 from "@/shared/sections/index-6/Section2";
import C140 from "@/shared/sections/index-6/Section3";
import C141 from "@/shared/sections/index-6/Section4";
import C142 from "@/shared/sections/index-6/Section5";
import C143 from "@/shared/sections/index-6/Section6";
import C144 from "@/shared/sections/index-6/Section7";
import C145 from "@/shared/sections/index-6/Section8";
import C146 from "@/shared/sections/index-6/Section9";
import C147 from "@/shared/sections/index-7/Section1";
import C148 from "@/shared/sections/index-7/Section10";
import C149 from "@/shared/sections/index-7/Section11";
import C150 from "@/shared/sections/index-7/Section12";
import C151 from "@/shared/sections/index-7/Section13";
import C152 from "@/shared/sections/index-7/Section14";
import C153 from "@/shared/sections/index-7/Section15";
import C154 from "@/shared/sections/index-7/Section2";
import C155 from "@/shared/sections/index-7/Section3";
import C156 from "@/shared/sections/index-7/Section4";
import C157 from "@/shared/sections/index-7/Section5";
import C158 from "@/shared/sections/index-7/Section6";
import C159 from "@/shared/sections/index-7/Section7";
import C160 from "@/shared/sections/index-7/Section8";
import C161 from "@/shared/sections/index-7/Section9";
import C162 from "@/shared/sections/index-8/Section1";
import C163 from "@/shared/sections/index-8/Section10";
import C164 from "@/shared/sections/index-8/Section2";
import C165 from "@/shared/sections/index-8/Section3";
import C166 from "@/shared/sections/index-8/Section4";
import C167 from "@/shared/sections/index-8/Section5";
import C168 from "@/shared/sections/index-8/Section6";
import C169 from "@/shared/sections/index-8/Section7";
import C170 from "@/shared/sections/index-8/Section8";
import C171 from "@/shared/sections/index-8/Section9";
import C172 from "@/shared/sections/index-9/Section1";
import C173 from "@/shared/sections/index-9/Section10";
import C174 from "@/shared/sections/index-9/Section2";
import C175 from "@/shared/sections/index-9/Section3";
import C176 from "@/shared/sections/index-9/Section4";
import C177 from "@/shared/sections/index-9/Section5";
import C178 from "@/shared/sections/index-9/Section6";
import C179 from "@/shared/sections/index-9/Section7";
import C180 from "@/shared/sections/index-9/Section8";
import C181 from "@/shared/sections/index-9/Section9";
import C182 from "@/shared/sections/portfolio-1/Section1";
import C183 from "@/shared/sections/portfolio-2/Section1";
import C184 from "@/shared/sections/portfolio-3/Section1";
import C185 from "@/shared/sections/portfolio-4/Section1";
import C186 from "@/shared/sections/portfolio-5/Section1";
import C187 from "@/shared/sections/portfolio-6/Section1";
import C188 from "@/shared/sections/portfolio-details-1/Section1";
import C189 from "@/shared/sections/portfolio-details-1/Section2";
import C190 from "@/shared/sections/portfolio-details-2/Section1";
import C191 from "@/shared/sections/portfolio-details-3/Section1";
import C192 from "@/shared/sections/portfolio-details-3/Section2";
import C193 from "@/shared/sections/portfolio-details-3/Section3";
import C194 from "@/shared/sections/portfolio-details-3/Section4";
import C195 from "@/shared/sections/portfolio-details-3/Section5";
import C196 from "@/shared/sections/portfolio-details-3/Section6";
import C197 from "@/shared/sections/portfolio-details-3/Section7";
import C198 from "@/shared/sections/portfolio-details-3/Section8";
import C199 from "@/shared/sections/portfolio-details-4/Section1";
import C200 from "@/shared/sections/portfolio-details-5/Section1";
import C201 from "@/shared/sections/portfolio-details-6/Section1";
import C202 from "@/shared/sections/product-cart/Section1";
import C203 from "@/shared/sections/product-cart/Section2";
import C204 from "@/shared/sections/product-checkout/Section1";
import C205 from "@/shared/sections/product-details/Section1";
import C206 from "@/shared/sections/product-details/Section1Interactive";
import C207 from "@/shared/sections/product-details/Section2";
import C208 from "@/shared/sections/product-details/Section3";
import C209 from "@/shared/sections/product/Section1";
import C210 from "@/shared/sections/product/Section2";
import C211 from "@/shared/sections/product/Section2Archive";
import C212 from "@/shared/sections/product/Section3";
import C213 from "@/shared/sections/product/Section4";
import C214 from "@/shared/sections/services-1/Section1";
import C215 from "@/shared/sections/services-2/Section1";
import C216 from "@/shared/sections/services-2/Section2";
import C217 from "@/shared/sections/services-2/Section3";
import C218 from "@/shared/sections/services-3/Section1";
import C219 from "@/shared/sections/services-3/Section2";
import C220 from "@/shared/sections/services-details/Section1";
import C221 from "@/shared/sections/services-details/Section2";
import C222 from "@/shared/sections/services-details/Section3";
import C223 from "@/shared/sections/services-details/Section4";
import C224 from "@/shared/sections/services-details/Section5";
import C225 from "@/shared/sections/team-details/Section-1";
import C226 from "@/shared/sections/team-details/Section-2";

export const GENERATED_MANIFESTS: SectionManifest[] = [
  { type: "about_1_Section1", source: "about-1/Section1", label: "About 1: Section1", group: "About", component: C0 as unknown as ComponentType<Record<string, unknown>> },
  { type: "about_1_Section2", source: "about-1/Section2", label: "About 1: Section2", group: "About", component: C1 as unknown as ComponentType<Record<string, unknown>> },
  { type: "about_1_Section3", source: "about-1/Section3", label: "About 1: Section3", group: "About", component: C2 as unknown as ComponentType<Record<string, unknown>> },
  { type: "about_1_Section4", source: "about-1/Section4", label: "About 1: Section4", group: "About", component: C3 as unknown as ComponentType<Record<string, unknown>> },
  { type: "about_1_Section5", source: "about-1/Section5", label: "About 1: Section5", group: "About", component: C4 as unknown as ComponentType<Record<string, unknown>> },
  { type: "about_2_Section1", source: "about-2/Section1", label: "About 2: Section1", group: "About", component: C5 as unknown as ComponentType<Record<string, unknown>> },
  { type: "about_2_Section2", source: "about-2/Section2", label: "About 2: Section2", group: "About", component: C6 as unknown as ComponentType<Record<string, unknown>> },
  { type: "about_2_Section3", source: "about-2/Section3", label: "About 2: Section3", group: "About", component: C7 as unknown as ComponentType<Record<string, unknown>> },
  { type: "about_2_Section4", source: "about-2/Section4", label: "About 2: Section4", group: "About", component: C8 as unknown as ComponentType<Record<string, unknown>> },
  { type: "about_2_Section5", source: "about-2/Section5", label: "About 2: Section5", group: "About", component: C9 as unknown as ComponentType<Record<string, unknown>> },
  { type: "about_3_Section1", source: "about-3/Section1", label: "About 3: Section1", group: "About", component: C10 as unknown as ComponentType<Record<string, unknown>> },
  { type: "about_3_Section2", source: "about-3/Section2", label: "About 3: Section2", group: "About", component: C11 as unknown as ComponentType<Record<string, unknown>> },
  { type: "about_3_Section3", source: "about-3/Section3", label: "About 3: Section3", group: "About", component: C12 as unknown as ComponentType<Record<string, unknown>> },
  { type: "about_3_Section4", source: "about-3/Section4", label: "About 3: Section4", group: "About", component: C13 as unknown as ComponentType<Record<string, unknown>> },
  { type: "about_3_Section5", source: "about-3/Section5", label: "About 3: Section5", group: "About", component: C14 as unknown as ComponentType<Record<string, unknown>> },
  { type: "about_3_Section6", source: "about-3/Section6", label: "About 3: Section6", group: "About", component: C15 as unknown as ComponentType<Record<string, unknown>> },
  { type: "about_3_Section7", source: "about-3/Section7", label: "About 3: Section7", group: "About", component: C16 as unknown as ComponentType<Record<string, unknown>> },
  { type: "archive_1_Section1", source: "archive-1/Section1", label: "Archive 1: Section1", group: "Blog & Archive", component: C17 as unknown as ComponentType<Record<string, unknown>> },
  { type: "archive_1_Section2", source: "archive-1/Section2", label: "Archive 1: Section2", group: "Blog & Archive", component: C18 as unknown as ComponentType<Record<string, unknown>> },
  { type: "archive_2_Section1", source: "archive-2/Section1", label: "Archive 2: Section1", group: "Blog & Archive", component: C19 as unknown as ComponentType<Record<string, unknown>> },
  { type: "archive_3_Section1", source: "archive-3/Section1", label: "Archive 3: Section1", group: "Blog & Archive", component: C20 as unknown as ComponentType<Record<string, unknown>> },
  { type: "archive_4_Section1", source: "archive-4/Section1", label: "Archive 4: Section1", group: "Blog & Archive", component: C21 as unknown as ComponentType<Record<string, unknown>> },
  { type: "blog_details_Section1", source: "blog-details/Section1", label: "Blog Details: Section1", group: "Blog & Archive", component: C22 as unknown as ComponentType<Record<string, unknown>> },
  { type: "blog_details_Section2", source: "blog-details/Section2", label: "Blog Details: Section2", group: "Blog & Archive", component: C23 as unknown as ComponentType<Record<string, unknown>> },
  { type: "careers_Section1", source: "careers/Section1", label: "Careers: Section1", group: "Careers", component: C24 as unknown as ComponentType<Record<string, unknown>> },
  { type: "careers_Section2", source: "careers/Section2", label: "Careers: Section2", group: "Careers", component: C25 as unknown as ComponentType<Record<string, unknown>> },
  { type: "coming_soon_Section1", source: "coming-soon/Section1", label: "Coming Soon: Section1", group: "Other", component: C26 as unknown as ComponentType<Record<string, unknown>> },
  { type: "contact_1_Section1", source: "contact-1/Section1", label: "Contact 1: Section1", group: "Contact", component: C27 as unknown as ComponentType<Record<string, unknown>> },
  { type: "faqs_Section1", source: "faqs/Section1", label: "Faqs: Section1", group: "FAQ", component: C28 as unknown as ComponentType<Record<string, unknown>> },
  { type: "faqs_Section2", source: "faqs/Section2", label: "Faqs: Section2", group: "FAQ", component: C29 as unknown as ComponentType<Record<string, unknown>> },
  { type: "faqs_Section3", source: "faqs/Section3", label: "Faqs: Section3", group: "FAQ", component: C30 as unknown as ComponentType<Record<string, unknown>> },
  { type: "faqs_Section4", source: "faqs/Section4", label: "Faqs: Section4", group: "FAQ", component: C31 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_10_Section1", source: "index-10/Section1", label: "Index 10: Section1", group: "Home sections", component: C32 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_10_Section2", source: "index-10/Section2", label: "Index 10: Section2", group: "Home sections", component: C33 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_10_Section3", source: "index-10/Section3", label: "Index 10: Section3", group: "Home sections", component: C34 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_10_Section4", source: "index-10/Section4", label: "Index 10: Section4", group: "Home sections", component: C35 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_10_Section5", source: "index-10/Section5", label: "Index 10: Section5", group: "Home sections", component: C36 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_10_Section6", source: "index-10/Section6", label: "Index 10: Section6", group: "Home sections", component: C37 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_11_Section1", source: "index-11/Section1", label: "Index 11: Section1", group: "Home sections", component: C38 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_11_Section2", source: "index-11/Section2", label: "Index 11: Section2", group: "Home sections", component: C39 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_11_Section3", source: "index-11/Section3", label: "Index 11: Section3", group: "Home sections", component: C40 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_11_Section4", source: "index-11/Section4", label: "Index 11: Section4", group: "Home sections", component: C41 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_11_Section5", source: "index-11/Section5", label: "Index 11: Section5", group: "Home sections", component: C42 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_11_Section6", source: "index-11/Section6", label: "Index 11: Section6", group: "Home sections", component: C43 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_11_Section7", source: "index-11/Section7", label: "Index 11: Section7", group: "Home sections", component: C44 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_11_Section8", source: "index-11/Section8", label: "Index 11: Section8", group: "Home sections", component: C45 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_12_Section1", source: "index-12/Section1", label: "Index 12: Section1", group: "Home sections", component: C46 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_12_Section2", source: "index-12/Section2", label: "Index 12: Section2", group: "Home sections", component: C47 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_12_Section3", source: "index-12/Section3", label: "Index 12: Section3", group: "Home sections", component: C48 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_12_Section4", source: "index-12/Section4", label: "Index 12: Section4", group: "Home sections", component: C49 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_12_Section5", source: "index-12/Section5", label: "Index 12: Section5", group: "Home sections", component: C50 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_12_Section6", source: "index-12/Section6", label: "Index 12: Section6", group: "Home sections", component: C51 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_12_Section7", source: "index-12/Section7", label: "Index 12: Section7", group: "Home sections", component: C52 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_12_Section8", source: "index-12/Section8", label: "Index 12: Section8", group: "Home sections", component: C53 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_13_Section1", source: "index-13/Section1", label: "Index 13: Section1", group: "Home sections", component: C54 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_13_Section2", source: "index-13/Section2", label: "Index 13: Section2", group: "Home sections", component: C55 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_13_Section3", source: "index-13/Section3", label: "Index 13: Section3", group: "Home sections", component: C56 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_13_Section4", source: "index-13/Section4", label: "Index 13: Section4", group: "Home sections", component: C57 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_13_Section5", source: "index-13/Section5", label: "Index 13: Section5", group: "Home sections", component: C58 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_13_Section6", source: "index-13/Section6", label: "Index 13: Section6", group: "Home sections", component: C59 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_13_Section7", source: "index-13/Section7", label: "Index 13: Section7", group: "Home sections", component: C60 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_13_Section8", source: "index-13/Section8", label: "Index 13: Section8", group: "Home sections", component: C61 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_13_SectionCalc", source: "index-13/SectionCalc", label: "Index 13: SectionCalc", group: "Home sections", component: C62 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_13_SectionFaq", source: "index-13/SectionFaq", label: "Index 13: SectionFaq", group: "Home sections", component: C63 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_13_SectionTrust", source: "index-13/SectionTrust", label: "Index 13: SectionTrust", group: "Home sections", component: C64 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_14_Section1", source: "index-14/Section1", label: "Index 14: Section1", group: "Home sections", component: C65 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_14_Section2", source: "index-14/Section2", label: "Index 14: Section2", group: "Home sections", component: C66 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_14_Section3", source: "index-14/Section3", label: "Index 14: Section3", group: "Home sections", component: C67 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_14_Section4", source: "index-14/Section4", label: "Index 14: Section4", group: "Home sections", component: C68 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_14_Section5", source: "index-14/Section5", label: "Index 14: Section5", group: "Home sections", component: C69 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_14_Section6", source: "index-14/Section6", label: "Index 14: Section6", group: "Home sections", component: C70 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_14_Section7", source: "index-14/Section7", label: "Index 14: Section7", group: "Home sections", component: C71 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_14_Section8", source: "index-14/Section8", label: "Index 14: Section8", group: "Home sections", component: C72 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_14_Section9", source: "index-14/Section9", label: "Index 14: Section9", group: "Home sections", component: C73 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_15_Section1", source: "index-15/Section1", label: "Index 15: Section1", group: "Home sections", component: C74 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_15_Section2", source: "index-15/Section2", label: "Index 15: Section2", group: "Home sections", component: C75 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_15_Section3", source: "index-15/Section3", label: "Index 15: Section3", group: "Home sections", component: C76 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_15_Section4", source: "index-15/Section4", label: "Index 15: Section4", group: "Home sections", component: C77 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_15_Section5", source: "index-15/Section5", label: "Index 15: Section5", group: "Home sections", component: C78 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_15_Section6", source: "index-15/Section6", label: "Index 15: Section6", group: "Home sections", component: C79 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_15_Section7", source: "index-15/Section7", label: "Index 15: Section7", group: "Home sections", component: C80 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_15_Section8", source: "index-15/Section8", label: "Index 15: Section8", group: "Home sections", component: C81 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_15_Section9", source: "index-15/Section9", label: "Index 15: Section9", group: "Home sections", component: C82 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_1_Section1", source: "index-1/Section1", label: "Index 1: Section1", group: "Home sections", component: C83 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_1_Section10", source: "index-1/Section10", label: "Index 1: Section10", group: "Home sections", component: C84 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_1_Section11", source: "index-1/Section11", label: "Index 1: Section11", group: "Home sections", component: C85 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_1_Section12", source: "index-1/Section12", label: "Index 1: Section12", group: "Home sections", component: C86 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_1_Section13", source: "index-1/Section13", label: "Index 1: Section13", group: "Home sections", component: C87 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_1_Section2", source: "index-1/Section2", label: "Index 1: Section2", group: "Home sections", component: C88 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_1_Section3", source: "index-1/Section3", label: "Index 1: Section3", group: "Home sections", component: C89 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_1_Section4", source: "index-1/Section4", label: "Index 1: Section4", group: "Home sections", component: C90 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_1_Section5", source: "index-1/Section5", label: "Index 1: Section5", group: "Home sections", component: C91 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_1_Section6", source: "index-1/Section6", label: "Index 1: Section6", group: "Home sections", component: C92 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_1_Section7", source: "index-1/Section7", label: "Index 1: Section7", group: "Home sections", component: C93 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_1_Section8", source: "index-1/Section8", label: "Index 1: Section8", group: "Home sections", component: C94 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_1_Section9", source: "index-1/Section9", label: "Index 1: Section9", group: "Home sections", component: C95 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_2_Section1", source: "index-2/Section1", label: "Index 2: Section1", group: "Home sections", component: C96 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_2_Section10", source: "index-2/Section10", label: "Index 2: Section10", group: "Home sections", component: C97 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_2_Section11", source: "index-2/Section11", label: "Index 2: Section11", group: "Home sections", component: C98 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_2_Section12", source: "index-2/Section12", label: "Index 2: Section12", group: "Home sections", component: C99 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_2_Section12Pricing", source: "index-2/Section12Pricing", label: "Index 2: Section12Pricing", group: "Home sections", component: C100 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_2_Section13", source: "index-2/Section13", label: "Index 2: Section13", group: "Home sections", component: C101 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_2_Section2", source: "index-2/Section2", label: "Index 2: Section2", group: "Home sections", component: C102 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_2_Section3", source: "index-2/Section3", label: "Index 2: Section3", group: "Home sections", component: C103 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_2_Section4", source: "index-2/Section4", label: "Index 2: Section4", group: "Home sections", component: C104 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_2_Section5", source: "index-2/Section5", label: "Index 2: Section5", group: "Home sections", component: C105 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_2_Section6", source: "index-2/Section6", label: "Index 2: Section6", group: "Home sections", component: C106 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_2_Section7", source: "index-2/Section7", label: "Index 2: Section7", group: "Home sections", component: C107 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_2_Section8", source: "index-2/Section8", label: "Index 2: Section8", group: "Home sections", component: C108 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_2_Section9", source: "index-2/Section9", label: "Index 2: Section9", group: "Home sections", component: C109 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_3_Section1", source: "index-3/Section1", label: "Index 3: Section1", group: "Home sections", component: C110 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_3_Section10", source: "index-3/Section10", label: "Index 3: Section10", group: "Home sections", component: C111 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_3_Section11", source: "index-3/Section11", label: "Index 3: Section11", group: "Home sections", component: C112 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_3_Section12", source: "index-3/Section12", label: "Index 3: Section12", group: "Home sections", component: C113 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_3_Section2", source: "index-3/Section2", label: "Index 3: Section2", group: "Home sections", component: C114 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_3_Section3", source: "index-3/Section3", label: "Index 3: Section3", group: "Home sections", component: C115 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_3_Section4", source: "index-3/Section4", label: "Index 3: Section4", group: "Home sections", component: C116 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_3_Section5", source: "index-3/Section5", label: "Index 3: Section5", group: "Home sections", component: C117 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_3_Section6", source: "index-3/Section6", label: "Index 3: Section6", group: "Home sections", component: C118 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_3_Section7", source: "index-3/Section7", label: "Index 3: Section7", group: "Home sections", component: C119 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_3_Section8", source: "index-3/Section8", label: "Index 3: Section8", group: "Home sections", component: C120 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_3_Section9", source: "index-3/Section9", label: "Index 3: Section9", group: "Home sections", component: C121 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_4_Section1", source: "index-4/Section1", label: "Index 4: Section1", group: "Home sections", component: C122 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_4_Section2", source: "index-4/Section2", label: "Index 4: Section2", group: "Home sections", component: C123 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_4_Section3", source: "index-4/Section3", label: "Index 4: Section3", group: "Home sections", component: C124 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_4_Section4", source: "index-4/Section4", label: "Index 4: Section4", group: "Home sections", component: C125 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_4_Section5", source: "index-4/Section5", label: "Index 4: Section5", group: "Home sections", component: C126 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_4_Section6", source: "index-4/Section6", label: "Index 4: Section6", group: "Home sections", component: C127 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_4_Section7", source: "index-4/Section7", label: "Index 4: Section7", group: "Home sections", component: C128 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_4_Section8", source: "index-4/Section8", label: "Index 4: Section8", group: "Home sections", component: C129 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_5_Section1", source: "index-5/Section1", label: "Index 5: Section1", group: "Home sections", component: C130 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_5_Section2", source: "index-5/Section2", label: "Index 5: Section2", group: "Home sections", component: C131 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_5_Section3", source: "index-5/Section3", label: "Index 5: Section3", group: "Home sections", component: C132 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_5_Section4", source: "index-5/Section4", label: "Index 5: Section4", group: "Home sections", component: C133 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_5_Section5", source: "index-5/Section5", label: "Index 5: Section5", group: "Home sections", component: C134 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_5_Section6", source: "index-5/Section6", label: "Index 5: Section6", group: "Home sections", component: C135 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_5_Section7", source: "index-5/Section7", label: "Index 5: Section7", group: "Home sections", component: C136 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_5_Section8", source: "index-5/Section8", label: "Index 5: Section8", group: "Home sections", component: C137 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_6_Section1", source: "index-6/Section1", label: "Index 6: Section1", group: "Home sections", component: C138 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_6_Section2", source: "index-6/Section2", label: "Index 6: Section2", group: "Home sections", component: C139 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_6_Section3", source: "index-6/Section3", label: "Index 6: Section3", group: "Home sections", component: C140 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_6_Section4", source: "index-6/Section4", label: "Index 6: Section4", group: "Home sections", component: C141 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_6_Section5", source: "index-6/Section5", label: "Index 6: Section5", group: "Home sections", component: C142 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_6_Section6", source: "index-6/Section6", label: "Index 6: Section6", group: "Home sections", component: C143 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_6_Section7", source: "index-6/Section7", label: "Index 6: Section7", group: "Home sections", component: C144 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_6_Section8", source: "index-6/Section8", label: "Index 6: Section8", group: "Home sections", component: C145 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_6_Section9", source: "index-6/Section9", label: "Index 6: Section9", group: "Home sections", component: C146 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_7_Section1", source: "index-7/Section1", label: "Index 7: Section1", group: "Home sections", component: C147 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_7_Section10", source: "index-7/Section10", label: "Index 7: Section10", group: "Home sections", component: C148 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_7_Section11", source: "index-7/Section11", label: "Index 7: Section11", group: "Home sections", component: C149 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_7_Section12", source: "index-7/Section12", label: "Index 7: Section12", group: "Home sections", component: C150 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_7_Section13", source: "index-7/Section13", label: "Index 7: Section13", group: "Home sections", component: C151 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_7_Section14", source: "index-7/Section14", label: "Index 7: Section14", group: "Home sections", component: C152 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_7_Section15", source: "index-7/Section15", label: "Index 7: Section15", group: "Home sections", component: C153 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_7_Section2", source: "index-7/Section2", label: "Index 7: Section2", group: "Home sections", component: C154 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_7_Section3", source: "index-7/Section3", label: "Index 7: Section3", group: "Home sections", component: C155 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_7_Section4", source: "index-7/Section4", label: "Index 7: Section4", group: "Home sections", component: C156 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_7_Section5", source: "index-7/Section5", label: "Index 7: Section5", group: "Home sections", component: C157 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_7_Section6", source: "index-7/Section6", label: "Index 7: Section6", group: "Home sections", component: C158 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_7_Section7", source: "index-7/Section7", label: "Index 7: Section7", group: "Home sections", component: C159 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_7_Section8", source: "index-7/Section8", label: "Index 7: Section8", group: "Home sections", component: C160 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_7_Section9", source: "index-7/Section9", label: "Index 7: Section9", group: "Home sections", component: C161 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_8_Section1", source: "index-8/Section1", label: "Index 8: Section1", group: "Home sections", component: C162 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_8_Section10", source: "index-8/Section10", label: "Index 8: Section10", group: "Home sections", component: C163 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_8_Section2", source: "index-8/Section2", label: "Index 8: Section2", group: "Home sections", component: C164 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_8_Section3", source: "index-8/Section3", label: "Index 8: Section3", group: "Home sections", component: C165 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_8_Section4", source: "index-8/Section4", label: "Index 8: Section4", group: "Home sections", component: C166 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_8_Section5", source: "index-8/Section5", label: "Index 8: Section5", group: "Home sections", component: C167 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_8_Section6", source: "index-8/Section6", label: "Index 8: Section6", group: "Home sections", component: C168 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_8_Section7", source: "index-8/Section7", label: "Index 8: Section7", group: "Home sections", component: C169 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_8_Section8", source: "index-8/Section8", label: "Index 8: Section8", group: "Home sections", component: C170 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_8_Section9", source: "index-8/Section9", label: "Index 8: Section9", group: "Home sections", component: C171 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_9_Section1", source: "index-9/Section1", label: "Index 9: Section1", group: "Home sections", component: C172 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_9_Section10", source: "index-9/Section10", label: "Index 9: Section10", group: "Home sections", component: C173 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_9_Section2", source: "index-9/Section2", label: "Index 9: Section2", group: "Home sections", component: C174 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_9_Section3", source: "index-9/Section3", label: "Index 9: Section3", group: "Home sections", component: C175 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_9_Section4", source: "index-9/Section4", label: "Index 9: Section4", group: "Home sections", component: C176 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_9_Section5", source: "index-9/Section5", label: "Index 9: Section5", group: "Home sections", component: C177 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_9_Section6", source: "index-9/Section6", label: "Index 9: Section6", group: "Home sections", component: C178 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_9_Section7", source: "index-9/Section7", label: "Index 9: Section7", group: "Home sections", component: C179 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_9_Section8", source: "index-9/Section8", label: "Index 9: Section8", group: "Home sections", component: C180 as unknown as ComponentType<Record<string, unknown>> },
  { type: "index_9_Section9", source: "index-9/Section9", label: "Index 9: Section9", group: "Home sections", component: C181 as unknown as ComponentType<Record<string, unknown>> },
  { type: "portfolio_1_Section1", source: "portfolio-1/Section1", label: "Portfolio 1: Section1", group: "Portfolio", component: C182 as unknown as ComponentType<Record<string, unknown>> },
  { type: "portfolio_2_Section1", source: "portfolio-2/Section1", label: "Portfolio 2: Section1", group: "Portfolio", component: C183 as unknown as ComponentType<Record<string, unknown>> },
  { type: "portfolio_3_Section1", source: "portfolio-3/Section1", label: "Portfolio 3: Section1", group: "Portfolio", component: C184 as unknown as ComponentType<Record<string, unknown>> },
  { type: "portfolio_4_Section1", source: "portfolio-4/Section1", label: "Portfolio 4: Section1", group: "Portfolio", component: C185 as unknown as ComponentType<Record<string, unknown>> },
  { type: "portfolio_5_Section1", source: "portfolio-5/Section1", label: "Portfolio 5: Section1", group: "Portfolio", component: C186 as unknown as ComponentType<Record<string, unknown>> },
  { type: "portfolio_6_Section1", source: "portfolio-6/Section1", label: "Portfolio 6: Section1", group: "Portfolio", component: C187 as unknown as ComponentType<Record<string, unknown>> },
  { type: "portfolio_details_1_Section1", source: "portfolio-details-1/Section1", label: "Portfolio Details 1: Section1", group: "Portfolio", component: C188 as unknown as ComponentType<Record<string, unknown>> },
  { type: "portfolio_details_1_Section2", source: "portfolio-details-1/Section2", label: "Portfolio Details 1: Section2", group: "Portfolio", component: C189 as unknown as ComponentType<Record<string, unknown>> },
  { type: "portfolio_details_2_Section1", source: "portfolio-details-2/Section1", label: "Portfolio Details 2: Section1", group: "Portfolio", component: C190 as unknown as ComponentType<Record<string, unknown>> },
  { type: "portfolio_details_3_Section1", source: "portfolio-details-3/Section1", label: "Portfolio Details 3: Section1", group: "Portfolio", component: C191 as unknown as ComponentType<Record<string, unknown>> },
  { type: "portfolio_details_3_Section2", source: "portfolio-details-3/Section2", label: "Portfolio Details 3: Section2", group: "Portfolio", component: C192 as unknown as ComponentType<Record<string, unknown>> },
  { type: "portfolio_details_3_Section3", source: "portfolio-details-3/Section3", label: "Portfolio Details 3: Section3", group: "Portfolio", component: C193 as unknown as ComponentType<Record<string, unknown>> },
  { type: "portfolio_details_3_Section4", source: "portfolio-details-3/Section4", label: "Portfolio Details 3: Section4", group: "Portfolio", component: C194 as unknown as ComponentType<Record<string, unknown>> },
  { type: "portfolio_details_3_Section5", source: "portfolio-details-3/Section5", label: "Portfolio Details 3: Section5", group: "Portfolio", component: C195 as unknown as ComponentType<Record<string, unknown>> },
  { type: "portfolio_details_3_Section6", source: "portfolio-details-3/Section6", label: "Portfolio Details 3: Section6", group: "Portfolio", component: C196 as unknown as ComponentType<Record<string, unknown>> },
  { type: "portfolio_details_3_Section7", source: "portfolio-details-3/Section7", label: "Portfolio Details 3: Section7", group: "Portfolio", component: C197 as unknown as ComponentType<Record<string, unknown>> },
  { type: "portfolio_details_3_Section8", source: "portfolio-details-3/Section8", label: "Portfolio Details 3: Section8", group: "Portfolio", component: C198 as unknown as ComponentType<Record<string, unknown>> },
  { type: "portfolio_details_4_Section1", source: "portfolio-details-4/Section1", label: "Portfolio Details 4: Section1", group: "Portfolio", component: C199 as unknown as ComponentType<Record<string, unknown>> },
  { type: "portfolio_details_5_Section1", source: "portfolio-details-5/Section1", label: "Portfolio Details 5: Section1", group: "Portfolio", component: C200 as unknown as ComponentType<Record<string, unknown>> },
  { type: "portfolio_details_6_Section1", source: "portfolio-details-6/Section1", label: "Portfolio Details 6: Section1", group: "Portfolio", component: C201 as unknown as ComponentType<Record<string, unknown>> },
  { type: "product_cart_Section1", source: "product-cart/Section1", label: "Product Cart: Section1", group: "Commerce", component: C202 as unknown as ComponentType<Record<string, unknown>> },
  { type: "product_cart_Section2", source: "product-cart/Section2", label: "Product Cart: Section2", group: "Commerce", component: C203 as unknown as ComponentType<Record<string, unknown>> },
  { type: "product_checkout_Section1", source: "product-checkout/Section1", label: "Product Checkout: Section1", group: "Commerce", component: C204 as unknown as ComponentType<Record<string, unknown>> },
  { type: "product_details_Section1", source: "product-details/Section1", label: "Product Details: Section1", group: "Commerce", component: C205 as unknown as ComponentType<Record<string, unknown>> },
  { type: "product_details_Section1Interactive", source: "product-details/Section1Interactive", label: "Product Details: Section1Interactive", group: "Commerce", component: C206 as unknown as ComponentType<Record<string, unknown>> },
  { type: "product_details_Section2", source: "product-details/Section2", label: "Product Details: Section2", group: "Commerce", component: C207 as unknown as ComponentType<Record<string, unknown>> },
  { type: "product_details_Section3", source: "product-details/Section3", label: "Product Details: Section3", group: "Commerce", component: C208 as unknown as ComponentType<Record<string, unknown>> },
  { type: "product_Section1", source: "product/Section1", label: "Product: Section1", group: "Commerce", component: C209 as unknown as ComponentType<Record<string, unknown>> },
  { type: "product_Section2", source: "product/Section2", label: "Product: Section2", group: "Commerce", component: C210 as unknown as ComponentType<Record<string, unknown>> },
  { type: "product_Section2Archive", source: "product/Section2Archive", label: "Product: Section2Archive", group: "Commerce", component: C211 as unknown as ComponentType<Record<string, unknown>> },
  { type: "product_Section3", source: "product/Section3", label: "Product: Section3", group: "Commerce", component: C212 as unknown as ComponentType<Record<string, unknown>> },
  { type: "product_Section4", source: "product/Section4", label: "Product: Section4", group: "Commerce", component: C213 as unknown as ComponentType<Record<string, unknown>> },
  { type: "services_1_Section1", source: "services-1/Section1", label: "Services 1: Section1", group: "Services", component: C214 as unknown as ComponentType<Record<string, unknown>> },
  { type: "services_2_Section1", source: "services-2/Section1", label: "Services 2: Section1", group: "Services", component: C215 as unknown as ComponentType<Record<string, unknown>> },
  { type: "services_2_Section2", source: "services-2/Section2", label: "Services 2: Section2", group: "Services", component: C216 as unknown as ComponentType<Record<string, unknown>> },
  { type: "services_2_Section3", source: "services-2/Section3", label: "Services 2: Section3", group: "Services", component: C217 as unknown as ComponentType<Record<string, unknown>> },
  { type: "services_3_Section1", source: "services-3/Section1", label: "Services 3: Section1", group: "Services", component: C218 as unknown as ComponentType<Record<string, unknown>> },
  { type: "services_3_Section2", source: "services-3/Section2", label: "Services 3: Section2", group: "Services", component: C219 as unknown as ComponentType<Record<string, unknown>> },
  { type: "services_details_Section1", source: "services-details/Section1", label: "Services Details: Section1", group: "Services", component: C220 as unknown as ComponentType<Record<string, unknown>> },
  { type: "services_details_Section2", source: "services-details/Section2", label: "Services Details: Section2", group: "Services", component: C221 as unknown as ComponentType<Record<string, unknown>> },
  { type: "services_details_Section3", source: "services-details/Section3", label: "Services Details: Section3", group: "Services", component: C222 as unknown as ComponentType<Record<string, unknown>> },
  { type: "services_details_Section4", source: "services-details/Section4", label: "Services Details: Section4", group: "Services", component: C223 as unknown as ComponentType<Record<string, unknown>> },
  { type: "services_details_Section5", source: "services-details/Section5", label: "Services Details: Section5", group: "Services", component: C224 as unknown as ComponentType<Record<string, unknown>> },
  { type: "team_details_Section_1", source: "team-details/Section-1", label: "Team Details: Section 1", group: "Team", component: C225 as unknown as ComponentType<Record<string, unknown>> },
  { type: "team_details_Section_2", source: "team-details/Section-2", label: "Team Details: Section 2", group: "Team", component: C226 as unknown as ComponentType<Record<string, unknown>> },
];
