// AUTO-GENERATED by scripts/gen-page-templates.mjs — do not edit by hand.
// 50 starter templates derived from src/pages. Each is an editable
// Puck document referencing registered sections. Re-run the script to refresh.
import type { PageDocument } from "@/builder/types";

export type PageTemplate = { name: string; slug: string; sourcePage: string; document: PageDocument };

// Cast suppresses excess-property checks: our layout props (headerStyle, etc.)
// live on root.props, which Puck's Data types narrowly. They are valid at runtime.
export const PAGE_TEMPLATES = ([
  {
    "name": "About 1",
    "slug": "about-1",
    "sourcePage": "src/pages/About1Page.tsx",
    "document": {
      "root": {
        "props": {
          "title": "About 1",
          "headerStyle": 1,
          "footerStyle": 1,
          "noHeader": false,
          "noFooter": false,
          "mainClass": "bg-neutral-0"
        }
      },
      "content": [
        {
          "type": "AboutHero1",
          "props": {
            "id": "AboutHero1-0"
          }
        },
        {
          "type": "index_2_Section9",
          "props": {
            "id": "index_2_Section9-1"
          }
        },
        {
          "type": "about_1_Section2",
          "props": {
            "id": "about_1_Section2-2"
          }
        },
        {
          "type": "about_1_Section3",
          "props": {
            "id": "about_1_Section3-3"
          }
        },
        {
          "type": "TeamIntro1",
          "props": {
            "id": "TeamIntro1-4"
          }
        },
        {
          "type": "about_1_Section4",
          "props": {
            "id": "about_1_Section4-5"
          }
        },
        {
          "type": "index_3_Section11",
          "props": {
            "id": "index_3_Section11-6"
          }
        },
        {
          "type": "about_1_Section5",
          "props": {
            "id": "about_1_Section5-7"
          }
        }
      ],
      "zones": {}
    }
  },
  {
    "name": "About 2",
    "slug": "about-2",
    "sourcePage": "src/pages/About2Page.tsx",
    "document": {
      "root": {
        "props": {
          "title": "About 2",
          "headerStyle": 1,
          "footerStyle": 1,
          "noHeader": false,
          "noFooter": false,
          "mainClass": "bg-neutral-0"
        }
      },
      "content": [
        {
          "type": "about_2_Section1",
          "props": {
            "id": "about_2_Section1-8"
          }
        },
        {
          "type": "about_2_Section2",
          "props": {
            "id": "about_2_Section2-9"
          }
        },
        {
          "type": "about_2_Section3",
          "props": {
            "id": "about_2_Section3-a"
          }
        },
        {
          "type": "about_2_Section4",
          "props": {
            "id": "about_2_Section4-b"
          }
        },
        {
          "type": "about_2_Section5",
          "props": {
            "id": "about_2_Section5-c"
          }
        },
        {
          "type": "about_1_Section4",
          "props": {
            "id": "about_1_Section4-d"
          }
        }
      ],
      "zones": {}
    }
  },
  {
    "name": "About 3",
    "slug": "about-3",
    "sourcePage": "src/pages/About3Page.tsx",
    "document": {
      "root": {
        "props": {
          "title": "About 3",
          "headerStyle": 1,
          "footerStyle": 1,
          "noHeader": false,
          "noFooter": false,
          "mainClass": "bg-neutral-0"
        }
      },
      "content": [
        {
          "type": "about_3_Section1",
          "props": {
            "id": "about_3_Section1-e"
          }
        },
        {
          "type": "about_3_Section2",
          "props": {
            "id": "about_3_Section2-f"
          }
        },
        {
          "type": "about_3_Section3",
          "props": {
            "id": "about_3_Section3-g"
          }
        },
        {
          "type": "about_3_Section4",
          "props": {
            "id": "about_3_Section4-h"
          }
        },
        {
          "type": "about_3_Section5",
          "props": {
            "id": "about_3_Section5-i"
          }
        },
        {
          "type": "about_3_Section6",
          "props": {
            "id": "about_3_Section6-j"
          }
        },
        {
          "type": "about_3_Section7",
          "props": {
            "id": "about_3_Section7-k"
          }
        }
      ],
      "zones": {}
    }
  },
  {
    "name": "Archive 1",
    "slug": "archive-1",
    "sourcePage": "src/pages/Archive1Page.tsx",
    "document": {
      "root": {
        "props": {
          "title": "Archive 1",
          "headerStyle": 1,
          "footerStyle": 1,
          "noHeader": false,
          "noFooter": false,
          "mainClass": "bg-neutral-0"
        }
      },
      "content": [
        {
          "type": "archive_1_Section1",
          "props": {
            "id": "archive_1_Section1-l"
          }
        },
        {
          "type": "archive_1_Section2",
          "props": {
            "id": "archive_1_Section2-m"
          }
        },
        {
          "type": "index_3_Section12",
          "props": {
            "id": "index_3_Section12-n"
          }
        }
      ],
      "zones": {}
    }
  },
  {
    "name": "Archive 2",
    "slug": "archive-2",
    "sourcePage": "src/pages/Archive2Page.tsx",
    "document": {
      "root": {
        "props": {
          "title": "Archive 2",
          "headerStyle": 1,
          "footerStyle": 1,
          "noHeader": false,
          "noFooter": false,
          "mainClass": "bg-neutral-0"
        }
      },
      "content": [
        {
          "type": "archive_2_Section1",
          "props": {
            "id": "archive_2_Section1-o"
          }
        },
        {
          "type": "index_3_Section12",
          "props": {
            "id": "index_3_Section12-p"
          }
        }
      ],
      "zones": {}
    }
  },
  {
    "name": "Archive 3",
    "slug": "archive-3",
    "sourcePage": "src/pages/Archive3Page.tsx",
    "document": {
      "root": {
        "props": {
          "title": "Archive 3",
          "headerStyle": 1,
          "footerStyle": 1,
          "noHeader": false,
          "noFooter": false,
          "mainClass": "bg-neutral-0"
        }
      },
      "content": [
        {
          "type": "archive_3_Section1",
          "props": {
            "id": "archive_3_Section1-q"
          }
        },
        {
          "type": "index_3_Section12",
          "props": {
            "id": "index_3_Section12-r"
          }
        }
      ],
      "zones": {}
    }
  },
  {
    "name": "Archive 4",
    "slug": "archive-4",
    "sourcePage": "src/pages/Archive4Page.tsx",
    "document": {
      "root": {
        "props": {
          "title": "Archive 4",
          "headerStyle": 1,
          "footerStyle": 1,
          "noHeader": false,
          "noFooter": false,
          "mainClass": "bg-neutral-0"
        }
      },
      "content": [
        {
          "type": "archive_4_Section1",
          "props": {
            "id": "archive_4_Section1-s"
          }
        },
        {
          "type": "index_3_Section12",
          "props": {
            "id": "index_3_Section12-t"
          }
        }
      ],
      "zones": {}
    }
  },
  {
    "name": "Blog Details",
    "slug": "blog-details",
    "sourcePage": "src/pages/BlogDetailsPage.tsx",
    "document": {
      "root": {
        "props": {
          "title": "Blog Details",
          "headerStyle": 1,
          "footerStyle": 1,
          "noHeader": false,
          "noFooter": false,
          "mainClass": "bg-neutral-0"
        }
      },
      "content": [
        {
          "type": "blog_details_Section1",
          "props": {
            "id": "blog_details_Section1-u"
          }
        },
        {
          "type": "blog_details_Section2",
          "props": {
            "id": "blog_details_Section2-v"
          }
        }
      ],
      "zones": {}
    }
  },
  {
    "name": "Careers",
    "slug": "careers",
    "sourcePage": "src/pages/CareersPage.tsx",
    "document": {
      "root": {
        "props": {
          "title": "Careers",
          "headerStyle": 1,
          "footerStyle": 1,
          "noHeader": false,
          "noFooter": false,
          "mainClass": "bg-neutral-0"
        }
      },
      "content": [
        {
          "type": "careers_Section1",
          "props": {
            "id": "careers_Section1-w"
          }
        },
        {
          "type": "careers_Section2",
          "props": {
            "id": "careers_Section2-x"
          }
        }
      ],
      "zones": {}
    }
  },
  {
    "name": "Contact 1",
    "slug": "contact-1",
    "sourcePage": "src/pages/Contact1Page.tsx",
    "document": {
      "root": {
        "props": {
          "title": "Contact 1",
          "headerStyle": 1,
          "footerStyle": 1,
          "noHeader": false,
          "noFooter": false,
          "mainClass": "bg-neutral-0"
        }
      },
      "content": [
        {
          "type": "contact_1_Section1",
          "props": {
            "id": "contact_1_Section1-y"
          }
        },
        {
          "type": "about_2_Section4",
          "props": {
            "id": "about_2_Section4-z"
          }
        }
      ],
      "zones": {}
    }
  },
  {
    "name": "Contact 2",
    "slug": "contact-2",
    "sourcePage": "src/pages/Contact2Page.tsx",
    "document": {
      "root": {
        "props": {
          "title": "Contact 2",
          "headerStyle": 1,
          "footerStyle": 1,
          "noHeader": false,
          "noFooter": false,
          "mainClass": "bg-neutral-0"
        }
      },
      "content": [
        {
          "type": "about_1_Section4",
          "props": {
            "id": "about_1_Section4-10"
          }
        }
      ],
      "zones": {}
    }
  },
  {
    "name": "Faqs",
    "slug": "faqs",
    "sourcePage": "src/pages/FaqsPage.tsx",
    "document": {
      "root": {
        "props": {
          "title": "Faqs",
          "headerStyle": 1,
          "footerStyle": 1,
          "noHeader": false,
          "noFooter": false,
          "mainClass": "bg-neutral-0"
        }
      },
      "content": [
        {
          "type": "FaqHero1",
          "props": {
            "id": "FaqHero1-11"
          }
        },
        {
          "type": "FaqTopics1",
          "props": {
            "id": "FaqTopics1-12"
          }
        },
        {
          "type": "faqs_Section3",
          "props": {
            "id": "faqs_Section3-13"
          }
        },
        {
          "type": "faqs_Section4",
          "props": {
            "id": "faqs_Section4-14"
          }
        }
      ],
      "zones": {}
    }
  },
  {
    "name": "Home 10",
    "slug": "home-10",
    "sourcePage": "src/pages/Home10Page.tsx",
    "document": {
      "root": {
        "props": {
          "title": "Home 10",
          "headerStyle": 1,
          "footerStyle": 1,
          "noHeader": false,
          "noFooter": false,
          "mainClass": "bg-neutral-0"
        }
      },
      "content": [
        {
          "type": "index_10_Section1",
          "props": {
            "id": "index_10_Section1-15"
          }
        },
        {
          "type": "index_10_Section2",
          "props": {
            "id": "index_10_Section2-16"
          }
        },
        {
          "type": "index_10_Section3",
          "props": {
            "id": "index_10_Section3-17"
          }
        },
        {
          "type": "index_10_Section4",
          "props": {
            "id": "index_10_Section4-18"
          }
        },
        {
          "type": "index_10_Section5",
          "props": {
            "id": "index_10_Section5-19"
          }
        },
        {
          "type": "index_10_Section6",
          "props": {
            "id": "index_10_Section6-1a"
          }
        }
      ],
      "zones": {}
    }
  },
  {
    "name": "Home 11",
    "slug": "home-11",
    "sourcePage": "src/pages/Home11Page.tsx",
    "document": {
      "root": {
        "props": {
          "title": "Home 11",
          "headerStyle": 1,
          "footerStyle": 1,
          "noHeader": false,
          "noFooter": false,
          "mainClass": "bg-neutral-0"
        }
      },
      "content": [
        {
          "type": "index_11_Section1",
          "props": {
            "id": "index_11_Section1-1b"
          }
        },
        {
          "type": "index_11_Section2",
          "props": {
            "id": "index_11_Section2-1c"
          }
        },
        {
          "type": "index_11_Section3",
          "props": {
            "id": "index_11_Section3-1d"
          }
        },
        {
          "type": "index_11_Section4",
          "props": {
            "id": "index_11_Section4-1e"
          }
        },
        {
          "type": "index_11_Section5",
          "props": {
            "id": "index_11_Section5-1f"
          }
        },
        {
          "type": "index_11_Section6",
          "props": {
            "id": "index_11_Section6-1g"
          }
        },
        {
          "type": "index_11_Section7",
          "props": {
            "id": "index_11_Section7-1h"
          }
        },
        {
          "type": "index_11_Section8",
          "props": {
            "id": "index_11_Section8-1i"
          }
        }
      ],
      "zones": {}
    }
  },
  {
    "name": "Home 12",
    "slug": "home-12",
    "sourcePage": "src/pages/Home12Page.tsx",
    "document": {
      "root": {
        "props": {
          "title": "Home 12",
          "headerStyle": 1,
          "footerStyle": 1,
          "noHeader": false,
          "noFooter": false,
          "mainClass": "bg-neutral-0"
        }
      },
      "content": [
        {
          "type": "index_12_Section1",
          "props": {
            "id": "index_12_Section1-1j"
          }
        },
        {
          "type": "index_12_Section2",
          "props": {
            "id": "index_12_Section2-1k"
          }
        },
        {
          "type": "index_12_Section3",
          "props": {
            "id": "index_12_Section3-1l"
          }
        },
        {
          "type": "index_12_Section4",
          "props": {
            "id": "index_12_Section4-1m"
          }
        },
        {
          "type": "index_12_Section5",
          "props": {
            "id": "index_12_Section5-1n"
          }
        },
        {
          "type": "index_12_Section6",
          "props": {
            "id": "index_12_Section6-1o"
          }
        },
        {
          "type": "index_12_Section7",
          "props": {
            "id": "index_12_Section7-1p"
          }
        },
        {
          "type": "index_12_Section8",
          "props": {
            "id": "index_12_Section8-1q"
          }
        }
      ],
      "zones": {}
    }
  },
  {
    "name": "Home 13",
    "slug": "home-13",
    "sourcePage": "src/pages/Home13Page.tsx",
    "document": {
      "root": {
        "props": {
          "title": "Home 13",
          "headerStyle": 1,
          "footerStyle": 1,
          "noHeader": false,
          "noFooter": false,
          "mainClass": "bg-neutral-0"
        }
      },
      "content": [
        {
          "type": "index_13_Section1",
          "props": {
            "id": "index_13_Section1-1r"
          }
        },
        {
          "type": "index_13_SectionTrust",
          "props": {
            "id": "index_13_SectionTrust-1s"
          }
        },
        {
          "type": "index_13_Section2",
          "props": {
            "id": "index_13_Section2-1t"
          }
        },
        {
          "type": "index_13_Section3",
          "props": {
            "id": "index_13_Section3-1u"
          }
        },
        {
          "type": "index_13_Section4",
          "props": {
            "id": "index_13_Section4-1v"
          }
        },
        {
          "type": "index_13_Section5",
          "props": {
            "id": "index_13_Section5-1w"
          }
        },
        {
          "type": "index_13_Section6",
          "props": {
            "id": "index_13_Section6-1x"
          }
        },
        {
          "type": "index_13_SectionCalc",
          "props": {
            "id": "index_13_SectionCalc-1y"
          }
        },
        {
          "type": "index_13_Section7",
          "props": {
            "id": "index_13_Section7-1z"
          }
        },
        {
          "type": "index_13_Section8",
          "props": {
            "id": "index_13_Section8-20"
          }
        },
        {
          "type": "index_13_SectionFaq",
          "props": {
            "id": "index_13_SectionFaq-21"
          }
        }
      ],
      "zones": {}
    }
  },
  {
    "name": "Home 14",
    "slug": "home-14",
    "sourcePage": "src/pages/Home14Page.tsx",
    "document": {
      "root": {
        "props": {
          "title": "Home 14",
          "headerStyle": 1,
          "footerStyle": 1,
          "noHeader": false,
          "noFooter": false,
          "mainClass": "bg-neutral-0"
        }
      },
      "content": [
        {
          "type": "index_14_Section1",
          "props": {
            "id": "index_14_Section1-22"
          }
        },
        {
          "type": "index_14_Section2",
          "props": {
            "id": "index_14_Section2-23"
          }
        },
        {
          "type": "index_14_Section3",
          "props": {
            "id": "index_14_Section3-24"
          }
        },
        {
          "type": "index_14_Section4",
          "props": {
            "id": "index_14_Section4-25"
          }
        },
        {
          "type": "index_14_Section5",
          "props": {
            "id": "index_14_Section5-26"
          }
        },
        {
          "type": "index_14_Section6",
          "props": {
            "id": "index_14_Section6-27"
          }
        },
        {
          "type": "index_14_Section7",
          "props": {
            "id": "index_14_Section7-28"
          }
        },
        {
          "type": "index_14_Section8",
          "props": {
            "id": "index_14_Section8-29"
          }
        },
        {
          "type": "index_14_Section9",
          "props": {
            "id": "index_14_Section9-2a"
          }
        }
      ],
      "zones": {}
    }
  },
  {
    "name": "Home 15",
    "slug": "home-15",
    "sourcePage": "src/pages/Home15Page.tsx",
    "document": {
      "root": {
        "props": {
          "title": "Home 15",
          "headerStyle": 1,
          "footerStyle": 1,
          "noHeader": false,
          "noFooter": false,
          "mainClass": "bg-neutral-0"
        }
      },
      "content": [
        {
          "type": "index_15_Section1",
          "props": {
            "id": "index_15_Section1-2b"
          }
        },
        {
          "type": "index_15_Section2",
          "props": {
            "id": "index_15_Section2-2c"
          }
        },
        {
          "type": "index_15_Section3",
          "props": {
            "id": "index_15_Section3-2d"
          }
        },
        {
          "type": "index_15_Section4",
          "props": {
            "id": "index_15_Section4-2e"
          }
        },
        {
          "type": "index_15_Section5",
          "props": {
            "id": "index_15_Section5-2f"
          }
        },
        {
          "type": "index_15_Section6",
          "props": {
            "id": "index_15_Section6-2g"
          }
        },
        {
          "type": "index_15_Section7",
          "props": {
            "id": "index_15_Section7-2h"
          }
        },
        {
          "type": "index_15_Section8",
          "props": {
            "id": "index_15_Section8-2i"
          }
        },
        {
          "type": "index_15_Section9",
          "props": {
            "id": "index_15_Section9-2j"
          }
        }
      ],
      "zones": {}
    }
  },
  {
    "name": "Home 1",
    "slug": "home-1",
    "sourcePage": "src/pages/Home1Page.tsx",
    "document": {
      "root": {
        "props": {
          "title": "Home 1",
          "headerStyle": 1,
          "footerStyle": 1,
          "noHeader": false,
          "noFooter": false,
          "mainClass": "bg-neutral-0"
        }
      },
      "content": [
        {
          "type": "Home1Hero",
          "props": {
            "id": "Home1Hero-2k"
          }
        },
        {
          "type": "Home1Intro",
          "props": {
            "id": "Home1Intro-2l"
          }
        },
        {
          "type": "index_1_Section3",
          "props": {
            "id": "index_1_Section3-2m"
          }
        },
        {
          "type": "index_1_Section4",
          "props": {
            "id": "index_1_Section4-2n"
          }
        },
        {
          "type": "index_1_Section5",
          "props": {
            "id": "index_1_Section5-2o"
          }
        },
        {
          "type": "Home1Testimonials",
          "props": {
            "id": "Home1Testimonials-2p"
          }
        },
        {
          "type": "index_1_Section7",
          "props": {
            "id": "index_1_Section7-2q"
          }
        },
        {
          "type": "index_1_Section8",
          "props": {
            "id": "index_1_Section8-2r"
          }
        },
        {
          "type": "index_1_Section9",
          "props": {
            "id": "index_1_Section9-2s"
          }
        },
        {
          "type": "index_1_Section10",
          "props": {
            "id": "index_1_Section10-2t"
          }
        },
        {
          "type": "index_1_Section11",
          "props": {
            "id": "index_1_Section11-2u"
          }
        },
        {
          "type": "index_1_Section12",
          "props": {
            "id": "index_1_Section12-2v"
          }
        },
        {
          "type": "index_1_Section13",
          "props": {
            "id": "index_1_Section13-2w"
          }
        }
      ],
      "zones": {}
    }
  },
  {
    "name": "Home 2",
    "slug": "home-2",
    "sourcePage": "src/pages/Home2Page.tsx",
    "document": {
      "root": {
        "props": {
          "title": "Home 2",
          "headerStyle": 1,
          "footerStyle": 1,
          "noHeader": false,
          "noFooter": false,
          "mainClass": "bg-neutral-0"
        }
      },
      "content": [
        {
          "type": "index_2_Section1",
          "props": {
            "id": "index_2_Section1-2x"
          }
        },
        {
          "type": "index_2_Section2",
          "props": {
            "id": "index_2_Section2-2y"
          }
        },
        {
          "type": "index_2_Section3",
          "props": {
            "id": "index_2_Section3-2z"
          }
        },
        {
          "type": "index_2_Section4",
          "props": {
            "id": "index_2_Section4-30"
          }
        },
        {
          "type": "index_2_Section5",
          "props": {
            "id": "index_2_Section5-31"
          }
        },
        {
          "type": "index_2_Section6",
          "props": {
            "id": "index_2_Section6-32"
          }
        },
        {
          "type": "index_2_Section7",
          "props": {
            "id": "index_2_Section7-33"
          }
        },
        {
          "type": "index_2_Section8",
          "props": {
            "id": "index_2_Section8-34"
          }
        },
        {
          "type": "index_2_Section9",
          "props": {
            "id": "index_2_Section9-35"
          }
        },
        {
          "type": "index_2_Section10",
          "props": {
            "id": "index_2_Section10-36"
          }
        },
        {
          "type": "index_2_Section11",
          "props": {
            "id": "index_2_Section11-37"
          }
        },
        {
          "type": "index_2_Section12",
          "props": {
            "id": "index_2_Section12-38"
          }
        },
        {
          "type": "index_2_Section13",
          "props": {
            "id": "index_2_Section13-39"
          }
        }
      ],
      "zones": {}
    }
  },
  {
    "name": "Home 3",
    "slug": "home-3",
    "sourcePage": "src/pages/Home3Page.tsx",
    "document": {
      "root": {
        "props": {
          "title": "Home 3",
          "headerStyle": 1,
          "footerStyle": 1,
          "noHeader": false,
          "noFooter": false,
          "mainClass": "bg-neutral-0"
        }
      },
      "content": [
        {
          "type": "index_3_Section1",
          "props": {
            "id": "index_3_Section1-3a"
          }
        },
        {
          "type": "index_3_Section2",
          "props": {
            "id": "index_3_Section2-3b"
          }
        },
        {
          "type": "index_3_Section3",
          "props": {
            "id": "index_3_Section3-3c"
          }
        },
        {
          "type": "index_3_Section4",
          "props": {
            "id": "index_3_Section4-3d"
          }
        },
        {
          "type": "index_3_Section5",
          "props": {
            "id": "index_3_Section5-3e"
          }
        },
        {
          "type": "index_3_Section6",
          "props": {
            "id": "index_3_Section6-3f"
          }
        },
        {
          "type": "index_3_Section7",
          "props": {
            "id": "index_3_Section7-3g"
          }
        },
        {
          "type": "index_3_Section8",
          "props": {
            "id": "index_3_Section8-3h"
          }
        },
        {
          "type": "TeamIntro1",
          "props": {
            "id": "TeamIntro1-3i"
          }
        },
        {
          "type": "index_3_Section10",
          "props": {
            "id": "index_3_Section10-3j"
          }
        },
        {
          "type": "index_3_Section11",
          "props": {
            "id": "index_3_Section11-3k"
          }
        },
        {
          "type": "index_3_Section12",
          "props": {
            "id": "index_3_Section12-3l"
          }
        }
      ],
      "zones": {}
    }
  },
  {
    "name": "Home 4",
    "slug": "home-4",
    "sourcePage": "src/pages/Home4Page.tsx",
    "document": {
      "root": {
        "props": {
          "title": "Home 4",
          "headerStyle": 1,
          "footerStyle": 1,
          "noHeader": false,
          "noFooter": false,
          "mainClass": "bg-neutral-0"
        }
      },
      "content": [
        {
          "type": "index_4_Section1",
          "props": {
            "id": "index_4_Section1-3m"
          }
        },
        {
          "type": "index_4_Section2",
          "props": {
            "id": "index_4_Section2-3n"
          }
        },
        {
          "type": "index_4_Section3",
          "props": {
            "id": "index_4_Section3-3o"
          }
        },
        {
          "type": "index_4_Section4",
          "props": {
            "id": "index_4_Section4-3p"
          }
        },
        {
          "type": "index_4_Section5",
          "props": {
            "id": "index_4_Section5-3q"
          }
        },
        {
          "type": "index_4_Section6",
          "props": {
            "id": "index_4_Section6-3r"
          }
        },
        {
          "type": "index_4_Section7",
          "props": {
            "id": "index_4_Section7-3s"
          }
        },
        {
          "type": "index_4_Section8",
          "props": {
            "id": "index_4_Section8-3t"
          }
        }
      ],
      "zones": {}
    }
  },
  {
    "name": "Home 5",
    "slug": "home-5",
    "sourcePage": "src/pages/Home5Page.tsx",
    "document": {
      "root": {
        "props": {
          "title": "Home 5",
          "headerStyle": 1,
          "footerStyle": 1,
          "noHeader": false,
          "noFooter": false,
          "mainClass": "bg-neutral-0"
        }
      },
      "content": [
        {
          "type": "index_5_Section1",
          "props": {
            "id": "index_5_Section1-3u"
          }
        },
        {
          "type": "index_5_Section2",
          "props": {
            "id": "index_5_Section2-3v"
          }
        },
        {
          "type": "index_5_Section3",
          "props": {
            "id": "index_5_Section3-3w"
          }
        },
        {
          "type": "index_5_Section4",
          "props": {
            "id": "index_5_Section4-3x"
          }
        },
        {
          "type": "index_5_Section5",
          "props": {
            "id": "index_5_Section5-3y"
          }
        },
        {
          "type": "index_5_Section6",
          "props": {
            "id": "index_5_Section6-3z"
          }
        },
        {
          "type": "index_5_Section7",
          "props": {
            "id": "index_5_Section7-40"
          }
        },
        {
          "type": "index_5_Section8",
          "props": {
            "id": "index_5_Section8-41"
          }
        }
      ],
      "zones": {}
    }
  },
  {
    "name": "Home 6",
    "slug": "home-6",
    "sourcePage": "src/pages/Home6Page.tsx",
    "document": {
      "root": {
        "props": {
          "title": "Home 6",
          "headerStyle": 1,
          "footerStyle": 1,
          "noHeader": false,
          "noFooter": false,
          "mainClass": "bg-neutral-0"
        }
      },
      "content": [
        {
          "type": "index_6_Section1",
          "props": {
            "id": "index_6_Section1-42"
          }
        },
        {
          "type": "index_6_Section2",
          "props": {
            "id": "index_6_Section2-43"
          }
        },
        {
          "type": "index_6_Section3",
          "props": {
            "id": "index_6_Section3-44"
          }
        },
        {
          "type": "index_6_Section4",
          "props": {
            "id": "index_6_Section4-45"
          }
        },
        {
          "type": "index_6_Section5",
          "props": {
            "id": "index_6_Section5-46"
          }
        },
        {
          "type": "index_6_Section6",
          "props": {
            "id": "index_6_Section6-47"
          }
        },
        {
          "type": "index_6_Section7",
          "props": {
            "id": "index_6_Section7-48"
          }
        },
        {
          "type": "index_6_Section8",
          "props": {
            "id": "index_6_Section8-49"
          }
        },
        {
          "type": "index_6_Section9",
          "props": {
            "id": "index_6_Section9-4a"
          }
        }
      ],
      "zones": {}
    }
  },
  {
    "name": "Home 7",
    "slug": "home-7",
    "sourcePage": "src/pages/Home7Page.tsx",
    "document": {
      "root": {
        "props": {
          "title": "Home 7",
          "headerStyle": 1,
          "footerStyle": 1,
          "noHeader": false,
          "noFooter": false,
          "mainClass": "bg-neutral-0"
        }
      },
      "content": [
        {
          "type": "index_7_Section1",
          "props": {
            "id": "index_7_Section1-4b"
          }
        },
        {
          "type": "index_7_Section2",
          "props": {
            "id": "index_7_Section2-4c"
          }
        },
        {
          "type": "index_7_Section3",
          "props": {
            "id": "index_7_Section3-4d"
          }
        },
        {
          "type": "index_7_Section4",
          "props": {
            "id": "index_7_Section4-4e"
          }
        },
        {
          "type": "index_7_Section5",
          "props": {
            "id": "index_7_Section5-4f"
          }
        },
        {
          "type": "index_7_Section6",
          "props": {
            "id": "index_7_Section6-4g"
          }
        },
        {
          "type": "index_7_Section7",
          "props": {
            "id": "index_7_Section7-4h"
          }
        },
        {
          "type": "index_7_Section8",
          "props": {
            "id": "index_7_Section8-4i"
          }
        },
        {
          "type": "index_7_Section9",
          "props": {
            "id": "index_7_Section9-4j"
          }
        },
        {
          "type": "index_7_Section10",
          "props": {
            "id": "index_7_Section10-4k"
          }
        },
        {
          "type": "index_7_Section11",
          "props": {
            "id": "index_7_Section11-4l"
          }
        }
      ],
      "zones": {}
    }
  },
  {
    "name": "Home 8",
    "slug": "home-8",
    "sourcePage": "src/pages/Home8Page.tsx",
    "document": {
      "root": {
        "props": {
          "title": "Home 8",
          "headerStyle": 1,
          "footerStyle": 1,
          "noHeader": false,
          "noFooter": false,
          "mainClass": "bg-neutral-0"
        }
      },
      "content": [
        {
          "type": "index_8_Section1",
          "props": {
            "id": "index_8_Section1-4m"
          }
        },
        {
          "type": "index_8_Section2",
          "props": {
            "id": "index_8_Section2-4n"
          }
        },
        {
          "type": "index_8_Section3",
          "props": {
            "id": "index_8_Section3-4o"
          }
        },
        {
          "type": "index_8_Section4",
          "props": {
            "id": "index_8_Section4-4p"
          }
        },
        {
          "type": "index_8_Section5",
          "props": {
            "id": "index_8_Section5-4q"
          }
        },
        {
          "type": "index_8_Section6",
          "props": {
            "id": "index_8_Section6-4r"
          }
        },
        {
          "type": "index_8_Section7",
          "props": {
            "id": "index_8_Section7-4s"
          }
        },
        {
          "type": "index_8_Section8",
          "props": {
            "id": "index_8_Section8-4t"
          }
        },
        {
          "type": "index_8_Section9",
          "props": {
            "id": "index_8_Section9-4u"
          }
        },
        {
          "type": "index_8_Section10",
          "props": {
            "id": "index_8_Section10-4v"
          }
        }
      ],
      "zones": {}
    }
  },
  {
    "name": "Home 9",
    "slug": "home-9",
    "sourcePage": "src/pages/Home9Page.tsx",
    "document": {
      "root": {
        "props": {
          "title": "Home 9",
          "headerStyle": 1,
          "footerStyle": 1,
          "noHeader": false,
          "noFooter": false,
          "mainClass": "bg-neutral-0"
        }
      },
      "content": [
        {
          "type": "index_9_Section1",
          "props": {
            "id": "index_9_Section1-4w"
          }
        },
        {
          "type": "index_9_Section2",
          "props": {
            "id": "index_9_Section2-4x"
          }
        },
        {
          "type": "index_9_Section3",
          "props": {
            "id": "index_9_Section3-4y"
          }
        },
        {
          "type": "index_9_Section4",
          "props": {
            "id": "index_9_Section4-4z"
          }
        },
        {
          "type": "index_9_Section5",
          "props": {
            "id": "index_9_Section5-50"
          }
        },
        {
          "type": "index_9_Section6",
          "props": {
            "id": "index_9_Section6-51"
          }
        },
        {
          "type": "index_9_Section7",
          "props": {
            "id": "index_9_Section7-52"
          }
        },
        {
          "type": "index_9_Section8",
          "props": {
            "id": "index_9_Section8-53"
          }
        },
        {
          "type": "index_9_Section9",
          "props": {
            "id": "index_9_Section9-54"
          }
        },
        {
          "type": "index_9_Section10",
          "props": {
            "id": "index_9_Section10-55"
          }
        }
      ],
      "zones": {}
    }
  },
  {
    "name": "Portfolio 1",
    "slug": "portfolio-1",
    "sourcePage": "src/pages/Portfolio1Page.tsx",
    "document": {
      "root": {
        "props": {
          "title": "Portfolio 1",
          "headerStyle": 1,
          "footerStyle": 1,
          "noHeader": false,
          "noFooter": false,
          "mainClass": "bg-neutral-0"
        }
      },
      "content": [
        {
          "type": "portfolio_1_Section1",
          "props": {
            "id": "portfolio_1_Section1-56"
          }
        },
        {
          "type": "about_3_Section7",
          "props": {
            "id": "about_3_Section7-57"
          }
        }
      ],
      "zones": {}
    }
  },
  {
    "name": "Portfolio 2",
    "slug": "portfolio-2",
    "sourcePage": "src/pages/Portfolio2Page.tsx",
    "document": {
      "root": {
        "props": {
          "title": "Portfolio 2",
          "headerStyle": 1,
          "footerStyle": 1,
          "noHeader": false,
          "noFooter": false,
          "mainClass": "bg-neutral-0"
        }
      },
      "content": [
        {
          "type": "portfolio_2_Section1",
          "props": {
            "id": "portfolio_2_Section1-58"
          }
        },
        {
          "type": "about_3_Section7",
          "props": {
            "id": "about_3_Section7-59"
          }
        }
      ],
      "zones": {}
    }
  },
  {
    "name": "Portfolio 3",
    "slug": "portfolio-3",
    "sourcePage": "src/pages/Portfolio3Page.tsx",
    "document": {
      "root": {
        "props": {
          "title": "Portfolio 3",
          "headerStyle": 1,
          "footerStyle": 1,
          "noHeader": false,
          "noFooter": false,
          "mainClass": "bg-neutral-0"
        }
      },
      "content": [
        {
          "type": "portfolio_3_Section1",
          "props": {
            "id": "portfolio_3_Section1-5a"
          }
        },
        {
          "type": "about_3_Section7",
          "props": {
            "id": "about_3_Section7-5b"
          }
        }
      ],
      "zones": {}
    }
  },
  {
    "name": "Portfolio 4",
    "slug": "portfolio-4",
    "sourcePage": "src/pages/Portfolio4Page.tsx",
    "document": {
      "root": {
        "props": {
          "title": "Portfolio 4",
          "headerStyle": 1,
          "footerStyle": 1,
          "noHeader": false,
          "noFooter": false,
          "mainClass": "bg-neutral-0"
        }
      },
      "content": [
        {
          "type": "portfolio_4_Section1",
          "props": {
            "id": "portfolio_4_Section1-5c"
          }
        },
        {
          "type": "about_3_Section7",
          "props": {
            "id": "about_3_Section7-5d"
          }
        }
      ],
      "zones": {}
    }
  },
  {
    "name": "Portfolio 5",
    "slug": "portfolio-5",
    "sourcePage": "src/pages/Portfolio5Page.tsx",
    "document": {
      "root": {
        "props": {
          "title": "Portfolio 5",
          "headerStyle": 1,
          "footerStyle": 1,
          "noHeader": false,
          "noFooter": false,
          "mainClass": "bg-neutral-0"
        }
      },
      "content": [
        {
          "type": "portfolio_5_Section1",
          "props": {
            "id": "portfolio_5_Section1-5e"
          }
        },
        {
          "type": "about_3_Section7",
          "props": {
            "id": "about_3_Section7-5f"
          }
        }
      ],
      "zones": {}
    }
  },
  {
    "name": "Portfolio 6",
    "slug": "portfolio-6",
    "sourcePage": "src/pages/Portfolio6Page.tsx",
    "document": {
      "root": {
        "props": {
          "title": "Portfolio 6",
          "headerStyle": 1,
          "footerStyle": 1,
          "noHeader": false,
          "noFooter": false,
          "mainClass": "bg-neutral-0"
        }
      },
      "content": [
        {
          "type": "portfolio_6_Section1",
          "props": {
            "id": "portfolio_6_Section1-5g"
          }
        },
        {
          "type": "about_3_Section7",
          "props": {
            "id": "about_3_Section7-5h"
          }
        }
      ],
      "zones": {}
    }
  },
  {
    "name": "Portfolio Details 1",
    "slug": "portfolio-details-1",
    "sourcePage": "src/pages/PortfolioDetails1Page.tsx",
    "document": {
      "root": {
        "props": {
          "title": "Portfolio Details 1",
          "headerStyle": 1,
          "footerStyle": 1,
          "noHeader": false,
          "noFooter": false,
          "mainClass": "bg-neutral-0"
        }
      },
      "content": [
        {
          "type": "portfolio_details_1_Section1",
          "props": {
            "id": "portfolio_details_1_Section1-5i"
          }
        },
        {
          "type": "portfolio_details_1_Section2",
          "props": {
            "id": "portfolio_details_1_Section2-5j"
          }
        }
      ],
      "zones": {}
    }
  },
  {
    "name": "Portfolio Details 2",
    "slug": "portfolio-details-2",
    "sourcePage": "src/pages/PortfolioDetails2Page.tsx",
    "document": {
      "root": {
        "props": {
          "title": "Portfolio Details 2",
          "headerStyle": 1,
          "footerStyle": 1,
          "noHeader": false,
          "noFooter": false,
          "mainClass": "bg-neutral-0"
        }
      },
      "content": [
        {
          "type": "portfolio_details_2_Section1",
          "props": {
            "id": "portfolio_details_2_Section1-5k"
          }
        },
        {
          "type": "portfolio_details_1_Section2",
          "props": {
            "id": "portfolio_details_1_Section2-5l"
          }
        }
      ],
      "zones": {}
    }
  },
  {
    "name": "Portfolio Details 3",
    "slug": "portfolio-details-3",
    "sourcePage": "src/pages/PortfolioDetails3Page.tsx",
    "document": {
      "root": {
        "props": {
          "title": "Portfolio Details 3",
          "headerStyle": 1,
          "footerStyle": 1,
          "noHeader": false,
          "noFooter": false,
          "mainClass": "bg-neutral-0"
        }
      },
      "content": [
        {
          "type": "portfolio_details_3_Section1",
          "props": {
            "id": "portfolio_details_3_Section1-5m"
          }
        },
        {
          "type": "portfolio_details_3_Section2",
          "props": {
            "id": "portfolio_details_3_Section2-5n"
          }
        },
        {
          "type": "portfolio_details_3_Section3",
          "props": {
            "id": "portfolio_details_3_Section3-5o"
          }
        },
        {
          "type": "portfolio_details_3_Section4",
          "props": {
            "id": "portfolio_details_3_Section4-5p"
          }
        },
        {
          "type": "portfolio_details_3_Section5",
          "props": {
            "id": "portfolio_details_3_Section5-5q"
          }
        },
        {
          "type": "portfolio_details_3_Section6",
          "props": {
            "id": "portfolio_details_3_Section6-5r"
          }
        },
        {
          "type": "portfolio_details_3_Section7",
          "props": {
            "id": "portfolio_details_3_Section7-5s"
          }
        },
        {
          "type": "portfolio_details_3_Section8",
          "props": {
            "id": "portfolio_details_3_Section8-5t"
          }
        }
      ],
      "zones": {}
    }
  },
  {
    "name": "Portfolio Details 4",
    "slug": "portfolio-details-4",
    "sourcePage": "src/pages/PortfolioDetails4Page.tsx",
    "document": {
      "root": {
        "props": {
          "title": "Portfolio Details 4",
          "headerStyle": 1,
          "footerStyle": 1,
          "noHeader": false,
          "noFooter": false,
          "mainClass": "bg-neutral-0"
        }
      },
      "content": [
        {
          "type": "portfolio_details_4_Section1",
          "props": {
            "id": "portfolio_details_4_Section1-5u"
          }
        },
        {
          "type": "portfolio_details_3_Section2",
          "props": {
            "id": "portfolio_details_3_Section2-5v"
          }
        },
        {
          "type": "portfolio_details_3_Section3",
          "props": {
            "id": "portfolio_details_3_Section3-5w"
          }
        },
        {
          "type": "portfolio_details_3_Section5",
          "props": {
            "id": "portfolio_details_3_Section5-5x"
          }
        },
        {
          "type": "portfolio_details_3_Section7",
          "props": {
            "id": "portfolio_details_3_Section7-5y"
          }
        }
      ],
      "zones": {}
    }
  },
  {
    "name": "Portfolio Details 5",
    "slug": "portfolio-details-5",
    "sourcePage": "src/pages/PortfolioDetails5Page.tsx",
    "document": {
      "root": {
        "props": {
          "title": "Portfolio Details 5",
          "headerStyle": 1,
          "footerStyle": 1,
          "noHeader": false,
          "noFooter": false,
          "mainClass": "bg-neutral-0"
        }
      },
      "content": [
        {
          "type": "portfolio_details_5_Section1",
          "props": {
            "id": "portfolio_details_5_Section1-5z"
          }
        },
        {
          "type": "portfolio_details_3_Section2",
          "props": {
            "id": "portfolio_details_3_Section2-60"
          }
        },
        {
          "type": "portfolio_details_3_Section3",
          "props": {
            "id": "portfolio_details_3_Section3-61"
          }
        },
        {
          "type": "portfolio_details_3_Section4",
          "props": {
            "id": "portfolio_details_3_Section4-62"
          }
        },
        {
          "type": "portfolio_details_3_Section5",
          "props": {
            "id": "portfolio_details_3_Section5-63"
          }
        },
        {
          "type": "portfolio_details_3_Section6",
          "props": {
            "id": "portfolio_details_3_Section6-64"
          }
        },
        {
          "type": "portfolio_details_3_Section8",
          "props": {
            "id": "portfolio_details_3_Section8-65"
          }
        }
      ],
      "zones": {}
    }
  },
  {
    "name": "Portfolio Details 6",
    "slug": "portfolio-details-6",
    "sourcePage": "src/pages/PortfolioDetails6Page.tsx",
    "document": {
      "root": {
        "props": {
          "title": "Portfolio Details 6",
          "headerStyle": 1,
          "footerStyle": 1,
          "noHeader": false,
          "noFooter": false,
          "mainClass": "bg-neutral-0"
        }
      },
      "content": [
        {
          "type": "portfolio_details_6_Section1",
          "props": {
            "id": "portfolio_details_6_Section1-66"
          }
        },
        {
          "type": "portfolio_details_3_Section2",
          "props": {
            "id": "portfolio_details_3_Section2-67"
          }
        },
        {
          "type": "portfolio_details_3_Section3",
          "props": {
            "id": "portfolio_details_3_Section3-68"
          }
        },
        {
          "type": "portfolio_details_3_Section4",
          "props": {
            "id": "portfolio_details_3_Section4-69"
          }
        },
        {
          "type": "portfolio_details_3_Section5",
          "props": {
            "id": "portfolio_details_3_Section5-6a"
          }
        },
        {
          "type": "portfolio_details_3_Section6",
          "props": {
            "id": "portfolio_details_3_Section6-6b"
          }
        },
        {
          "type": "portfolio_details_3_Section8",
          "props": {
            "id": "portfolio_details_3_Section8-6c"
          }
        }
      ],
      "zones": {}
    }
  },
  {
    "name": "Pricing",
    "slug": "pricing",
    "sourcePage": "src/pages/PricingPage.tsx",
    "document": {
      "root": {
        "props": {
          "title": "Pricing",
          "headerStyle": 1,
          "footerStyle": 1,
          "noHeader": false,
          "noFooter": false,
          "mainClass": "bg-neutral-0"
        }
      },
      "content": [
        {
          "type": "index_2_Section12",
          "props": {
            "id": "index_2_Section12-6d"
          }
        },
        {
          "type": "services_details_Section4",
          "props": {
            "id": "services_details_Section4-6e"
          }
        },
        {
          "type": "about_3_Section7",
          "props": {
            "id": "about_3_Section7-6f"
          }
        }
      ],
      "zones": {}
    }
  },
  {
    "name": "Product Archive",
    "slug": "product-archive",
    "sourcePage": "src/pages/ProductArchivePage.tsx",
    "document": {
      "root": {
        "props": {
          "title": "Product Archive",
          "headerStyle": 1,
          "footerStyle": 1,
          "noHeader": false,
          "noFooter": false,
          "mainClass": "bg-neutral-0"
        }
      },
      "content": [
        {
          "type": "product_Section1",
          "props": {
            "id": "product_Section1-6g"
          }
        },
        {
          "type": "product_Section2",
          "props": {
            "id": "product_Section2-6h"
          }
        },
        {
          "type": "product_Section3",
          "props": {
            "id": "product_Section3-6i"
          }
        },
        {
          "type": "product_Section4",
          "props": {
            "id": "product_Section4-6j"
          }
        },
        {
          "type": "index_5_Section8",
          "props": {
            "id": "index_5_Section8-6k"
          }
        }
      ],
      "zones": {}
    }
  },
  {
    "name": "Product Cart",
    "slug": "product-cart",
    "sourcePage": "src/pages/ProductCartPage.tsx",
    "document": {
      "root": {
        "props": {
          "title": "Product Cart",
          "headerStyle": 1,
          "footerStyle": 1,
          "noHeader": false,
          "noFooter": false,
          "mainClass": "bg-neutral-0"
        }
      },
      "content": [
        {
          "type": "product_cart_Section1",
          "props": {
            "id": "product_cart_Section1-6l"
          }
        },
        {
          "type": "product_cart_Section2",
          "props": {
            "id": "product_cart_Section2-6m"
          }
        }
      ],
      "zones": {}
    }
  },
  {
    "name": "Product Checkout",
    "slug": "product-checkout",
    "sourcePage": "src/pages/ProductCheckoutPage.tsx",
    "document": {
      "root": {
        "props": {
          "title": "Product Checkout",
          "headerStyle": 1,
          "footerStyle": 1,
          "noHeader": false,
          "noFooter": false,
          "mainClass": "bg-neutral-0"
        }
      },
      "content": [
        {
          "type": "product_checkout_Section1",
          "props": {
            "id": "product_checkout_Section1-6n"
          }
        },
        {
          "type": "product_cart_Section2",
          "props": {
            "id": "product_cart_Section2-6o"
          }
        }
      ],
      "zones": {}
    }
  },
  {
    "name": "Product Details",
    "slug": "product-details",
    "sourcePage": "src/pages/ProductDetailsPage.tsx",
    "document": {
      "root": {
        "props": {
          "title": "Product Details",
          "headerStyle": 1,
          "footerStyle": 1,
          "noHeader": false,
          "noFooter": false,
          "mainClass": "bg-neutral-0"
        }
      },
      "content": [
        {
          "type": "product_details_Section1",
          "props": {
            "id": "product_details_Section1-6p"
          }
        },
        {
          "type": "product_Section3",
          "props": {
            "id": "product_Section3-6q"
          }
        },
        {
          "type": "product_details_Section2",
          "props": {
            "id": "product_details_Section2-6r"
          }
        },
        {
          "type": "product_details_Section3",
          "props": {
            "id": "product_details_Section3-6s"
          }
        }
      ],
      "zones": {}
    }
  },
  {
    "name": "Services 1",
    "slug": "services-1",
    "sourcePage": "src/pages/Services1Page.tsx",
    "document": {
      "root": {
        "props": {
          "title": "Services 1",
          "headerStyle": 1,
          "footerStyle": 1,
          "noHeader": false,
          "noFooter": false,
          "mainClass": "bg-neutral-0"
        }
      },
      "content": [
        {
          "type": "ServicesIntro",
          "props": {
            "id": "ServicesIntro-6t"
          }
        },
        {
          "type": "index_1_Section4",
          "props": {
            "id": "index_1_Section4-6u"
          }
        },
        {
          "type": "about_3_Section5",
          "props": {
            "id": "about_3_Section5-6v"
          }
        },
        {
          "type": "index_2_Section12",
          "props": {
            "id": "index_2_Section12-6w"
          }
        },
        {
          "type": "index_1_Section11",
          "props": {
            "id": "index_1_Section11-6x"
          }
        },
        {
          "type": "about_1_Section4",
          "props": {
            "id": "about_1_Section4-6y"
          }
        }
      ],
      "zones": {}
    }
  },
  {
    "name": "Services 2",
    "slug": "services-2",
    "sourcePage": "src/pages/Services2Page.tsx",
    "document": {
      "root": {
        "props": {
          "title": "Services 2",
          "headerStyle": 1,
          "footerStyle": 1,
          "noHeader": false,
          "noFooter": false,
          "mainClass": "bg-neutral-0"
        }
      },
      "content": [
        {
          "type": "services_2_Section1",
          "props": {
            "id": "services_2_Section1-6z"
          }
        },
        {
          "type": "services_2_Section2",
          "props": {
            "id": "services_2_Section2-70"
          }
        },
        {
          "type": "index_2_Section4",
          "props": {
            "id": "index_2_Section4-71"
          }
        },
        {
          "type": "about_3_Section3",
          "props": {
            "id": "about_3_Section3-72"
          }
        },
        {
          "type": "services_2_Section3",
          "props": {
            "id": "services_2_Section3-73"
          }
        }
      ],
      "zones": {}
    }
  },
  {
    "name": "Services 3",
    "slug": "services-3",
    "sourcePage": "src/pages/Services3Page.tsx",
    "document": {
      "root": {
        "props": {
          "title": "Services 3",
          "headerStyle": 1,
          "footerStyle": 1,
          "noHeader": false,
          "noFooter": false,
          "mainClass": "bg-neutral-0"
        }
      },
      "content": [
        {
          "type": "services_3_Section1",
          "props": {
            "id": "services_3_Section1-74"
          }
        },
        {
          "type": "services_3_Section2",
          "props": {
            "id": "services_3_Section2-75"
          }
        },
        {
          "type": "about_3_Section2",
          "props": {
            "id": "about_3_Section2-76"
          }
        },
        {
          "type": "index_2_Section9",
          "props": {
            "id": "index_2_Section9-77"
          }
        },
        {
          "type": "index_2_Section8",
          "props": {
            "id": "index_2_Section8-78"
          }
        },
        {
          "type": "about_3_Section7",
          "props": {
            "id": "about_3_Section7-79"
          }
        }
      ],
      "zones": {}
    }
  },
  {
    "name": "Services Details",
    "slug": "services-details",
    "sourcePage": "src/pages/ServicesDetailsPage.tsx",
    "document": {
      "root": {
        "props": {
          "title": "Services Details",
          "headerStyle": 1,
          "footerStyle": 1,
          "noHeader": false,
          "noFooter": false,
          "mainClass": "bg-neutral-0"
        }
      },
      "content": [
        {
          "type": "services_details_Section1",
          "props": {
            "id": "services_details_Section1-7a"
          }
        },
        {
          "type": "services_details_Section2",
          "props": {
            "id": "services_details_Section2-7b"
          }
        },
        {
          "type": "services_details_Section3",
          "props": {
            "id": "services_details_Section3-7c"
          }
        },
        {
          "type": "services_details_Section4",
          "props": {
            "id": "services_details_Section4-7d"
          }
        },
        {
          "type": "services_details_Section5",
          "props": {
            "id": "services_details_Section5-7e"
          }
        },
        {
          "type": "index_3_Section12",
          "props": {
            "id": "index_3_Section12-7f"
          }
        }
      ],
      "zones": {}
    }
  },
  {
    "name": "Team Details",
    "slug": "team-details",
    "sourcePage": "src/pages/TeamDetailsPage.tsx",
    "document": {
      "root": {
        "props": {
          "title": "Team Details",
          "headerStyle": 1,
          "footerStyle": 1,
          "noHeader": false,
          "noFooter": false,
          "mainClass": "bg-neutral-0"
        }
      },
      "content": [
        {
          "type": "team_details_Section_1",
          "props": {
            "id": "team_details_Section_1-7g"
          }
        },
        {
          "type": "team_details_Section_2",
          "props": {
            "id": "team_details_Section_2-7h"
          }
        }
      ],
      "zones": {}
    }
  },
  {
    "name": "Team",
    "slug": "team",
    "sourcePage": "src/pages/TeamPage.tsx",
    "document": {
      "root": {
        "props": {
          "title": "Team",
          "headerStyle": 1,
          "footerStyle": 1,
          "noHeader": false,
          "noFooter": false,
          "mainClass": "bg-neutral-0"
        }
      },
      "content": [
        {
          "type": "ServicesIntro",
          "props": {
            "id": "ServicesIntro-7i"
          }
        },
        {
          "type": "TeamIntro1",
          "props": {
            "id": "TeamIntro1-7j"
          }
        },
        {
          "type": "index_5_Section7",
          "props": {
            "id": "index_5_Section7-7k"
          }
        }
      ],
      "zones": {}
    }
  }
]) as unknown as PageTemplate[];
