-- Phoxta — 0096: knowledge the business writes for itself.
--
-- Uploading a knowledge base by hand is the thing nobody keeps doing. It is
-- accurate the week it is written and quietly wrong six months later, which is
-- how the platform agent ended up reciting ten blueprints when five existed.
--
-- So the agent builds its own, from what the app actually contains — profile,
-- published pages, live catalogue — and refreshes when that changes. Manual
-- docs stay: an owner can still write something no data implies ("we never
-- discount in December"), and the builder must never overwrite it.
--
-- THE LINE THAT MATTERS: auto docs describe POSITIONING and HOW THINGS WORK,
-- never countable facts. A generated paragraph saying "we offer five blueprints
-- from $499" is wrong the moment a sixth is added — the same staleness one level
-- up. Counts, prices and availability come from tools (list_blueprints,
-- list_products), which are true at the moment they are asked.

alter table knowledge_docs
  add column if not exists origin text not null default 'manual'
  check (origin in ('manual', 'auto'));

-- Stable identity for a generated doc, so a refresh replaces it instead of
-- appending a near-duplicate every run.
alter table knowledge_docs add column if not exists source_key text not null default '';

-- Hash of the inputs the doc was built from. Unchanged inputs mean no model
-- call: the builder can run every hour and cost nothing on a quiet day.
alter table knowledge_docs add column if not exists source_hash text not null default '';

alter table knowledge_docs add column if not exists built_at timestamptz;

create unique index if not exists idx_knowledge_docs_source
  on knowledge_docs(organization_id, source_key)
  where source_key <> '';

comment on column knowledge_docs.origin is
  'manual = written by the owner and never touched by the builder. '
  'auto = generated by knowledge-build and replaced on refresh.';

-- Upsert one generated doc. security definer because the builder runs as a
-- background job; it refuses to touch a manual doc even if the keys collide,
-- so an owner can never lose what they wrote.
create or replace function public.app_knowledge_autosave(
  p_org uuid,
  p_key text,
  p_title text,
  p_content text,
  p_hash text
)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  v_existing record;
begin
  select id, origin into v_existing
  from knowledge_docs
  where organization_id = p_org and source_key = p_key;

  if found and v_existing.origin = 'manual' then
    return jsonb_build_object('ok', false, 'skipped', 'manual doc owns this key');
  end if;

  if found then
    update knowledge_docs
    set title = p_title, content = p_content, source_hash = p_hash, built_at = now()
    where id = v_existing.id;
  else
    insert into knowledge_docs (organization_id, title, content, origin, source_key, source_hash, built_at, visibility)
    values (p_org, p_title, p_content, 'auto', p_key, p_hash, now(), 'public');
  end if;

  return jsonb_build_object('ok', true);
end $$;
revoke all on function public.app_knowledge_autosave(uuid, text, text, text, text) from public, anon, authenticated;
grant execute on function public.app_knowledge_autosave(uuid, text, text, text, text) to service_role;

-- What the builder needs to decide whether anything changed, without pulling
-- whole tables across the wire.
create or replace function public.app_knowledge_sources(p_org uuid)
returns jsonb language sql stable security definer set search_path = public as $$
  select jsonb_build_object(
    'org', (select jsonb_build_object('name', o.name, 'vertical', o.vertical, 'profile', o.profile)
              from organizations o where o.id = p_org),
    'pages', coalesce((select jsonb_agg(jsonb_build_object('title', c.title, 'body', left(c.body, 4000)) order by c.title)
              from cms_pages c where c.organization_id = p_org and c.status = 'published'), '[]'::jsonb),
    'products', coalesce((select jsonb_agg(jsonb_build_object('name', p.name, 'description', left(p.description, 600)) order by p.name)
              from products p where p.organization_id = p_org and p.status = 'active'), '[]'::jsonb),
    -- Only the platform sells blueprints; including them for a tenant would put
    -- the marketplace catalogue in a car dealer's knowledge base.
    'blueprints', case when (select lower(coalesce(o.vertical, '')) from organizations o where o.id = p_org) = 'platform'
      then coalesce((select jsonb_agg(jsonb_build_object('name', b.name, 'tagline', b.tagline, 'vertical', b.vertical) order by b.name)
              from blueprints b where b.status = 'live'), '[]'::jsonb)
      else '[]'::jsonb end,
    'existing', coalesce((select jsonb_agg(jsonb_build_object('key', k.source_key, 'hash', k.source_hash))
              from knowledge_docs k where k.organization_id = p_org and k.origin = 'auto'), '[]'::jsonb)
  );
$$;
revoke all on function public.app_knowledge_sources(uuid) from public, anon, authenticated;
grant execute on function public.app_knowledge_sources(uuid) to service_role;
