-- Generated from the shared Phoxta 2.0 curriculum. Do not edit lesson text here.
-- Defines an explicit activation function. Does not silently replace production courses.
begin;
create table public.ss_curriculum_archives(organization_id uuid not null references organizations(id),version text not null,catalogue jsonb not null,archived_at timestamptz not null default now(),primary key(organization_id,version));
alter table public.ss_curriculum_archives enable row level security;
revoke all on public.ss_curriculum_archives from anon,authenticated;
create function public.ss_activate_opportunity_curriculum(p_org uuid,p_confirmed boolean default false) returns jsonb language plpgsql security definer set search_path=public as $school$
declare v_preview jsonb;begin
if not app_is_platform_admin() then raise exception 'Platform administrator required.'; end if;
v_preview:=ss_opportunity_migration_preview(p_org);
if not p_confirmed then return v_preview; end if;
if not exists(select 1 from organizations where id=p_org and (slug='startup-school' or vertical='startup-school' or app_path='businesses/startup-school')) then raise exception 'Select a Startup School tenant.'; end if;
insert into ss_curriculum_archives(organization_id,version,catalogue) select p_org,'pre-phoxta-2.0',jsonb_build_object('courses',(select jsonb_agg(to_jsonb(c)) from cs_courses c where organization_id=p_org),'modules',(select jsonb_agg(to_jsonb(m)) from cs_modules m where organization_id=p_org),'lessons',(select jsonb_agg(to_jsonb(l)) from cs_lessons l where organization_id=p_org)) on conflict do nothing;
update cs_courses set published=false where organization_id=p_org and id not like 'v2-%';
insert into cs_mentors(organization_id,id,name,role,bio,hue,handle,followers,expertise) values(p_org,'m-phoxta-curriculum','Phoxta Startup School','Curriculum','Opportunity discovery and venture creation.','mint','phoxta',0,array['start','fund','grow']) on conflict(organization_id,id) do nothing;
insert into cs_categories(organization_id,id,name,blurb,sort) values(p_org,'start','Discover & Investigate','Find the customer, problem, alternatives and timing.',0) on conflict(organization_id,id) do update set name=excluded.name,blurb=excluded.blurb;
insert into cs_categories(organization_id,id,name,blurb,sort) values(p_org,'fund','Validate & Shape','Test what must be true and design the business.',1) on conflict(organization_id,id) do update set name=excluded.name,blurb=excluded.blurb;
insert into cs_categories(organization_id,id,name,blurb,sort) values(p_org,'grow','Build, Launch & Learn','Deliver value, reach customers and review the evidence.',2) on conflict(organization_id,id) do update set name=excluded.name,blurb=excluded.blurb;
insert into cs_courses(organization_id,id,slug,title,blurb,description,category_id,mentor_id,level,theme,rating,learners,outcomes,final_project_title,final_project_description,published_at,published) values(p_org,'v2-opportunity-thinking','opportunity-thinking','Opportunity Thinking','Understand the difference between an idea, problem, trend and opportunity.','Understand the difference between an idea, problem, trend and opportunity. Produce your Opportunity thesis in a live opportunity workspace.','start','m-phoxta-curriculum','Beginner','start',0,0,'["Understand the difference between an idea, problem, trend and opportunity.","Create: Opportunity thesis"]'::jsonb,'Opportunity thesis','Write a two-to-four-sentence thesis naming the customer, problem, current alternative and why the opportunity may matter. Label it as inferred until you can link real evidence.','2026-09-26T00:00:00.000Z',true) on conflict(organization_id,id) do update set title=excluded.title,description=excluded.description,outcomes=excluded.outcomes,published=true;
insert into cs_courses(organization_id,id,slug,title,blurb,description,category_id,mentor_id,level,theme,rating,learners,outcomes,final_project_title,final_project_description,published_at,published) values(p_org,'v2-finding-problems','finding-problems','Finding Problems Worth Investigating','Observe jobs, pain, friction and workarounds.','Observe jobs, pain, friction and workarounds. Produce your Problem evidence log in a live opportunity workspace.','start','m-phoxta-curriculum','Beginner','start',0,0,'["Observe jobs, pain, friction and workarounds.","Create: Problem evidence log"]'::jsonb,'Problem evidence log','Record one real observation or sourced problem signal. Include its date and context, then state what it does and does not support.','2026-09-26T00:00:00.000Z',true) on conflict(organization_id,id) do update set title=excluded.title,description=excluded.description,outcomes=excluded.outcomes,published=true;
insert into cs_courses(organization_id,id,slug,title,blurb,description,category_id,mentor_id,level,theme,rating,learners,outcomes,final_project_title,final_project_description,published_at,published) values(p_org,'v2-customers-context','customers-context','Customers & Context','Define who experiences the problem and when.','Define who experiences the problem and when. Produce your ICP + context map in a live opportunity workspace.','start','m-phoxta-curriculum','Beginner','start',0,0,'["Define who experiences the problem and when.","Create: ICP + context map"]'::jsonb,'ICP + context map','Create an ideal customer profile with the user, buyer, job, context, trigger and route to a real conversation. Mark unsupported attributes as assumptions.','2026-09-26T00:00:00.000Z',true) on conflict(organization_id,id) do update set title=excluded.title,description=excluded.description,outcomes=excluded.outcomes,published=true;
insert into cs_courses(organization_id,id,slug,title,blurb,description,category_id,mentor_id,level,theme,rating,learners,outcomes,final_project_title,final_project_description,published_at,published) values(p_org,'v2-market-alternatives','market-alternatives','Market & Alternatives','Understand how value is currently delivered.','Understand how value is currently delivered. Produce your Alternative/competitor map in a live opportunity workspace.','start','m-phoxta-curriculum','Beginner','start',0,0,'["Understand how value is currently delivered.","Create: Alternative/competitor map"]'::jsonb,'Alternative/competitor map','Map at least the current workaround and one direct or indirect alternative. Link sources for factual statements, and name what you still need to ask customers.','2026-09-26T00:00:00.000Z',true) on conflict(organization_id,id) do update set title=excluded.title,description=excluded.description,outcomes=excluded.outcomes,published=true;
insert into cs_courses(organization_id,id,slug,title,blurb,description,category_id,mentor_id,level,theme,rating,learners,outcomes,final_project_title,final_project_description,published_at,published) values(p_org,'v2-why-now','why-now','Why Now?','Identify enabling changes and timing.','Identify enabling changes and timing. Produce your Why-now thesis in a live opportunity workspace.','start','m-phoxta-curriculum','Beginner','start',0,0,'["Identify enabling changes and timing.","Create: Why-now thesis"]'::jsonb,'Why-now thesis','Write a why-now claim with a dated source where available. Explain the causal link to the customer problem and identify one reason that link may fail.','2026-09-26T00:00:00.000Z',true) on conflict(organization_id,id) do update set title=excluded.title,description=excluded.description,outcomes=excluded.outcomes,published=true;
insert into cs_courses(organization_id,id,slug,title,blurb,description,category_id,mentor_id,level,theme,rating,learners,outcomes,final_project_title,final_project_description,published_at,published) values(p_org,'v2-critical-assumptions','critical-assumptions','Critical Assumptions','State what must be true.','State what must be true. Produce your Assumption map in a live opportunity workspace.','fund','m-phoxta-curriculum','Beginner','fund',0,0,'["State what must be true.","Create: Assumption map"]'::jsonb,'Assumption map','Add your critical assumptions and rate their importance and uncertainty. Choose the one whose failure would most change your decision.','2026-09-26T00:00:00.000Z',true) on conflict(organization_id,id) do update set title=excluded.title,description=excluded.description,outcomes=excluded.outcomes,published=true;
insert into cs_courses(organization_id,id,slug,title,blurb,description,category_id,mentor_id,level,theme,rating,learners,outcomes,final_project_title,final_project_description,published_at,published) values(p_org,'v2-validation','validation','Validation','Design evidence-generating tests.','Design evidence-generating tests. Produce your Experiment plan in a live opportunity workspace.','fund','m-phoxta-curriculum','Beginner','fund',0,0,'["Design evidence-generating tests.","Create: Experiment plan"]'::jsonb,'Experiment plan','Create a draft experiment linked to an assumption, with a method, predetermined success criteria and a review date. Run it only after checking consent and any real-world obligations.','2026-09-26T00:00:00.000Z',true) on conflict(organization_id,id) do update set title=excluded.title,description=excluded.description,outcomes=excluded.outcomes,published=true;
insert into cs_courses(organization_id,id,slug,title,blurb,description,category_id,mentor_id,level,theme,rating,learners,outcomes,final_project_title,final_project_description,published_at,published) values(p_org,'v2-value-proposition','value-proposition','Value Proposition','Translate learning into a compelling outcome.','Translate learning into a compelling outcome. Produce your Value proposition in a live opportunity workspace.','fund','m-phoxta-curriculum','Beginner','fund',0,0,'["Translate learning into a compelling outcome.","Create: Value proposition"]'::jsonb,'Value proposition','Save a value proposition naming the customer, desired outcome, alternative, distinction and evidence. Include the next claim to test.','2026-09-26T00:00:00.000Z',true) on conflict(organization_id,id) do update set title=excluded.title,description=excluded.description,outcomes=excluded.outcomes,published=true;
insert into cs_courses(organization_id,id,slug,title,blurb,description,category_id,mentor_id,level,theme,rating,learners,outcomes,final_project_title,final_project_description,published_at,published) values(p_org,'v2-business-model','business-model','Business Model','Define who pays and how value is captured.','Define who pays and how value is captured. Produce your Business model in a live opportunity workspace.','fund','m-phoxta-curriculum','Beginner','fund',0,0,'["Define who pays and how value is captured.","Create: Business model"]'::jsonb,'Business model','Save a versioned model showing payer, pricing mechanism, revenue frequency, costs, delivery and the unit-economics assumptions to test next.','2026-09-26T00:00:00.000Z',true) on conflict(organization_id,id) do update set title=excluded.title,description=excluded.description,outcomes=excluded.outcomes,published=true;
insert into cs_courses(organization_id,id,slug,title,blurb,description,category_id,mentor_id,level,theme,rating,learners,outcomes,final_project_title,final_project_description,published_at,published) values(p_org,'v2-mvp-delivery','mvp-delivery','MVP & Delivery','Design the smallest credible delivery system.','Design the smallest credible delivery system. Produce your MVP scope in a live opportunity workspace.','grow','m-phoxta-curriculum','Beginner','grow',0,0,'["Design the smallest credible delivery system.","Create: MVP scope"]'::jsonb,'MVP scope','Write the MVP scope with the value to test, necessary work, manual steps, exclusions and acceptance criteria. Make external-action approvals explicit.','2026-09-26T00:00:00.000Z',true) on conflict(organization_id,id) do update set title=excluded.title,description=excluded.description,outcomes=excluded.outcomes,published=true;
insert into cs_courses(organization_id,id,slug,title,blurb,description,category_id,mentor_id,level,theme,rating,learners,outcomes,final_project_title,final_project_description,published_at,published) values(p_org,'v2-go-to-market','go-to-market','Go-to-Market','Choose channels and sales motion.','Choose channels and sales motion. Produce your Launch plan in a live opportunity workspace.','grow','m-phoxta-curriculum','Beginner','grow',0,0,'["Choose channels and sales motion.","Create: Launch plan"]'::jsonb,'Launch plan','Create a launch plan containing objective, target cohort, channels, message, activation, measurement and a post-launch learning review.','2026-09-26T00:00:00.000Z',true) on conflict(organization_id,id) do update set title=excluded.title,description=excluded.description,outcomes=excluded.outcomes,published=true;
insert into cs_courses(organization_id,id,slug,title,blurb,description,category_id,mentor_id,level,theme,rating,learners,outcomes,final_project_title,final_project_description,published_at,published) values(p_org,'v2-decision-iteration','decision-iteration','Decision & Iteration','Proceed, revise, pause or stop based on evidence.','Proceed, revise, pause or stop based on evidence. Produce your Decision review in a live opportunity workspace.','grow','m-phoxta-curriculum','Beginner','grow',0,0,'["Proceed, revise, pause or stop based on evidence.","Create: Decision review"]'::jsonb,'Decision review','Finalise a review stating what changed, what remains unknown, your decision and the next learning action. Confirm the snapshot yourself.','2026-09-26T00:00:00.000Z',true) on conflict(organization_id,id) do update set title=excluded.title,description=excluded.description,outcomes=excluded.outcomes,published=true;
insert into cs_modules(organization_id,id,course_id,title,sort) values(p_org,'v2-opportunity-thinking-module','v2-opportunity-thinking','Opportunity Thinking',0) on conflict(organization_id,id) do update set title=excluded.title;
insert into cs_modules(organization_id,id,course_id,title,sort) values(p_org,'v2-finding-problems-module','v2-finding-problems','Finding Problems Worth Investigating',0) on conflict(organization_id,id) do update set title=excluded.title;
insert into cs_modules(organization_id,id,course_id,title,sort) values(p_org,'v2-customers-context-module','v2-customers-context','Customers & Context',0) on conflict(organization_id,id) do update set title=excluded.title;
insert into cs_modules(organization_id,id,course_id,title,sort) values(p_org,'v2-market-alternatives-module','v2-market-alternatives','Market & Alternatives',0) on conflict(organization_id,id) do update set title=excluded.title;
insert into cs_modules(organization_id,id,course_id,title,sort) values(p_org,'v2-why-now-module','v2-why-now','Why Now?',0) on conflict(organization_id,id) do update set title=excluded.title;
insert into cs_modules(organization_id,id,course_id,title,sort) values(p_org,'v2-critical-assumptions-module','v2-critical-assumptions','Critical Assumptions',0) on conflict(organization_id,id) do update set title=excluded.title;
insert into cs_modules(organization_id,id,course_id,title,sort) values(p_org,'v2-validation-module','v2-validation','Validation',0) on conflict(organization_id,id) do update set title=excluded.title;
insert into cs_modules(organization_id,id,course_id,title,sort) values(p_org,'v2-value-proposition-module','v2-value-proposition','Value Proposition',0) on conflict(organization_id,id) do update set title=excluded.title;
insert into cs_modules(organization_id,id,course_id,title,sort) values(p_org,'v2-business-model-module','v2-business-model','Business Model',0) on conflict(organization_id,id) do update set title=excluded.title;
insert into cs_modules(organization_id,id,course_id,title,sort) values(p_org,'v2-mvp-delivery-module','v2-mvp-delivery','MVP & Delivery',0) on conflict(organization_id,id) do update set title=excluded.title;
insert into cs_modules(organization_id,id,course_id,title,sort) values(p_org,'v2-go-to-market-module','v2-go-to-market','Go-to-Market',0) on conflict(organization_id,id) do update set title=excluded.title;
insert into cs_modules(organization_id,id,course_id,title,sort) values(p_org,'v2-decision-iteration-module','v2-decision-iteration','Decision & Iteration',0) on conflict(organization_id,id) do update set title=excluded.title;
insert into cs_lessons(organization_id,id,course_id,module_id,title,kind,duration_sec,body,sort) values(p_org,'v2-opportunity-thinking-practice','v2-opportunity-thinking','v2-opportunity-thinking-module','Opportunity Thinking','article',600,'An idea proposes something to build. A problem describes an outcome someone struggles to achieve. A trend describes a change. An opportunity connects a specific customer and problem to a plausible way of creating value. None of these establishes demand on its own.

Start with the customer and their situation. Describe the job they need to accomplish, what they do today and why an alternative might matter. Keep the proposed solution provisional: several different businesses could address the same problem.

Write a thesis that another person can challenge. Separate what you observed from what you infer and what remains unknown. A useful thesis makes your next investigation obvious; it does not make the opportunity sound certain.

**Illustrative example**

Fictional service-business example: a founder proposes an AI scheduling app. Their opportunity thesis instead asks whether independent repair businesses lose work while coordinating appointments. The founder has not yet observed the workflow or established willingness to pay. Both remain unknown.

**Apply it to your opportunity**

Write a two-to-four-sentence thesis naming the customer, problem, current alternative and why the opportunity may matter. Label it as inferred until you can link real evidence.',0) on conflict(organization_id,id) do update set title=excluded.title,body=excluded.body;
insert into cs_lessons(organization_id,id,course_id,module_id,title,kind,duration_sec,body,sort) values(p_org,'v2-finding-problems-practice','v2-finding-problems','v2-finding-problems-module','Finding Problems Worth Investigating','article',600,'Look for work people already do, delays they accept and workarounds they maintain. A complaint is a starting signal, not proof that a person will change behaviour or buy a solution. Observe the work in its context wherever possible.

Ask about a recent specific incident: what triggered it, what happened next, what tools were used and what the consequences were. Avoid suggesting your product or asking whether someone likes your idea. Record the customer’s account separately from your explanation of it.

A useful evidence record includes the observation, the source or interview reference, the date, the market and the limits of what it tells you. Ask permission before recording personal information. An AI-generated customer story is a hypothesis, never an interview.

**Illustrative example**

Fictional local-business example: an operator watches a shopkeeper reconcile orders against messages. The observation concerns that shopkeeper on that day. It does not establish that every shopkeeper has the same problem.

**Apply it to your opportunity**

Record one real observation or sourced problem signal. Include its date and context, then state what it does and does not support.',0) on conflict(organization_id,id) do update set title=excluded.title,body=excluded.body;
insert into cs_lessons(organization_id,id,course_id,module_id,title,kind,duration_sec,body,sort) values(p_org,'v2-customers-context-practice','v2-customers-context','v2-customers-context-module','Customers & Context','article',600,'A customer segment is useful when its members share a relevant job, context or constraint. A broad label such as small business hides differences in buying behaviour, budget and access. Narrow the segment enough to identify people you can actually speak with.

The user, buyer and approver can be different people. Map who experiences the problem, who pays, who can block adoption and what event triggers a search for an alternative. Do not infer budget merely from job title or company size.

Describe one primary segment and record adjacent segments separately. Revisit your choice when observations contradict it. Your profile is a working hypothesis, not a demographic persona invented to fill a template.

**Illustrative example**

Fictional SaaS example: an operations employee uses a reporting tool, a department head approves it and finance pays. A problem experienced by the user may not be important enough for the buyer to fund.

**Apply it to your opportunity**

Create an ideal customer profile with the user, buyer, job, context, trigger and route to a real conversation. Mark unsupported attributes as assumptions.',0) on conflict(organization_id,id) do update set title=excluded.title,body=excluded.body;
insert into cs_lessons(organization_id,id,course_id,module_id,title,kind,duration_sec,body,sort) values(p_org,'v2-market-alternatives-practice','v2-market-alternatives','v2-market-alternatives-module','Market & Alternatives','article',600,'Competition includes direct products, services, internal processes, spreadsheets and doing nothing. Begin with how the customer handles the job today. An alternative can be inconvenient and still be good enough to prevent switching.

Map the value chain: who supplies inputs, who delivers the outcome, who controls access and who captures payment. Describe alternatives using verifiable sources. A model’s suggestion that a competitor exists is not sufficient evidence.

Compare outcomes and constraints rather than building a feature-count contest. Keep observed facts, your interpretation of a gap and the switching hypothesis separate. Record source dates because product capabilities and prices change.

**Illustrative example**

Fictional ecommerce example: a seller handles returns through email and a spreadsheet. Their alternative is a familiar process with no new subscription. A new returns product must justify the disruption of switching.

**Apply it to your opportunity**

Map at least the current workaround and one direct or indirect alternative. Link sources for factual statements, and name what you still need to ask customers.',0) on conflict(organization_id,id) do update set title=excluded.title,body=excluded.body;
insert into cs_lessons(organization_id,id,course_id,module_id,title,kind,duration_sec,body,sort) values(p_org,'v2-why-now-practice','v2-why-now','v2-why-now-module','Why Now?','article',600,'A timing thesis explains what changed and how that change affects a customer’s options. Changes can involve technology, regulation, behaviour, economics or distribution. A fashionable topic is not enough: describe the mechanism connecting the change to the problem.

Record when the change occurred, its geography and the source. Separate the existence of a change from your belief about its commercial effect. A cheaper technical capability does not establish that customers need or want the resulting product.

Ask what would make the timing thesis wrong. The customer might not be ready, adoption might be costly or the change may already be reflected in existing alternatives. Use those uncertainties to guide research.

**Illustrative example**

Fictional AI-enabled-business example: a new document-processing capability might reduce a manual step. The team still needs to test accuracy, review effort and whether the affected customer sees enough value to change.

**Apply it to your opportunity**

Write a why-now claim with a dated source where available. Explain the causal link to the customer problem and identify one reason that link may fail.',0) on conflict(organization_id,id) do update set title=excluded.title,body=excluded.body;
insert into cs_lessons(organization_id,id,course_id,module_id,title,kind,duration_sec,body,sort) values(p_org,'v2-critical-assumptions-practice','v2-critical-assumptions','v2-critical-assumptions-module','Critical Assumptions','article',600,'An assumption is a statement that must hold for your opportunity to work. It should be specific enough to support or contradict. “Customers will love it” is hard to test; a statement about a particular customer, behaviour and situation is more useful.

Consider problem, customer, value, behaviour, payment, distribution, solution, operations and regulatory assumptions. Importance asks how much the opportunity depends on a claim. Uncertainty asks how little you currently know about it. Prioritise high-importance, high-uncertainty claims.

These ratings order learning; they do not predict business success. Evidence can support, contradict or provide context. Preserve disagreement rather than averaging it into a reassuring score.

**Illustrative example**

Fictional service example: the team believes buyers will switch from an existing supplier. This assumption could invalidate the offer even if delivery is technically easy. It deserves testing before adding more features.

**Apply it to your opportunity**

Add your critical assumptions and rate their importance and uncertainty. Choose the one whose failure would most change your decision.',0) on conflict(organization_id,id) do update set title=excluded.title,body=excluded.body;
insert into cs_lessons(organization_id,id,course_id,module_id,title,kind,duration_sec,body,sort) values(p_org,'v2-validation-practice','v2-validation','v2-validation-module','Validation','article',600,'Validation is an investigation, not a one-time verdict. Choose a test that can change your view of a critical assumption. Interviews, prototypes, concierge delivery, landing pages, waitlists and paid pilots answer different questions.

Define the hypothesis, method and success criteria before running the test. State who will participate, what action or observation matters and when you will review the result. Choose the smallest credible test rather than the most impressive prototype.

Record observations separately from interpretation. An inconclusive result is useful when it shows what your test could not establish. Avoid changing the success threshold after seeing the result. Do not treat stated enthusiasm as equivalent to usage or payment.

**Illustrative example**

Fictional local-service example: a concierge test delivers the proposed outcome manually before software exists. It can reveal whether the outcome matters, while leaving automation cost and scalability unproven.

**Apply it to your opportunity**

Create a draft experiment linked to an assumption, with a method, predetermined success criteria and a review date. Run it only after checking consent and any real-world obligations.',0) on conflict(organization_id,id) do update set title=excluded.title,body=excluded.body;
insert into cs_lessons(organization_id,id,course_id,module_id,title,kind,duration_sec,body,sort) values(p_org,'v2-value-proposition-practice','v2-value-proposition','v2-value-proposition-module','Value Proposition','article',600,'A value proposition describes a meaningful customer outcome and why this offer may deliver it better than current alternatives. Begin with what you have learned about the customer’s job and context. A technology label is not itself a customer benefit.

Connect the desired outcome to concrete deliverables and a reason to believe. Be explicit about constraints: what the offer does not promise, what the customer must contribute and which parts remain hypotheses.

Use customer language from actual observations where available. Test whether the promise is understood and whether it motivates a relevant action. Revise the promise when the evidence changes instead of making it broader.

**Illustrative example**

Fictional SaaS example: “AI-powered reports” becomes a proposed outcome of preparing a reviewable report from existing records. The accuracy and time benefit remain assumptions until tested with real users.

**Apply it to your opportunity**

Save a value proposition naming the customer, desired outcome, alternative, distinction and evidence. Include the next claim to test.',0) on conflict(organization_id,id) do update set title=excluded.title,body=excluded.body;
insert into cs_lessons(organization_id,id,course_id,module_id,title,kind,duration_sec,body,sort) values(p_org,'v2-business-model-practice','v2-business-model','v2-business-model-module','Business Model','article',600,'A business model connects the customer outcome to payment and delivery. Identify who pays, what they pay for, how often, how the offer reaches them and what it costs to deliver. A price without a payer and buying situation is an unsupported number.

Separate revenue hypotheses from observed transactions. Record direct delivery costs, acquisition effort, recurring infrastructure and human work. In an AI-enabled service, include review, exception handling and provider usage in the delivery model.

Explore how the model changes when a key assumption is wrong. A useful first model shows which inputs need evidence; it does not turn a spreadsheet into a forecast you can trust.

**Illustrative example**

Fictional ecommerce example: a subscription may create recurring revenue, but replenishment frequency, returns and repeat demand still need testing. The team records those as assumptions rather than filling a growth forecast with unsupported rates.

**Apply it to your opportunity**

Save a versioned model showing payer, pricing mechanism, revenue frequency, costs, delivery and the unit-economics assumptions to test next.',0) on conflict(organization_id,id) do update set title=excluded.title,body=excluded.body;
insert into cs_lessons(organization_id,id,course_id,module_id,title,kind,duration_sec,body,sort) values(p_org,'v2-mvp-delivery-practice','v2-mvp-delivery','v2-mvp-delivery-module','MVP & Delivery','article',600,'An MVP is a boundary around the smallest credible way to deliver and test the proposed value. It is not simply a large product with fewer features. Decide which uncertainty the first version must resolve.

Map the customer journey to the first useful outcome. Identify what must work, what can be delivered manually and what can wait. Include support, failures and human review where they affect that outcome.

For an automated workflow, define inputs, permitted tools, outputs, logs and approval points. Planning a workflow does not authorize it to send messages, publish content or spend money. Test with controlled inputs before requesting production activation.

**Illustrative example**

Fictional AI-enabled-service example: a founder reviews every generated draft before delivery. That manual review is part of the MVP, allowing the team to learn about quality without claiming autonomous reliability.

**Apply it to your opportunity**

Write the MVP scope with the value to test, necessary work, manual steps, exclusions and acceptance criteria. Make external-action approvals explicit.',0) on conflict(organization_id,id) do update set title=excluded.title,body=excluded.body;
insert into cs_lessons(organization_id,id,course_id,module_id,title,kind,duration_sec,body,sort) values(p_org,'v2-go-to-market-practice','v2-go-to-market','v2-go-to-market-module','Go-to-Market','article',600,'A launch is a plan to reach a defined customer, help them experience value and learn from what happens. Start with a target cohort and an objective. Choose channels because you have a plausible route to that customer, not because every business is expected to use them.

Connect the offer, message, sales conversation, onboarding and measurement. Define the action that represents activation and the follow-up that reveals continued value. Keep channel performance and revenue expectations labelled as hypotheses until observed.

Plan the review before the announcement. Record what you will measure, who owns it and which result would change your approach. Drafting a campaign is separate from authorizing publication, outreach or spending.

**Illustrative example**

Fictional service-business example: a founder plans a small set of consent-based discovery conversations through an existing professional community. The plan specifies the customer, offer, desired next action and learning review without assuming a conversion rate.

**Apply it to your opportunity**

Create a launch plan containing objective, target cohort, channels, message, activation, measurement and a post-launch learning review.',0) on conflict(organization_id,id) do update set title=excluded.title,body=excluded.body;
insert into cs_lessons(organization_id,id,course_id,module_id,title,kind,duration_sec,body,sort) values(p_org,'v2-decision-iteration-practice','v2-decision-iteration','v2-decision-iteration-module','Decision & Iteration','article',600,'A decision review connects what you learned to what you will do next. It does not require the system to declare the opportunity good or bad. Review the original thesis, new evidence, supported and contradicted assumptions, and unresolved questions.

Proceed means continuing with a stated next objective. Revise means changing the thesis or approach. Pause preserves the work while priorities or evidence develop. Stop records why further effort is not justified now. These are decisions under uncertainty, not predictions.

Write a rationale that a future reader can understand. Preserve the evidence available at that moment. If later evidence changes your view, create another review instead of rewriting the earlier decision. The venture loop can move backward or sideways as learning changes the work.

**Illustrative example**

Fictional local-business example: interviews support the problem, but a pilot has not shown willingness to pay. The founder pauses building, records that uncertainty and identifies a smaller payment test. The problem evidence remains useful even though the decision changes.

**Apply it to your opportunity**

Finalise a review stating what changed, what remains unknown, your decision and the next learning action. Confirm the snapshot yourself.',0) on conflict(organization_id,id) do update set title=excluded.title,body=excluded.body;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'opportunity-thinking-objective','v2-opportunity-thinking-practice','objective','Learning objective','Understand the difference between an idea, problem, trend and opportunity.',0,'','') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'opportunity-thinking-learn','v2-opportunity-thinking-practice','learn','Learn','An idea proposes something to build. A problem describes an outcome someone struggles to achieve. A trend describes a change. An opportunity connects a specific customer and problem to a plausible way of creating value. None of these establishes demand on its own.

Start with the customer and their situation. Describe the job they need to accomplish, what they do today and why an alternative might matter. Keep the proposed solution provisional: several different businesses could address the same problem.

Write a thesis that another person can challenge. Separate what you observed from what you infer and what remains unknown. A useful thesis makes your next investigation obvious; it does not make the opportunity sound certain.',1,'','') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'opportunity-thinking-example','v2-opportunity-thinking-practice','example','Illustrative example','Fictional service-business example: a founder proposes an AI scheduling app. Their opportunity thesis instead asks whether independent repair businesses lose work while coordinating appointments. The founder has not yet observed the workflow or established willingness to pay. Both remain unknown.',2,'','') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'opportunity-thinking-activity','v2-opportunity-thinking-practice','activity','Create your Opportunity thesis','Write a two-to-four-sentence thesis naming the customer, problem, current alternative and why the opportunity may matter. Label it as inferred until you can link real evidence.',3,'','') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'opportunity-thinking-template','v2-opportunity-thinking-practice','template','Opportunity thesis','- Customer and context
- Problem or desired outcome
- Current alternative
- Why this may matter
- What remains unknown',4,'/opportunity-practice/opportunity-thinking','Open opportunity workspace') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'opportunity-thinking-coach','v2-opportunity-thinking-practice','ai_activity','Ask the Adviser','Bring your real draft or observations. Ask which statements are supported, which are hypotheses and which question to test next. Do not ask AI to invent evidence.',5,'/adviser','Open Adviser') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'finding-problems-objective','v2-finding-problems-practice','objective','Learning objective','Observe jobs, pain, friction and workarounds.',0,'','') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'finding-problems-learn','v2-finding-problems-practice','learn','Learn','Look for work people already do, delays they accept and workarounds they maintain. A complaint is a starting signal, not proof that a person will change behaviour or buy a solution. Observe the work in its context wherever possible.

Ask about a recent specific incident: what triggered it, what happened next, what tools were used and what the consequences were. Avoid suggesting your product or asking whether someone likes your idea. Record the customer’s account separately from your explanation of it.

A useful evidence record includes the observation, the source or interview reference, the date, the market and the limits of what it tells you. Ask permission before recording personal information. An AI-generated customer story is a hypothesis, never an interview.',1,'','') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'finding-problems-example','v2-finding-problems-practice','example','Illustrative example','Fictional local-business example: an operator watches a shopkeeper reconcile orders against messages. The observation concerns that shopkeeper on that day. It does not establish that every shopkeeper has the same problem.',2,'','') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'finding-problems-activity','v2-finding-problems-practice','activity','Create your Problem evidence log','Record one real observation or sourced problem signal. Include its date and context, then state what it does and does not support.',3,'','') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'finding-problems-template','v2-finding-problems-practice','template','Problem evidence log','- Observed job
- Friction or workaround
- Who and where
- Source and date
- Interpretation
- Limits of the evidence',4,'/opportunity-practice/finding-problems','Open opportunity workspace') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'finding-problems-coach','v2-finding-problems-practice','ai_activity','Ask the Adviser','Bring your real draft or observations. Ask which statements are supported, which are hypotheses and which question to test next. Do not ask AI to invent evidence.',5,'/adviser','Open Adviser') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'customers-context-objective','v2-customers-context-practice','objective','Learning objective','Define who experiences the problem and when.',0,'','') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'customers-context-learn','v2-customers-context-practice','learn','Learn','A customer segment is useful when its members share a relevant job, context or constraint. A broad label such as small business hides differences in buying behaviour, budget and access. Narrow the segment enough to identify people you can actually speak with.

The user, buyer and approver can be different people. Map who experiences the problem, who pays, who can block adoption and what event triggers a search for an alternative. Do not infer budget merely from job title or company size.

Describe one primary segment and record adjacent segments separately. Revisit your choice when observations contradict it. Your profile is a working hypothesis, not a demographic persona invented to fill a template.',1,'','') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'customers-context-example','v2-customers-context-practice','example','Illustrative example','Fictional SaaS example: an operations employee uses a reporting tool, a department head approves it and finance pays. A problem experienced by the user may not be important enough for the buyer to fund.',2,'','') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'customers-context-activity','v2-customers-context-practice','activity','Create your ICP + context map','Create an ideal customer profile with the user, buyer, job, context, trigger and route to a real conversation. Mark unsupported attributes as assumptions.',3,'','') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'customers-context-template','v2-customers-context-practice','template','ICP + context map','- Primary segment
- User
- Buyer and approver
- Job and context
- Trigger
- Reachable channel
- Evidence and unknowns',4,'/opportunity-practice/customers-context','Open opportunity workspace') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'customers-context-coach','v2-customers-context-practice','ai_activity','Ask the Adviser','Bring your real draft or observations. Ask which statements are supported, which are hypotheses and which question to test next. Do not ask AI to invent evidence.',5,'/adviser','Open Adviser') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'market-alternatives-objective','v2-market-alternatives-practice','objective','Learning objective','Understand how value is currently delivered.',0,'','') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'market-alternatives-learn','v2-market-alternatives-practice','learn','Learn','Competition includes direct products, services, internal processes, spreadsheets and doing nothing. Begin with how the customer handles the job today. An alternative can be inconvenient and still be good enough to prevent switching.

Map the value chain: who supplies inputs, who delivers the outcome, who controls access and who captures payment. Describe alternatives using verifiable sources. A model’s suggestion that a competitor exists is not sufficient evidence.

Compare outcomes and constraints rather than building a feature-count contest. Keep observed facts, your interpretation of a gap and the switching hypothesis separate. Record source dates because product capabilities and prices change.',1,'','') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'market-alternatives-example','v2-market-alternatives-practice','example','Illustrative example','Fictional ecommerce example: a seller handles returns through email and a spreadsheet. Their alternative is a familiar process with no new subscription. A new returns product must justify the disruption of switching.',2,'','') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'market-alternatives-activity','v2-market-alternatives-practice','activity','Create your Alternative/competitor map','Map at least the current workaround and one direct or indirect alternative. Link sources for factual statements, and name what you still need to ask customers.',3,'','') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'market-alternatives-template','v2-market-alternatives-practice','template','Alternative/competitor map','- Current workaround
- Direct alternatives
- Indirect alternatives
- Value chain
- Switching cost
- Sources and dates
- Unanswered questions',4,'/opportunity-practice/market-alternatives','Open opportunity workspace') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'market-alternatives-coach','v2-market-alternatives-practice','ai_activity','Ask the Adviser','Bring your real draft or observations. Ask which statements are supported, which are hypotheses and which question to test next. Do not ask AI to invent evidence.',5,'/adviser','Open Adviser') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'why-now-objective','v2-why-now-practice','objective','Learning objective','Identify enabling changes and timing.',0,'','') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'why-now-learn','v2-why-now-practice','learn','Learn','A timing thesis explains what changed and how that change affects a customer’s options. Changes can involve technology, regulation, behaviour, economics or distribution. A fashionable topic is not enough: describe the mechanism connecting the change to the problem.

Record when the change occurred, its geography and the source. Separate the existence of a change from your belief about its commercial effect. A cheaper technical capability does not establish that customers need or want the resulting product.

Ask what would make the timing thesis wrong. The customer might not be ready, adoption might be costly or the change may already be reflected in existing alternatives. Use those uncertainties to guide research.',1,'','') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'why-now-example','v2-why-now-practice','example','Illustrative example','Fictional AI-enabled-business example: a new document-processing capability might reduce a manual step. The team still needs to test accuracy, review effort and whether the affected customer sees enough value to change.',2,'','') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'why-now-activity','v2-why-now-practice','activity','Create your Why-now thesis','Write a why-now claim with a dated source where available. Explain the causal link to the customer problem and identify one reason that link may fail.',3,'','') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'why-now-template','v2-why-now-practice','template','Why-now thesis','- Change
- Date and geography
- Source
- Effect on the customer
- Commercial hypothesis
- What would contradict it',4,'/opportunity-practice/why-now','Open opportunity workspace') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'why-now-coach','v2-why-now-practice','ai_activity','Ask the Adviser','Bring your real draft or observations. Ask which statements are supported, which are hypotheses and which question to test next. Do not ask AI to invent evidence.',5,'/adviser','Open Adviser') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'critical-assumptions-objective','v2-critical-assumptions-practice','objective','Learning objective','State what must be true.',0,'','') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'critical-assumptions-learn','v2-critical-assumptions-practice','learn','Learn','An assumption is a statement that must hold for your opportunity to work. It should be specific enough to support or contradict. “Customers will love it” is hard to test; a statement about a particular customer, behaviour and situation is more useful.

Consider problem, customer, value, behaviour, payment, distribution, solution, operations and regulatory assumptions. Importance asks how much the opportunity depends on a claim. Uncertainty asks how little you currently know about it. Prioritise high-importance, high-uncertainty claims.

These ratings order learning; they do not predict business success. Evidence can support, contradict or provide context. Preserve disagreement rather than averaging it into a reassuring score.',1,'','') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'critical-assumptions-example','v2-critical-assumptions-practice','example','Illustrative example','Fictional service example: the team believes buyers will switch from an existing supplier. This assumption could invalidate the offer even if delivery is technically easy. It deserves testing before adding more features.',2,'','') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'critical-assumptions-activity','v2-critical-assumptions-practice','activity','Create your Assumption map','Add your critical assumptions and rate their importance and uncertainty. Choose the one whose failure would most change your decision.',3,'','') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'critical-assumptions-template','v2-critical-assumptions-practice','template','Assumption map','- Must-be-true statement
- Class
- Importance
- Uncertainty
- Existing evidence
- Cheapest useful test',4,'/opportunity-practice/critical-assumptions','Open opportunity workspace') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'critical-assumptions-coach','v2-critical-assumptions-practice','ai_activity','Ask the Adviser','Bring your real draft or observations. Ask which statements are supported, which are hypotheses and which question to test next. Do not ask AI to invent evidence.',5,'/adviser','Open Adviser') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'validation-objective','v2-validation-practice','objective','Learning objective','Design evidence-generating tests.',0,'','') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'validation-learn','v2-validation-practice','learn','Learn','Validation is an investigation, not a one-time verdict. Choose a test that can change your view of a critical assumption. Interviews, prototypes, concierge delivery, landing pages, waitlists and paid pilots answer different questions.

Define the hypothesis, method and success criteria before running the test. State who will participate, what action or observation matters and when you will review the result. Choose the smallest credible test rather than the most impressive prototype.

Record observations separately from interpretation. An inconclusive result is useful when it shows what your test could not establish. Avoid changing the success threshold after seeing the result. Do not treat stated enthusiasm as equivalent to usage or payment.',1,'','') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'validation-example','v2-validation-practice','example','Illustrative example','Fictional local-service example: a concierge test delivers the proposed outcome manually before software exists. It can reveal whether the outcome matters, while leaving automation cost and scalability unproven.',2,'','') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'validation-activity','v2-validation-practice','activity','Create your Experiment plan','Create a draft experiment linked to an assumption, with a method, predetermined success criteria and a review date. Run it only after checking consent and any real-world obligations.',3,'','') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'validation-template','v2-validation-practice','template','Experiment plan','- Linked assumption
- Hypothesis
- Participants
- Method
- Success criteria
- Review date
- Learning',4,'/opportunity-practice/validation','Open opportunity workspace') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'validation-coach','v2-validation-practice','ai_activity','Ask the Adviser','Bring your real draft or observations. Ask which statements are supported, which are hypotheses and which question to test next. Do not ask AI to invent evidence.',5,'/adviser','Open Adviser') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'value-proposition-objective','v2-value-proposition-practice','objective','Learning objective','Translate learning into a compelling outcome.',0,'','') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'value-proposition-learn','v2-value-proposition-practice','learn','Learn','A value proposition describes a meaningful customer outcome and why this offer may deliver it better than current alternatives. Begin with what you have learned about the customer’s job and context. A technology label is not itself a customer benefit.

Connect the desired outcome to concrete deliverables and a reason to believe. Be explicit about constraints: what the offer does not promise, what the customer must contribute and which parts remain hypotheses.

Use customer language from actual observations where available. Test whether the promise is understood and whether it motivates a relevant action. Revise the promise when the evidence changes instead of making it broader.',1,'','') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'value-proposition-example','v2-value-proposition-practice','example','Illustrative example','Fictional SaaS example: “AI-powered reports” becomes a proposed outcome of preparing a reviewable report from existing records. The accuracy and time benefit remain assumptions until tested with real users.',2,'','') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'value-proposition-activity','v2-value-proposition-practice','activity','Create your Value proposition','Save a value proposition naming the customer, desired outcome, alternative, distinction and evidence. Include the next claim to test.',3,'','') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'value-proposition-template','v2-value-proposition-practice','template','Value proposition','- Customer
- Desired outcome
- Current alternative
- Differentiated promise
- Reason to believe
- Constraints
- Next test',4,'/opportunity-practice/value-proposition','Open opportunity workspace') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'value-proposition-coach','v2-value-proposition-practice','ai_activity','Ask the Adviser','Bring your real draft or observations. Ask which statements are supported, which are hypotheses and which question to test next. Do not ask AI to invent evidence.',5,'/adviser','Open Adviser') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'business-model-objective','v2-business-model-practice','objective','Learning objective','Define who pays and how value is captured.',0,'','') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'business-model-learn','v2-business-model-practice','learn','Learn','A business model connects the customer outcome to payment and delivery. Identify who pays, what they pay for, how often, how the offer reaches them and what it costs to deliver. A price without a payer and buying situation is an unsupported number.

Separate revenue hypotheses from observed transactions. Record direct delivery costs, acquisition effort, recurring infrastructure and human work. In an AI-enabled service, include review, exception handling and provider usage in the delivery model.

Explore how the model changes when a key assumption is wrong. A useful first model shows which inputs need evidence; it does not turn a spreadsheet into a forecast you can trust.',1,'','') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'business-model-example','v2-business-model-practice','example','Illustrative example','Fictional ecommerce example: a subscription may create recurring revenue, but replenishment frequency, returns and repeat demand still need testing. The team records those as assumptions rather than filling a growth forecast with unsupported rates.',2,'','') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'business-model-activity','v2-business-model-practice','activity','Create your Business model','Save a versioned model showing payer, pricing mechanism, revenue frequency, costs, delivery and the unit-economics assumptions to test next.',3,'','') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'business-model-template','v2-business-model-practice','template','Business model','- Payer
- What is purchased
- Pricing hypothesis
- Revenue frequency
- Cost drivers
- Delivery model
- Unit economics assumptions',4,'/opportunity-practice/business-model','Open opportunity workspace') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'business-model-coach','v2-business-model-practice','ai_activity','Ask the Adviser','Bring your real draft or observations. Ask which statements are supported, which are hypotheses and which question to test next. Do not ask AI to invent evidence.',5,'/adviser','Open Adviser') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'mvp-delivery-objective','v2-mvp-delivery-practice','objective','Learning objective','Design the smallest credible delivery system.',0,'','') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'mvp-delivery-learn','v2-mvp-delivery-practice','learn','Learn','An MVP is a boundary around the smallest credible way to deliver and test the proposed value. It is not simply a large product with fewer features. Decide which uncertainty the first version must resolve.

Map the customer journey to the first useful outcome. Identify what must work, what can be delivered manually and what can wait. Include support, failures and human review where they affect that outcome.

For an automated workflow, define inputs, permitted tools, outputs, logs and approval points. Planning a workflow does not authorize it to send messages, publish content or spend money. Test with controlled inputs before requesting production activation.',1,'','') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'mvp-delivery-example','v2-mvp-delivery-practice','example','Illustrative example','Fictional AI-enabled-service example: a founder reviews every generated draft before delivery. That manual review is part of the MVP, allowing the team to learn about quality without claiming autonomous reliability.',2,'','') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'mvp-delivery-activity','v2-mvp-delivery-practice','activity','Create your MVP scope','Write the MVP scope with the value to test, necessary work, manual steps, exclusions and acceptance criteria. Make external-action approvals explicit.',3,'','') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'mvp-delivery-template','v2-mvp-delivery-practice','template','MVP scope','- Value to test
- Core journey
- Must exist
- Manual steps
- Not yet
- Failure handling
- Acceptance criteria',4,'/opportunity-practice/mvp-delivery','Open opportunity workspace') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'mvp-delivery-coach','v2-mvp-delivery-practice','ai_activity','Ask the Adviser','Bring your real draft or observations. Ask which statements are supported, which are hypotheses and which question to test next. Do not ask AI to invent evidence.',5,'/adviser','Open Adviser') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'go-to-market-objective','v2-go-to-market-practice','objective','Learning objective','Choose channels and sales motion.',0,'','') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'go-to-market-learn','v2-go-to-market-practice','learn','Learn','A launch is a plan to reach a defined customer, help them experience value and learn from what happens. Start with a target cohort and an objective. Choose channels because you have a plausible route to that customer, not because every business is expected to use them.

Connect the offer, message, sales conversation, onboarding and measurement. Define the action that represents activation and the follow-up that reveals continued value. Keep channel performance and revenue expectations labelled as hypotheses until observed.

Plan the review before the announcement. Record what you will measure, who owns it and which result would change your approach. Drafting a campaign is separate from authorizing publication, outreach or spending.',1,'','') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'go-to-market-example','v2-go-to-market-practice','example','Illustrative example','Fictional service-business example: a founder plans a small set of consent-based discovery conversations through an existing professional community. The plan specifies the customer, offer, desired next action and learning review without assuming a conversion rate.',2,'','') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'go-to-market-activity','v2-go-to-market-practice','activity','Create your Launch plan','Create a launch plan containing objective, target cohort, channels, message, activation, measurement and a post-launch learning review.',3,'','') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'go-to-market-template','v2-go-to-market-practice','template','Launch plan','- Objective
- Target cohort
- Offer
- Channel hypothesis
- Sales motion
- Onboarding
- Measurement
- Review and next decision',4,'/opportunity-practice/go-to-market','Open opportunity workspace') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'go-to-market-coach','v2-go-to-market-practice','ai_activity','Ask the Adviser','Bring your real draft or observations. Ask which statements are supported, which are hypotheses and which question to test next. Do not ask AI to invent evidence.',5,'/adviser','Open Adviser') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'decision-iteration-objective','v2-decision-iteration-practice','objective','Learning objective','Proceed, revise, pause or stop based on evidence.',0,'','') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'decision-iteration-learn','v2-decision-iteration-practice','learn','Learn','A decision review connects what you learned to what you will do next. It does not require the system to declare the opportunity good or bad. Review the original thesis, new evidence, supported and contradicted assumptions, and unresolved questions.

Proceed means continuing with a stated next objective. Revise means changing the thesis or approach. Pause preserves the work while priorities or evidence develop. Stop records why further effort is not justified now. These are decisions under uncertainty, not predictions.

Write a rationale that a future reader can understand. Preserve the evidence available at that moment. If later evidence changes your view, create another review instead of rewriting the earlier decision. The venture loop can move backward or sideways as learning changes the work.',1,'','') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'decision-iteration-example','v2-decision-iteration-practice','example','Illustrative example','Fictional local-business example: interviews support the problem, but a pilot has not shown willingness to pay. The founder pauses building, records that uncertainty and identifies a smaller payment test. The problem evidence remains useful even though the decision changes.',2,'','') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'decision-iteration-activity','v2-decision-iteration-practice','activity','Create your Decision review','Finalise a review stating what changed, what remains unknown, your decision and the next learning action. Confirm the snapshot yourself.',3,'','') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'decision-iteration-template','v2-decision-iteration-practice','template','Decision review','- What was learned
- Supported assumptions
- Contradictions
- Open questions
- Proceed / revise / pause / stop
- Rationale
- Next action',4,'/opportunity-practice/decision-iteration','Open opportunity workspace') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into cs_lesson_blocks(organization_id,id,lesson_id,type,title,content,sort,action_href,action_label) values(p_org,'decision-iteration-coach','v2-decision-iteration-practice','ai_activity','Ask the Adviser','Bring your real draft or observations. Ask which statements are supported, which are hypotheses and which question to test next. Do not ask AI to invent evidence.',5,'/adviser','Open Adviser') on conflict(organization_id,id) do update set title=excluded.title,content=excluded.content,action_href=excluded.action_href,action_label=excluded.action_label;
insert into opportunity_audit_logs(actor_user_id,org_id,action,metadata) values(auth.uid(),p_org,'school_curriculum_activated',jsonb_build_object('version','phoxta-2.0-school-v1'));
return v_preview || '{"activated":true}'::jsonb;end $school$;
revoke all on function public.ss_activate_opportunity_curriculum(uuid,boolean) from public,anon;
grant execute on function public.ss_activate_opportunity_curriculum(uuid,boolean) to authenticated;
commit;
