import type { Frontier } from '../frontier'

/**
 * Where aspect-based sentiment, topic modelling and brand-crisis detection stand
 * in September 2026. Every claim is backed by a source in `sources`.
 */
const frontier: Frontier = {
  asOf: '2026-09',
  headline:
    'The aspect scores hold up against published human agreement, but the extraction layer is a keyword lexicon in a field that has moved to instruction-tuned generative ABSA with five sentiment classes and multilingual coverage — while the crisis engine occupies a genuine white space, because no one publishes a lead-time benchmark at all.',
  summary: [
    'Aspect-based sentiment stopped being a classification problem and became a generation problem. InstructABSA instruction-tunes a 200M-parameter Tk-Instruct model with positive, negative and neutral exemplars in every training sample and reaches F1 92.10 on SemEval-2014 Restaurant aspect-term extraction against 85.45 for the prior best, and 92.30 on Laptop against 87.93 — while losing on pure polarity classification to specialised discriminative encoders. That asymmetry is the single most useful engineering fact in the area: extract with a generative model, classify polarity with a discriminative one, and do not ask one model to do both.',
    'The 2026 entrant built for commercial reality is Arctic-ABSA, which aggregates 17 public ABSA datasets across 92 domains, trains a 395M encoder and an 8B decoder, and — crucially — expands the label set from three classes to five by adding *mixed* and *unknown*. Real review text is full of "great food, awful service", which a three-class scheme has to flatten. It reports up to ten percentage points more accuracy than GPT-4o and Claude 3.5 Sonnet and 87–91% across six languages from a single model, which is the clearest available evidence that frontier general-purpose LLMs are not the state of the art for this task.',
    'On the encoder side, ModernBERT retired the 512-token ceiling: 149M and 395M parameter models trained on 2 trillion tokens with a native 8,192-token window, beating DeBERTaV3 on GLUE while using under a fifth of its memory and running roughly twice as fast. EuroBERT extends the same window to European languages. Against that, this project runs a five-aspect keyword lexicon feeding VADER compounds plus a RoBERTa head at 512 tokens, three classes, one language — accurate on its own corpus at aspect F1 0.87, above the 0.82 human-human benchmark, but architecturally a generation behind. The crisis engine is the opposite case: a rolling baseline with a 28-day z-score and a volume-spike test claiming 91% precision at 24–38 hours of lead time, in a field where the best 2026 academic work on stream-based early warning is paywalled and no commercial vendor publishes a lead-time figure of any kind. There is no benchmark to lose to.',
  ],
  stateOfTheArt: [
    {
      name: 'InstructABSA',
      org: 'Scaria et al., Arizona State University (NAACL 2024)',
      what: 'Instruction tuning for ABSA: every training sample carries positive, negative and neutral exemplars, and one ~200M Tk-Instruct model covers aspect-term extraction, polarity classification and joint pair extraction. It beats models seven times its size on extraction while losing on polarity to specialised encoders.',
      metric: 'ATE F1 92.10 (Rest14) and 92.30 (Lapt14); joint ASPE F1 79.47 (Rest14)',
      url: 'https://aclanthology.org/2024.naacl-short.63/',
      year: '2024',
    },
    {
      name: 'Arctic-ABSA',
      org: 'Liskowski & Jankowski (arXiv 2601.03940)',
      what: 'The first ABSA work written explicitly for commercial deployment: 17 aggregated public datasets across 92 domains, a corpus 20× larger than SemEval-2014, a 395M encoder and an 8B decoder, and a five-class label set that adds *mixed* and *unknown* to the usual three.',
      metric: 'Up to 10 points above GPT-4o and Claude 3.5 Sonnet; 87–91% across six languages from one model',
      url: 'https://arxiv.org/abs/2601.03940',
      year: '2026',
    },
    {
      name: 'ModernBERT',
      org: 'Answer.AI / LightOn / Hugging Face (arXiv 2412.13663)',
      what: 'A bidirectional encoder trained on 2 trillion tokens with a native 8,192-token context — sixteen times the 512 tokens most encoders still carry — at 149M and 395M parameters, designed for inference on ordinary GPUs.',
      metric: 'Beats DeBERTaV3 on GLUE at under 1/5 the memory; ~2× faster, up to 4× on mixed-length inputs',
      url: 'https://huggingface.co/blog/modernbert',
      year: '2024',
    },
    {
      name: 'EuroBERT',
      org: 'Boizard et al. (arXiv 2503.05500)',
      what: 'A multilingual encoder family for European languages at 210M, 610M and 2.1B parameters with native 8,192-token sequences, positioned as the multilingual counterpart to ModernBERT for classification and retrieval.',
      metric: 'Outperforms existing alternatives across multilingual, mathematics and coding tasks at 8,192 tokens',
      url: 'https://arxiv.org/abs/2503.05500',
      year: '2026',
    },
    {
      name: 'TopicGPT',
      org: 'Pham et al., NAACL 2024',
      what: 'Prompt-based topic modelling that emits natural-language topic labels with free-form descriptions instead of bags of words, and can be steered — split a topic, add a constraint — without retraining anything.',
      metric: 'Harmonic mean purity 0.74 vs 0.64 for the strongest baseline',
      url: 'https://arxiv.org/abs/2311.01449',
      year: '2024',
    },
    {
      name: 'BERTopic with LLM representation models',
      org: 'Maarten Grootendorst',
      what: 'The economical form of the same idea: cluster with embeddings, then send only the top keywords and the four most representative documents per topic to an LLM for a label. Supports OpenAI, Cohere, LlamaCPP, Ollama, LiteLLM and Hugging Face backends.',
      metric: 'One model call per topic rather than per document',
      url: 'https://maartengr.github.io/BERTopic/getting_started/representation/llm.html',
      year: '2026',
    },
    {
      name: 'LLM-as-a-judge evaluation',
      org: 'Zheng et al., NeurIPS 2023 · G-Eval · DeepEval',
      what: 'Strong LLM judges agree with human preferences at roughly the rate humans agree with each other, which makes automated grading of generated narratives viable. G-Eval reaches Spearman 0.514 with humans on summarisation; DeepEval reports running more than 10 million G-Eval metrics a day, and documents that scores drift unless the evaluation steps and rubric are pinned.',
      metric: 'Over 80% agreement with human preference (GPT-4 judge, MT-Bench)',
      url: 'https://arxiv.org/abs/2306.05685',
      year: '2023',
    },
    {
      name: 'Browser-side sentiment with Transformers.js',
      org: 'Hugging Face / Xenova',
      what: 'ONNX Runtime in the browser, WASM by default and WebGPU on opt-in, with q4 quantisation. A three-class social sentiment model, a zero-shot aspect classifier and a 384-dimensional embedding model all run client-side with no data leaving the page.',
      metric: 'Xenova/twitter-roberta-base-sentiment-latest at 25.3k downloads/month; the cardiffnlp original trained on ~124M tweets',
      url: 'https://huggingface.co/Xenova/twitter-roberta-base-sentiment-latest',
      year: '2026',
    },
  ],
  benchmarks: [
    {
      name: 'Aspect-level extraction and scoring (F1)',
      sota: '92.10 F1 — instruction-tuned aspect-term extraction on SemEval-2014 Restaurant',
      sotaBy: 'InstructABSA, NAACL 2024',
      project: '0.87 aspect F1 on the hospitality corpus, above the 0.82 human-human agreement benchmark — but from a five-keyword lexicon plus VADER, not an extraction model, and on a different dataset',
      sotaValue: 92.1,
      projectValue: 87,
      unit: 'F1 ×100',
      higherIsBetter: true,
    },
    {
      name: 'Sentiment classes carried per aspect',
      sota: '5 — positive, negative, neutral, mixed, unknown',
      sotaBy: 'Arctic-ABSA, January 2026',
      project: '3 — positive, negative, neutral',
      sotaValue: 5,
      projectValue: 3,
      unit: 'classes',
      higherIsBetter: true,
    },
    {
      name: 'Languages covered by one model',
      sota: '6, at 87–91% accuracy, without degrading English',
      sotaBy: 'Arctic-ABSA',
      project: '1 — English only',
      sotaValue: 6,
      projectValue: 1,
      unit: 'languages',
      higherIsBetter: true,
    },
    {
      name: 'Encoder context window (tokens)',
      sota: '8,192 native',
      sotaBy: 'ModernBERT / EuroBERT',
      project: '512 — RoBERTa, so long reviews and whole threads must be chunked',
      sotaValue: 8192,
      projectValue: 512,
      unit: 'tokens',
      higherIsBetter: true,
    },
    {
      name: 'Crisis early-warning lead time',
      sota: 'No published benchmark exists — the strongest 2026 academic work on stream-based early warning is behind a paywall, and no listening vendor publishes a lead-time, precision or false-alarm figure',
      project: '24–38 hours ahead of external escalation at 91% precision, from a rolling baseline, a 28-day z-score and a volume-spike test',
      higherIsBetter: true,
    },
  ],
  upgrades: [
    {
      title: 'Replace the keyword aspect extractor with an instruction-tuned ABSA model',
      body: 'The five-aspect lexicon can only find aspects someone listed, and it attributes the sentence-level VADER compound to every aspect it matches — which is why the sample response shows the same −0.3612 on value, location and amenities. Swapping in an instruction-tuned extraction head (the InstructABSA checkpoints are public: `kevinscaria/ate_tk-instruct-base-def-pos-neg-neut-combined` for extraction and `kevinscaria/atsc_tk-instruct-base-def-pos-combined` for polarity) gives genuinely per-aspect spans and per-aspect polarity at roughly 200M parameters. Keep the discriminative head for polarity, where the published numbers say specialised encoders still win.',
      impact: 'high',
      effort: 'weeks',
      status: 'planned',
    },
    {
      title: 'Add mixed and unknown to the sentiment scheme',
      body: '"Beautiful room, appalling front desk" is not a neutral review, and forcing it into one of three classes is the largest single source of avoidable error in hospitality text. Arctic-ABSA\'s five-class scheme — adding *mixed* and *unknown* — is the current commercial answer, and it changes the downstream product too: a mixed review is a routing decision, not a score, and an unknown one is a request for a human. The crisis baseline should be recomputed on the negative share alone rather than the mean compound once mixed exists.',
      impact: 'high',
      effort: 'weeks',
      status: 'planned',
    },
    {
      title: 'Publish a crisis-detection benchmark',
      body: 'The 91%-precision, 24–38-hour claim is measured internally and cannot be compared to anything, because no vendor and no public dataset offers a lead-time benchmark for brand crises. Building one — a labelled set of real incidents with a known external escalation timestamp, scored on lead time, precision, recall and false alarms per brand-month — turns the strongest part of this system into the only auditable number in the category. It is also the cheapest defensible moat here, since the evaluation set is the asset.',
      impact: 'high',
      effort: 'weeks',
      status: 'planned',
    },
    {
      title: 'Move the encoder to an 8,192-token window',
      body: 'Reviews are chunked at 512 tokens today, which loses the structure of long complaints and makes thread-level analysis impossible. ModernBERT gives a native 8,192-token window at 149M or 395M parameters, beats DeBERTaV3 on GLUE at under a fifth of the memory and runs about twice as fast, so this is a straight upgrade rather than a trade. It also makes the 117-feature TF-IDF/SVD block redundant for most of what it currently contributes.',
      impact: 'medium',
      effort: 'weeks',
      status: 'planned',
    },
    {
      title: 'Let the model author the aspect ontology',
      body: 'Eleven service dimensions were written by hand and five are actually scored. TopicGPT reaches purity 0.74 against human-annotated topics versus 0.64 for the strongest classical baseline precisely because the model proposes the labels; BERTopic\'s LLM representation modules make that affordable by calling the model once per cluster with its keywords and four representative documents. The product form is a proposed ontology diff a brand manager approves, with historical reviews re-scored under a versioned ontology id so trend lines survive the change.',
      impact: 'medium',
      effort: 'weeks',
      status: 'planned',
    },
    {
      title: 'Put an evaluation harness around the generated briefings',
      body: 'Llama 3.2 writes an executive brand briefing from aggregated metrics with no automated check that the narrative matches the numbers. A judge model scoring faithfulness against the source aggregates — with the evaluation steps and rubric pinned, which is what keeps LLM-as-judge scoring reproducible — converts a hallucinated figure from an embarrassment into a failed test. Strong judges agree with human preference at over 80%, about the rate humans agree with each other.',
      impact: 'medium',
      effort: 'weeks',
      status: 'planned',
    },
    {
      title: 'Take the aspect model multilingual',
      body: 'One English model is the binding constraint on selling to any hotel group outside the US. Arctic-ABSA shows a single model holding 87–91% across six languages without degrading English; EuroBERT provides an 8,192-token multilingual encoder at 210M–2.1B parameters. The aspect ontology stays language-independent and only the extraction head and the few-shot examples become per-locale.',
      impact: 'high',
      effort: 'months',
      status: 'planned',
    },
    {
      title: 'Run the live scorer in the browser',
      body: 'The demo, the in-app triage and any privacy-sensitive first pass do not need a server. Xenova/twitter-roberta-base-sentiment-latest gives three-class social sentiment client-side, Xenova/nli-deberta-v3-xsmall gives zero-shot aspect routing against an arbitrary label list with no training at all, and Xenova/all-MiniLM-L6-v2 produces the same 384-dimensional embeddings the server index uses. All three run under Transformers.js on ONNX Runtime with q4 quantisation.',
      impact: 'medium',
      effort: 'weeks',
      status: 'planned',
    },
  ],
  compliance: [
    {
      name: 'EU AI Act Article 50 — and the emotion-recognition duty',
      body: 'Article 50 applies from 2 August 2026, with a limited grace period to 2 December 2026 for marking obligations on pre-existing systems. Generated text — the executive briefing, the structured review analysis — must be marked in a machine-readable format and detectable as artificially generated. More pointedly for this system, Article 50(3) obliges deployers of emotion-recognition systems to inform the people exposed to them: sentiment and emotion scoring applied to identifiable reviewers is the paradigm case. Fines reach EUR 15 million or 3% of global annual turnover, and the Commission recognises a voluntary Code of Practice on Transparency as a compliance route.',
      url: 'https://digital-strategy.ec.europa.eu/en/faqs/transparency-obligations-under-article-50-ai-act',
    },
    {
      name: 'FTC 16 CFR Part 465 — and the tool-vendor precedent',
      body: 'The FTC rule on consumer reviews and testimonials took effect on 21 October 2024, banning AI-generated fake reviews, sentiment-conditioned compensation, undisclosed insider reviews and the suppression of negative reviews by threat or intimidation. The FTC Act civil-penalty ceiling has stood at USD 53,088 per violation since 17 January 2025. In Operation AI Comply the FTC brought an action against Rytr, an AI writing tool marketed for generating consumer reviews — the tool vendor, not only the poster — and the Chair\'s statement was explicit that "there is no AI exemption from the laws on the books".',
      url: 'https://www.ftc.gov/news-events/news/press-releases/2024/09/ftc-announces-crackdown-deceptive-ai-claims-schemes',
    },
    {
      name: 'The corpus is licensed, not owned',
      body: 'The Yelp Open Dataset — 6,990,280 reviews across 150,346 businesses — is published as a subset "intended for educational use", which is a research licence rather than a commercial one. Trustpilot\'s consumer terms (v7.0, February 2025) prohibit automated collection and prohibit text mining, data mining or scraping for any purpose, naming AI training explicitly. Any production deployment has to run on the brand\'s own first-party reviews or on licensed feeds; the vendors that operate at scale, such as Brandwatch with official firehose access to X and Tumblr, pay for that access.',
      url: 'https://business.yelp.com/data/resources/open-dataset/',
    },
    {
      name: 'GDPR — reviews are personal data, and alerts drive decisions',
      body: 'A review with an author handle identifies a natural person, so sentiment scoring of it is processing under the GDPR, with retention, access and erasure obligations that must propagate into the embedding index as well as the review store. Where an alert triggers a decision producing legal or similarly significant effects on an individual, Article 22 requires human intervention, the right to express a point of view and the right to contest — so a crisis playbook may recommend an action but must not execute one against a person.',
      url: 'https://gdpr-info.eu/art-22-gdpr/',
    },
  ],
  sources: [
    { title: 'InstructABSA: Instruction Learning for Aspect Based Sentiment Analysis', url: 'https://aclanthology.org/2024.naacl-short.63/', org: 'ACL Anthology / NAACL', date: '2024-06' },
    { title: 'InstructABSA (arXiv preprint, full results tables)', url: 'https://arxiv.org/abs/2302.08624', org: 'Scaria et al.', date: '2023-11' },
    { title: 'Large-Scale Aspect-Based Sentiment Analysis with Reasoning-Infused LLMs', url: 'https://arxiv.org/abs/2601.03940', org: 'Liskowski & Jankowski', date: '2026-01' },
    { title: 'Smarter, Better, Faster, Longer: ModernBERT', url: 'https://arxiv.org/abs/2412.13663', org: 'Answer.AI / LightOn', date: '2024-12' },
    { title: 'Finally, a replacement for BERT — ModernBERT announcement', url: 'https://huggingface.co/blog/modernbert', org: 'Hugging Face', date: '2024-12' },
    { title: 'EuroBERT: Scaling Multilingual Encoders for European Languages', url: 'https://arxiv.org/abs/2503.05500', org: 'Boizard et al.', date: '2026-06' },
    { title: 'TopicGPT: A Prompt-based Topic Modeling Framework', url: 'https://arxiv.org/abs/2311.01449', org: 'Pham et al., NAACL', date: '2024-04' },
    { title: 'BERTopic — LLM & Generative AI representation models', url: 'https://maartengr.github.io/BERTopic/getting_started/representation/llm.html', org: 'Maarten Grootendorst', date: '2026-09' },
    { title: 'Judging LLM-as-a-Judge with MT-Bench and Chatbot Arena', url: 'https://arxiv.org/abs/2306.05685', org: 'Zheng et al., NeurIPS', date: '2023-12' },
    { title: 'G-Eval: NLG Evaluation using GPT-4 with Better Human Alignment', url: 'https://arxiv.org/abs/2303.16634', org: 'Microsoft', date: '2023-05' },
    { title: 'G-Eval and LLM-as-a-judge metrics', url: 'https://deepeval.com/docs/metrics-llm-evals', org: 'Confident AI', date: '2026-09' },
    { title: 'Xenova/twitter-roberta-base-sentiment-latest', url: 'https://huggingface.co/Xenova/twitter-roberta-base-sentiment-latest', org: 'Hugging Face', date: '2026-09' },
    { title: 'cardiffnlp/twitter-roberta-base-sentiment-latest', url: 'https://huggingface.co/cardiffnlp/twitter-roberta-base-sentiment-latest', org: 'Cardiff NLP', date: '2026-09' },
    { title: 'Transformers.js documentation', url: 'https://huggingface.co/docs/transformers.js', org: 'Hugging Face', date: '2026-09' },
    { title: 'Transparency obligations under Article 50 of the AI Act', url: 'https://digital-strategy.ec.europa.eu/en/faqs/transparency-obligations-under-article-50-ai-act', org: 'European Commission', date: '2026-09' },
    { title: 'FTC announces crackdown on deceptive AI claims and schemes', url: 'https://www.ftc.gov/news-events/news/press-releases/2024/09/ftc-announces-crackdown-deceptive-ai-claims-schemes', org: 'FTC', date: '2024-09' },
    { title: 'FTC publishes inflation-adjusted civil penalty amounts for 2025', url: 'https://www.ftc.gov/news-events/news/press-releases/2025/02/ftc-publishes-inflation-adjusted-civil-penalty-amounts-2025', org: 'FTC', date: '2025-01' },
    { title: 'Yelp Open Dataset', url: 'https://business.yelp.com/data/resources/open-dataset/', org: 'Yelp', date: '2026-09' },
  ],
}

export default frontier
