/**
 * P15 · Facial Emotion Detection — the 2026 frontier.
 * Every claim below is backed by an entry in `sources`.
 */
import type { Frontier } from '../frontier'

const frontier: Frontier = {
  asOf: '2026-09',
  headline:
    'The engineering is sound and the latency budget is genuinely good, but the project is measured on a retired benchmark, publishes no number on the two datasets the field actually competes on, reports no CCC for the arousal-valence head it advertises, and — most consequentially — its stated buyer list includes two categories that the EU AI Act has either prohibited outright since 2 February 2025 or pushed into Annex III high-risk from 2 December 2027.',
  summary: [
    'Static facial-expression recognition has been a slow-moving benchmark race for three years, and the numbers say why: POSTER++ reached 92.21% on RAF-DB and 67.49% on AffectNet-7 in January 2023 with 8.4 GFLOPs and 43.7M parameters, and SRE-FER, posted on 9 August 2026, reports 92.76% on RAF-DB and 67.78% on AffectNet-7. Three and a half years of architecture work bought roughly half a point on RAF-DB and a third of a point on AffectNet. The ceiling is not the model; it is the label. AffectNet-7 sits in the high sixties because a seven-way forced choice over an in-the-wild face is not a well-posed problem, and no amount of attention pooling changes that. FER2013, which this project reports on, is no longer where the field competes at all — it is a 48x48 grayscale corpus that the leading 2026 papers do not benchmark against.',
    'The two directions that are still moving are temporal and linguistic. On the temporal side, the ABAW workshop series measures continuous valence and arousal on Aff-Wild2 with the Concordance Correlation Coefficient, and the numbers have roughly tripled in two editions: at the 8th ABAW (CVPR 2025) a DDAMFN-plus-LSTM entry took valence-arousal from an official baseline CCC of 0.22 to 0.479, and action-unit F1 from a 0.39 baseline to 0.411 (0.451 after threshold optimisation); at the 10th ABAW (2026) Team RAS reported a multimodal fusion reaching valence CCC 0.6078 and arousal CCC 0.7073 on the Aff-Wild2 development set, mean CCC 0.6576, with a 0.62 mean CCC on the test set. The lesson is consistent and directly applicable here: a sequence model over pooled per-frame features is worth far more than a better single-frame backbone, and arousal is a substantially easier target than valence. This project has an arousal-valence head and a smoothing layer but publishes no CCC for either, which means the strongest part of its architecture is also the least evidenced.',
    'On the linguistic side the field is abandoning the seven-class softmax altogether. Emotion-LLaMA (NeurIPS 2024) reasons over audio, vision and text and reports DFEW zero-shot UAR 45.59 / WAR 59.37 and MER2023-SEMI F1 0.9036; AffectGPT (January 2025) replaced fixed labels with the MER-Caption dataset, over 2,000 fine-grained emotion categories across 115K samples, evaluated on MER-UniBench; AffectGPT-RL (May 2026) optimises non-differentiable emotion-wheel metrics with reinforcement learning and reports state of the art on that benchmark. The shift is from classifying a face into one of seven boxes to describing what the face is doing and what it might mean in context — and that shift is the honest one, because Barrett et al. (2019) meta-analysed 47 studies and found average effect sizes of r = .32, with category-specific proportions between .15 and .25, concluding that facial configurations lack "sufficient reliability and specificity across contexts, individuals, and cultures to be considered diagnostic displays of any emotional state". A 2025 driving-simulator study makes the practical version of the point: 15 of 24 participants showed no detectable facial reaction at all to a critical event, fear was never the dominant reading, and the authors concluded that facial expression recognition "is not a reliable method for assessing perceived risk". The frontier answer is not a better classifier. It is a model that describes movement, reports calibrated uncertainty, abstains when there is no signal, and is deployed only where a person has said yes.',
  ],
  stateOfTheArt: [
    {
      name: 'SRE-FER',
      org: 'arXiv 2608.08702',
      what: 'Regional residual evidence learning with action-unit guidance, aimed at local evidence dilution in fine-grained expression recognition. The current verifiable leader on the two datasets the field competes on, and the clearest demonstration that static FER has plateaued.',
      metric: 'RAF-DB 92.76% · AffectNet-7 67.78%',
      url: 'https://arxiv.org/abs/2608.08702',
      year: '2026',
    },
    {
      name: 'POSTER++',
      org: 'Mao, Xu, Yin, Chang, Nie, Huang',
      what: 'Cross-attention between image features and facial-landmark features at multiple scales, replacing the original POSTER pyramid. Still the reference efficiency point for the whole static-FER literature and the model most 2025-26 papers are measured against.',
      metric: 'RAF-DB 92.21% · AffectNet-7 67.49% · AffectNet-8 63.77% · 8.4 GFLOPs · 43.7M params',
      url: 'https://arxiv.org/abs/2301.12149',
      year: '2023',
    },
    {
      name: 'Aff-Wild2 valence-arousal, 10th ABAW',
      org: 'Team RAS (arXiv 2603.13056)',
      what: 'Multimodal fusion for continuous valence and arousal on Aff-Wild2, the in-the-wild audiovisual corpus the ABAW competition series is built on. This is where the continuous-affect state of the art is actually measured, using the Concordance Correlation Coefficient rather than accuracy.',
      metric: 'Valence CCC 0.6078 · Arousal CCC 0.7073 · mean CCC 0.6576 (dev) · 0.62 mean CCC (test)',
      url: 'https://arxiv.org/abs/2603.13056',
      year: '2026',
    },
    {
      name: 'DDAMFN + LSTM (8th ABAW)',
      org: 'Cabacas-Maso, Ortega-Beltran, Benito-Altamirano, Ventura',
      what: 'A dual-direction attention mixed feature network run across all three ABAW tasks with a temporal LSTM, plus a CLIP variant for expression recognition. The clean ablation that shows what temporal modelling is worth over a per-frame backbone.',
      metric: 'Valence-arousal CCC 0.479 vs 0.22 baseline · AU F1 0.451 vs 0.39 baseline · expression F1 0.341 vs 0.25 baseline',
      url: 'https://arxiv.org/abs/2503.12260',
      year: '2025',
    },
    {
      name: 'AffectGPT and AffectGPT-RL',
      org: 'Lian et al., Institute of Automation CAS',
      what: 'The open-vocabulary turn. AffectGPT introduced MER-Caption, over 2,000 fine-grained emotion categories across 115K samples, and MER-UniBench to score both traditional and natural-language emotion tasks; AffectGPT-RL treats emotion-wheel distance as a reward and optimises it with reinforcement learning.',
      metric: 'MER-Caption: 115K samples, 2,000+ emotion categories; state of the art on MER-UniBench',
      url: 'https://arxiv.org/abs/2605.06126',
      year: '2026',
    },
    {
      name: 'Emotion-LLaMA',
      org: 'Cheng et al., NeurIPS 2024',
      what: 'A multimodal LLM with audio, visual and text encoders instruction-tuned on the MERR dataset (28,618 coarse and 4,487 fine-grained samples) to both recognise and explain emotion. The reference point for whether a describing model can beat a classifier on unseen data.',
      metric: 'DFEW zero-shot UAR 45.59 / WAR 59.37 · MER2023-SEMI F1 0.9036 · EMER clue overlap 7.83',
      url: 'https://arxiv.org/abs/2406.11161',
      year: '2024',
    },
    {
      name: 'Xenova/facial_emotions_image_detection',
      org: 'Hugging Face · Transformers.js',
      what: 'A quantised ONNX conversion of a ViT-base expression classifier, packaged for Transformers.js. This is the exact repo id to load for an in-browser demo: no server, no upload, the frame never leaves the device.',
      metric: 'ViT architecture · transformers.js + onnx tags · 9.9K downloads/month · updated 27 June 2025',
      url: 'https://huggingface.co/Xenova/facial_emotions_image_detection',
      year: '2025',
    },
    {
      name: 'AdamCodd/YOLOv11n-face-detection',
      org: 'Hugging Face',
      what: 'A nano YOLOv11 face detector trained for 225 epochs on WIDER FACE, published with ONNX weights under Apache-2.0. The detector half of a browser pipeline, replacing MTCNN with something that runs under onnxruntime-web.',
      metric: 'WIDER FACE AP: easy 0.942 · medium 0.921 · hard 0.810 · Apache-2.0',
      url: 'https://huggingface.co/AdamCodd/YOLOv11n-face-detection',
      year: '2025',
    },
    {
      name: 'onnx-community/face-emotion-detection-ONNX',
      org: 'Hugging Face · ONNX Community',
      what: 'A second Transformers.js-compatible ViT expression classifier, published 29 August 2026 under Apache-2.0 and tagged to FER2013 — the same corpus this project trains on, which makes it a direct browser-side comparator rather than a substitute.',
      metric: 'ViT · transformers.js · Apache-2.0 · dataset FER2013 · published 29 August 2026',
      url: 'https://huggingface.co/onnx-community/face-emotion-detection-ONNX',
      year: '2026',
    },
  ],
  benchmarks: [
    {
      name: 'RAF-DB, 7-class accuracy',
      sota: '92.76%',
      sotaBy: 'SRE-FER, August 2026',
      project: 'Not published — RAF-DB is described as held out for external validation but no figure is reported',
      sotaValue: 92.76,
      unit: '%',
      higherIsBetter: true,
    },
    {
      name: 'AffectNet-7, accuracy',
      sota: '67.78%',
      sotaBy: 'SRE-FER, August 2026 (POSTER++ 67.49% in 2023)',
      project: 'Not published — AffectNet supplies ~450k training images but no AffectNet test accuracy is reported',
      sotaValue: 67.78,
      unit: '%',
      higherIsBetter: true,
    },
    {
      name: 'FER2013 private test, accuracy',
      sota: 'Effectively retired — the 2026 leaders benchmark on RAF-DB and AffectNet, not FER2013',
      project: '72.4% (human annotator agreement on this corpus is approximately 65%)',
      projectValue: 72.4,
      unit: '%',
      higherIsBetter: true,
    },
    {
      name: 'Aff-Wild2 valence-arousal, mean CCC',
      sota: '0.62 test / 0.6576 dev (valence 0.6078, arousal 0.7073)',
      sotaBy: 'Team RAS, 10th ABAW 2026',
      project: 'No CCC reported — the arousal-valence head ships without a concordance figure on any public corpus',
      sotaValue: 0.62,
      unit: 'CCC',
      higherIsBetter: true,
    },
    {
      name: 'Action-unit detection, F1 (ABAW)',
      sota: '0.451 with threshold optimisation (0.411 raw) against a 0.39 baseline',
      sotaBy: 'DDAMFN + LSTM, 8th ABAW 2025',
      project: 'No AU F1 reported — the multi-label FACS head is described but never scored',
      sotaValue: 0.451,
      unit: 'F1',
      higherIsBetter: true,
    },
    {
      name: 'Emotion label vocabulary',
      sota: '2,000+ fine-grained categories (MER-Caption, open vocabulary)',
      sotaBy: 'AffectGPT, 2025-26',
      project: '7 fixed classes plus a two-dimensional circumplex position',
      sotaValue: 2000,
      projectValue: 7,
      unit: 'categories',
      higherIsBetter: true,
    },
  ],
  upgrades: [
    {
      title: 'Publish RAF-DB and AffectNet numbers, or stop citing them',
      body: 'The module says RAF-DB is held out for external validation and that AffectNet supplies roughly 450k training images, then reports accuracy only on FER2013 — a 48x48 grayscale corpus the 2026 leaders no longer benchmark. Evaluating the existing ONNX graph on RAF-DB and AffectNet-7/-8 is an afternoon of work and is the single highest-value change here: it converts an unfalsifiable claim into a comparable one against SRE-FER at 92.76% / 67.78% and POSTER++ at 92.21% / 67.49% / 63.77%. Expect the AffectNet number to land well below the FER2013 headline; that is the point.',
      impact: 'high',
      effort: 'days',
    },
    {
      title: 'Report CCC for the arousal-valence head on Aff-Wild2',
      body: 'The continuous head is the architecturally strongest part of the system and the least evidenced. Score it against the Aff-Wild2 splits used by the ABAW competition and report valence CCC and arousal CCC separately, because they behave differently: the 10th ABAW leader reached 0.6078 on valence and 0.7073 on arousal, and reporting a single blended number hides which half is working. This also gives the product a defensible primary signal that does not depend on the seven-class taxonomy.',
      impact: 'high',
      effort: 'weeks',
    },
    {
      title: 'Put a sequence model where the EMA is',
      body: 'Exponential moving average with hysteresis is a display filter, not a model — it cannot recover information the per-frame backbone never had. The 8th ABAW ablation moved valence-arousal CCC from a 0.22 baseline to 0.479 by putting an LSTM over pooled features, and the 10th ABAW leader used multimodal temporal fusion to reach 0.62 on test. A light bidirectional GRU or temporal transformer over the last 16 pooled 1792-dimensional vectors is a small addition to the ONNX graph and is where the remaining accuracy in Fear and Disgust actually lives, since both classes are carried by the transition rather than the frame.',
      impact: 'high',
      effort: 'weeks',
    },
    {
      title: 'Ship the browser pipeline and stop moving video',
      body: 'Transformers.js runs ONNX Runtime in the browser over WASM on CPU or WebGPU on GPU, which removes the network hop and the entire class of "where did my face go" objections. The two-stage pipeline is available today as published repos: AdamCodd/YOLOv11n-face-detection for detection (WIDER FACE AP 0.942 easy / 0.921 medium / 0.810 hard, Apache-2.0, ONNX weights) and Xenova/facial_emotions_image_detection or onnx-community/face-emotion-detection-ONNX for the classifier, both Transformers.js-compatible ViT graphs. Only the resulting vectors leave the device, which makes the consent story structural instead of contractual.',
      impact: 'high',
      effort: 'weeks',
    },
    {
      title: 'Add abstention and calibrated uncertainty',
      body: 'A softmax always returns a class. In the 2025 automated-driving study, 15 of 24 participants showed no detectable facial reaction to a critical event at all — a system that must emit a label will emit a wrong one for every one of them. Add an explicit no-reliable-signal state driven by the calibrated top-1 confidence, the attention-map entropy and the AU activation floor, and report coverage alongside accuracy. This is the change that makes the honest claim ("no measurable facial response") sayable.',
      impact: 'high',
      effort: 'weeks',
    },
    {
      title: 'Run and publish a demographic performance audit',
      body: 'The ICO warned in October 2022 that emotion-analysis systems risk "systemic bias, inaccuracy and even discrimination" and that it would investigate organisations deploying them irresponsibly; Annex III classification will require the same evidence under the AI Act from 2 December 2027. Break RAF-DB and an internal held-out set down by apparent age band, skin tone, spectacles, facial hair and yaw, publish per-group accuracy and per-group abstention rate, and gate any release on the worst group rather than the mean.',
      impact: 'high',
      effort: 'weeks',
    },
    {
      title: 'Replace the seven-class headline with a describing head',
      body: 'The categorical taxonomy is the part of the system the science does not support. Distil an open-vocabulary description layer in the AffectGPT / Emotion-LLaMA direction: report the observed facial movement in FACS terms, the continuous valence and arousal, and a short natural-language description that is explicitly about the face, not about the inner state. AffectGPT works over 2,000-plus fine-grained categories precisely because seven does not survive contact with real footage. Keep the seven-class output as a legacy field, not as the headline.',
      impact: 'medium',
      effort: 'months',
    },
    {
      title: 'Encode the lawful-use boundary in the software',
      body: 'The current buyer list includes in-store sentiment and driver monitoring. Article 5(1)(f) has prohibited emotion inference in workplace and education contexts across the EU since 2 February 2025, with fines up to EUR 35,000,000 or 7% of worldwide annual turnover, and every other emotion-recognition deployment falls under Annex III point 1(c) with Article 50(3) transparency duties. Make deployment context a required, attested field on every API key; refuse workplace and education contexts at the token level rather than in a contract; and emit an Article 50(3) disclosure artefact and a consent record with every session.',
      impact: 'high',
      effort: 'weeks',
    },
  ],
  compliance: [
    {
      name: 'EU AI Act Article 5(1)(f) — prohibited practice',
      body: 'The Act prohibits "the use of AI systems to infer emotions of a natural person in the areas of workplace and education institutions, except where the use of the AI system is intended to be put in place or into the market for medical or safety reasons". This has applied since 2 February 2025. It is a prohibition, not a compliance burden: there is no conformity assessment that makes classroom or employee emotion inference lawful, and the medical/safety carve-out is narrow and purpose-bound. Under Article 99, breaching Article 5 carries administrative fines up to EUR 35,000,000 or, for an undertaking, up to 7% of total worldwide annual turnover for the preceding financial year, whichever is higher.',
      url: 'https://artificialintelligenceact.eu/article/5/',
    },
    {
      name: 'EU AI Act Annex III 1(c) and Article 50(3) — high risk plus transparency',
      body: 'Every emotion-recognition system outside the Article 5 prohibition is listed in Annex III point 1(c) as high risk, and Article 50(3) requires deployers to inform the natural persons exposed to the system of its operation and to process personal data in accordance with the GDPR. The 2026 Digital Omnibus on AI, in force 27 July 2026, moved the applicability of the Annex III high-risk obligations from 2 August 2026 to 2 December 2027 (Annex I product-embedded systems move to 2 August 2028) — a deferral, not a repeal, and it does not touch the Article 5 prohibitions, which remain applicable from 2 February 2025.',
      url: 'https://digital-strategy.ec.europa.eu/en/news/ai-omnibus-enters-force',
    },
    {
      name: 'GDPR Article 9 — special categories and explicit consent',
      body: 'Article 9(1) prohibits processing of "biometric data for the purpose of uniquely identifying a natural person" among other special categories. Emotion inference is not identification, so Article 9 does not bite automatically on that limb — but it does apply the moment an inference reveals data concerning health, and facial imagery of an identifiable participant is personal data regardless. The defensible posture is to obtain Article 9(2)(a) explicit consent for a specified purpose anyway, run a DPIA, and keep the consent record joined to every session, rather than to argue the exemption.',
      url: 'https://gdpr-info.eu/art-9-gdpr/',
    },
    {
      name: 'Illinois BIPA (740 ILCS 14)',
      body: 'BIPA requires written notice and a written release before collecting a face scan, and provides liquidated damages of USD 1,000 per negligent violation and USD 5,000 per intentional or reckless violation. Public Act 103-0769, effective 2 August 2024, limited recovery to a single award per person per method of collection, overturning the per-scan accrual reading; the Seventh Circuit has since held that amendment retroactive. The cap changed; the notice-and-release requirement did not, and a consented research panel satisfies it only if the release is written, specific and retained.',
    },
    {
      name: 'UK ICO warning on emotion analysis',
      body: 'On 26 October 2022 the ICO warned organisations against biometric emotion analysis. Deputy Commissioner Stephen Bonner said "Developments in the biometrics and emotion AI market are immature. They may not work yet, or indeed ever", that "the only sustainable biometric deployments will be those that are fully functional, accountable and backed by science", and that "as it stands, we are yet to see any emotion AI technology develop in a way that satisfies data protection requirements". The ICO said it would investigate organisations that fail to act responsibly. The correct reading is not that measurement is forbidden but that unevidenced claims about inner states are the exposure.',
    },
  ],
  sources: [
    {
      title: 'Article 5: Prohibited AI Practices',
      url: 'https://artificialintelligenceact.eu/article/5/',
      org: 'EU Artificial Intelligence Act (Future of Life Institute explorer)',
      date: '2026-09',
    },
    {
      title: 'Annex III: High-Risk AI Systems Referred to in Article 6(2)',
      url: 'https://artificialintelligenceact.eu/annex/3/',
      org: 'EU Artificial Intelligence Act',
      date: '2026-09',
    },
    {
      title: 'Article 50: Transparency Obligations for Providers and Deployers of Certain AI Systems',
      url: 'https://artificialintelligenceact.eu/article/50/',
      org: 'EU Artificial Intelligence Act',
      date: '2026-09',
    },
    {
      title: 'Article 99: Penalties',
      url: 'https://artificialintelligenceact.eu/article/99/',
      org: 'EU Artificial Intelligence Act',
      date: '2026-09',
    },
    {
      title: 'AI Omnibus enters into force',
      url: 'https://digital-strategy.ec.europa.eu/en/news/ai-omnibus-enters-force',
      org: 'European Commission, Shaping Europe\'s digital future',
      date: '2026-07',
    },
    {
      title: 'AI Act implementation timeline',
      url: 'https://artificialintelligenceact.eu/implementation-timeline/',
      org: 'EU Artificial Intelligence Act',
      date: '2026-09',
    },
    {
      title: 'Art. 9 GDPR — Processing of special categories of personal data',
      url: 'https://gdpr-info.eu/art-9-gdpr/',
      org: 'Regulation (EU) 2016/679',
    },
    {
      title: 'Immature biometric technologies could be discriminating against people, says ICO in warning to organisations',
      url: 'https://www.wired-gov.net/wg/news.nsf/articles/Immature+biometric+technologies+could+be+discriminating+against+people+says+ICO+in+warning+to+organisations+26102022091000',
      org: 'Information Commissioner\'s Office press release',
      date: '2022-10',
    },
    {
      title: 'Emotional Expressions Reconsidered: Challenges to Inferring Emotion From Human Facial Movements',
      url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC6640856/',
      org: 'Barrett, Adolphs, Marsella, Martinez & Pollak · Psychological Science in the Public Interest 20(1), 1-68',
      date: '2019-07',
    },
    {
      title: 'POSTER++: A simpler and stronger facial expression recognition network',
      url: 'https://arxiv.org/abs/2301.12149',
      org: 'Mao, Xu, Yin, Chang, Nie & Huang · arXiv 2301.12149',
      date: '2023-01',
    },
    {
      title: 'SRE-FER: Regional residual evidence learning for mitigating local evidence dilution in fine-grained facial expression recognition',
      url: 'https://arxiv.org/abs/2608.08702',
      org: 'arXiv 2608.08702',
      date: '2026-08',
    },
    {
      title: 'Enhancing Facial Expression Recognition through Dual-Direction Attention Mixed Feature Networks and CLIP: Application to 8th ABAW Challenge',
      url: 'https://arxiv.org/abs/2503.12260',
      org: 'Cabacas-Maso, Ortega-Beltran, Benito-Altamirano & Ventura · CVPR 2025 Workshops',
      date: '2025-03',
    },
    {
      title: 'Team RAS in 10th ABAW Competition: Multimodal Valence and Arousal Estimation Approach',
      url: 'https://arxiv.org/abs/2603.13056',
      org: 'arXiv 2603.13056',
      date: '2026-03',
    },
    {
      title: 'Emotion-LLaMA: Multimodal Emotion Recognition and Reasoning with Instruction Tuning',
      url: 'https://arxiv.org/abs/2406.11161',
      org: 'Cheng et al. · NeurIPS 2024',
      date: '2024-06',
    },
    {
      title: 'AffectGPT: A New Dataset, Model, and Benchmark for Emotion Understanding with Multimodal Large Language Models',
      url: 'https://arxiv.org/abs/2501.16566',
      org: 'Lian et al. · arXiv 2501.16566',
      date: '2025-01',
    },
    {
      title: 'AffectGPT-RL: Revealing Roles of Reinforcement Learning in Open-Vocabulary Emotion Recognition',
      url: 'https://arxiv.org/abs/2605.06126',
      org: 'Lian et al. · arXiv 2605.06126',
      date: '2026-05',
    },
    {
      title: 'Facial Emotion Recognition does not detect feeling unsafe in automated driving',
      url: 'https://arxiv.org/abs/2509.04490',
      org: 'van Elburg, Gkentsidis, Sarrazin, Barendswaard, Kotian & Happee · arXiv 2509.04490',
      date: '2025-09',
    },
    {
      title: 'Xenova/facial_emotions_image_detection',
      url: 'https://huggingface.co/Xenova/facial_emotions_image_detection',
      org: 'Hugging Face model card (Transformers.js, ONNX)',
      date: '2025-06',
    },
    {
      title: 'AdamCodd/YOLOv11n-face-detection',
      url: 'https://huggingface.co/AdamCodd/YOLOv11n-face-detection',
      org: 'Hugging Face model card (ONNX, WIDER FACE)',
      date: '2025-11',
    },
    {
      title: 'onnx-community/face-emotion-detection-ONNX',
      url: 'https://huggingface.co/onnx-community/face-emotion-detection-ONNX',
      org: 'Hugging Face model card (Transformers.js, ONNX, FER2013)',
      date: '2026-08',
    },
    {
      title: 'Transformers.js documentation',
      url: 'https://huggingface.co/docs/transformers.js/index',
      org: 'Hugging Face — ONNX Runtime in the browser via WASM or WebGPU',
      date: '2026-09',
    },
  ],
}

export default frontier
