import type { Frontier } from '../frontier'

const frontier: Frontier = {
  asOf: '2026-09',
  headline:
    'The project holds a near-perfect score on a benchmark that stopped deciding anything: 2026 malaria microscopy AI is judged on slide-level sensitivity, species identification and WHO-standard parasite density from field-prepared films, and on all three the project currently has no number at all.',
  summary: [
    'WHO put the 2024 burden at 282 million cases and 610 000 deaths, roughly 9 million more cases than the year before, against US$ 3.9 billion of malaria funding versus the US$ 9.3 billion 2025 target, with reductions in official development assistance already disrupting routine surveillance. At the same time the diagnostic that carries most of the testing load is failing in places: parasites with pfhrp2/pfhrp3 deletions are invisible to HRP2 rapid tests, and WHO reported in April 2026 that in countries in the Horn of Africa up to 80% of cases were missed, prequalifying three pf-LDH rapid tests in response. Every one of those pressures pushes work back onto microscopy, which is why automated microscopy is the part of malaria diagnostics attracting real money and real regulators in 2026.',
    'The systems that define the frontier are not cell classifiers. Noul miLab MAL is a fully integrated bench-top digital microscope that stains, images and reads a 5 microlitre sample, examines 200 000 red cells in about 15 minutes against roughly 1 000 in a manual read, reports species and parasitaemia, and returned 100% sensitivity and specificity on 408 Labcorp reference-laboratory samples, catching two P. falciparum cases below 0.1% parasitaemia that experienced microscopists had missed; Benin has placed an initial order of 20 units. Motic EasyScan GO is the honest field benchmark: 2 250 Giemsa films read at 11 sites gave 91.1% slide-level sensitivity (95% CI 88.9-92.7) and 75.6% specificity, rising to 85.1% on good-quality slides, with species called correctly in 93% of P. falciparum and 92% of P. vivax cases, meeting WHO-TDR competence level 2 for detection but only level 4 for quantification, since just 23% of slides (196/845) landed within plus or minus 25% of the expert density. In August 2026 a fully offline YOLOv13n pipeline reported mAP@0.5 of 0.863 and a slide-level parasitaemia correlation of r = 0.951 across four species, with per-image correlation of only 0.812, which is the clearest statement yet that aggregation, not per-cell accuracy, is where the diagnostic signal lives.',
    'Against that, this project trains two ImageNet-pretrained backbones on 27 558 pre-segmented single-cell crops from 200 donors at one hospital, imaged with one smartphone on one microscope and stained one way. The engineering is careful: patient-level splits, a sensitivity-first threshold, Grad-CAM agreeing with pathologist annotations at IoU 0.71, 30-pass MC-dropout routing to human review, INT8 ONNX at about 12 ms per cell on CPU. The problem is the unit of analysis. A 0.97 cell-level AUC on curated crops is not slide-level clinical sensitivity: the hardest part of a real read is finding and segmenting candidate objects in a noisy field, and thin smears alone yield neither the parasite density that drives treatment decisions nor reliable identification of the species that determine which treatment. Closing that gap is a pipeline problem and a data problem, not a backbone problem, and the pathology foundation models released since 2024 mean the backbone half is now largely a matter of choosing a licence.',
  ],
  stateOfTheArt: [
    {
      name: 'miLab MAL',
      org: 'Noul',
      what: 'The first commercially available fully integrated AI-supported automated microscope for clinical malaria, combining robotic staining and imaging with deep learning on a 5 microlitre finger-prick or venous sample. It reports species and parasitaemia as a percentage and suspected parasites per microlitre, and is the only digital-microscope malaria solution featured in the WHO-Unitaid malaria diagnostic landscape report.',
      metric: '100% sensitivity and specificity on 408 Labcorp reference-laboratory samples; 200 000 RBCs examined in 15 minutes; Benin initial order of 20 units',
      url: 'https://noul.com/en/product-mal/',
      year: '2026',
    },
    {
      name: 'EasyScan GO',
      org: 'Motic and the Global Good Fund',
      what: 'A machine-learning digital malaria microscope operating on thick films, evaluated in the largest independent multi-site field study of automated malaria microscopy to date. It remains the reference point for what an autonomous reader actually achieves on slides prepared under field conditions rather than in a curated corpus.',
      metric: 'Slide-level sensitivity 91.1% (95% CI 88.9-92.7), specificity 75.6% on 2 250 films at 11 sites; WHO-TDR level 2 for detection, level 4 for quantification',
      url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC9004086/',
      year: '2022',
    },
    {
      name: 'On-Device Multi-Species Malaria Detection with Uncertainty-Calibrated Slide-Level Aggregation',
      org: 'Seidu, Issah, Delahunt and Mukamakuza (arXiv:2608.08566)',
      what: 'A YOLOv13n detector shipped through TensorFlow Lite that runs entirely offline, aggregates per-image detections into slide-level parasitaemia with WHO-standard quantification using soft counting over ten images per slide, and adds stopping criteria, uncertainty quantification and explicit human-in-the-loop review. This is the architecture the frontier has converged on: detection, then calibrated aggregation, then triage.',
      metric: 'mAP@0.5 0.863; slide-level parasitaemia correlation r = 0.951 versus r = 0.812 per image; 10.27 ± 1.65 s per image on device; four species plus white blood cells across 2 739 annotated images',
      url: 'https://arxiv.org/abs/2608.08566',
      year: '2026',
    },
    {
      name: 'Towards Field-Ready AI-based Malaria Diagnosis: A Continual Learning Approach',
      org: 'Guillon, Dorkenoo, Piarroux and colleagues (arXiv:2507.23648)',
      what: 'Frames deployment across new clinics as domain-incremental learning, in which a YOLO detector must adapt to a new acquisition site without losing performance on the sites it already serves, and compares two rehearsal-based and two regularisation-based strategies on a multi-site clinical thin-smear dataset. It names the failure mode that single-site benchmarks hide: limited generalisation across sites with varying conditions.',
      metric: 'Rehearsal-based continual learning gave the largest gains across sites',
      url: 'https://arxiv.org/abs/2507.23648',
      year: '2025',
    },
    {
      name: 'UNI',
      org: 'Mahmood Lab, Harvard Medical School',
      what: 'A DINOv2 ViT-L/16 encoder pretrained on 100 402 H&E whole-slide images totalling 100 130 900 tiles, published in Nature Medicine as a general-purpose foundation model for computational pathology. It establishes the 2026 default: a frozen pathology encoder with a light task head, rather than fine-tuning an ImageNet backbone per task. The CC-BY-NC-ND 4.0 licence and gated access restrict it to non-commercial research.',
      metric: 'State-of-the-art across 34 clinical tasks; 100 402 WSIs, 100 130 900 pretraining images',
      url: 'https://huggingface.co/MahmoodLab/UNI',
      year: '2024',
    },
    {
      name: 'Virchow2',
      org: 'Paige and Microsoft Research',
      what: 'A 632 million-parameter ViT-H/14 tile encoder producing 1280-dimensional embeddings, pretrained on 3.1 million whole-slide images from Memorial Sloan Kettering at mixed magnifications of 5x, 10x, 20x and 40x. The mixed-magnification training matters for blood films specifically, because parasite morphology is read at oil immersion while field selection happens at low power. Released under CC-BY-NC-ND 4.0.',
      metric: '3.1M WSIs; 632M parameters; 1280-d embeddings; 32 layers, 16 heads, SwiGLU',
      url: 'https://huggingface.co/paige-ai/Virchow2',
      year: '2024',
    },
    {
      name: 'GigaPath-Flash',
      org: 'Microsoft Research and Providence (arXiv:2607.18218)',
      what: 'The efficiency successor to Prov-GigaPath, pairing a 22M-parameter ViT-S tile encoder with a 21M-parameter LongNet slide encoder and released with open weights under Apache-2.0. For a project that has to run offline on clinic hardware, this is the one frontier encoder whose licence and compute budget both permit deployment.',
      metric: '97% of GigaPath average slide-level performance at 50x less compute; Apache-2.0 open weights',
      url: 'https://arxiv.org/abs/2607.18218',
      year: '2026',
    },
    {
      name: 'Transformers.js ONNX image backbones',
      org: 'Hugging Face (onnx-community and Xenova)',
      what: 'Browser-runnable ONNX conversions that make a live in-browser cell demo possible with no server: onnx-community/mobilenetv4_conv_small.e2400_r224_in1k (used by the Xenova/webgpu-mobilenet and Xenova/mobilenet-wasm Spaces), Xenova/vit-base-patch16-224 for a ViT-B/16 classifier matching the project second backbone, Xenova/mobilevit-small as a hybrid CNN-transformer, and Xenova/dinov2-small for image-feature-extraction and nearest-neighbour retrieval over a reference cell bank. All four load through the image-classification or image-feature-extraction pipeline in @huggingface/transformers.',
      metric: 'ONNX weights in an onnx/ subfolder; WebGPU and WASM execution providers; mobilenetv4_conv_small at 917 downloads last month, Xenova/dinov2-small at 150.0K',
      url: 'https://huggingface.co/onnx-community/mobilenetv4_conv_small.e2400_r224_in1k',
      year: '2026',
    },
    {
      name: 'BBBC041 and MP-IDB',
      org: 'Broad Bioimage Benchmark Collection; Loddo and colleagues',
      what: 'The annotated corpora that support the tasks the NIH cell set cannot. BBBC041 gives 1 364 Giemsa thin-smear images with roughly 80 000 cells carrying bounding boxes and six classes (uninfected red cells, leukocytes, rings, trophozoites, gametocytes, schizonts) plus a difficult flag, drawn from Brazil, South-East Asia and a time-course study, under CC BY-NC-SA 3.0. MP-IDB adds all four human species (falciparum, malariae, ovale, vivax) crossed with all four life-cycle stages.',
      metric: '1 364 images, about 80 000 annotated cells, 6 classes (BBBC041); 4 species x 4 stages (MP-IDB)',
      url: 'https://bbbc.broadinstitute.org/BBBC041',
      year: '2019',
    },
  ],
  benchmarks: [
    {
      name: 'Slide-level parasite detection sensitivity, field-prepared films',
      sota: '91.1% (95% CI 88.9-92.7) across 2 250 Giemsa films at 11 sites',
      sotaBy: 'Motic EasyScan GO, Malaria Journal 2022',
      project: 'Not measured. The reported 94% is cell-level sensitivity on 1 375 pre-segmented crops from a single hospital, which is a different and much easier task',
      sotaValue: 91.1,
      unit: '%',
      higherIsBetter: true,
    },
    {
      name: 'Parasite density agreement with expert microscopy',
      sota: '23% of slides (196/845) within plus or minus 25% of the expert density; 3-10 fold variation elsewhere',
      sotaBy: 'Motic EasyScan GO (WHO-TDR competence level 4 for quantification)',
      project: 'No density output at all. A thin-smear cell classifier produces no parasites per microlitre, which is the number that drives severity triage and treatment monitoring',
      sotaValue: 23,
      projectValue: 0,
      unit: '% of slides within ±25%',
      higherIsBetter: true,
    },
    {
      name: 'Slide-level parasitaemia correlation with reference counts',
      sota: 'r = 0.951 at slide level from 10 images per slide, versus r = 0.812 per image',
      sotaBy: 'Seidu et al., arXiv:2608.08566, August 2026',
      project: 'No aggregation stage. Per-cell probabilities are never combined into a slide-level estimate, so the correlation is undefined',
      sotaValue: 0.951,
      projectValue: 0,
      unit: 'Pearson r',
      higherIsBetter: true,
    },
    {
      name: 'Species identification accuracy',
      sota: '93% for P. falciparum (kappa 0.76, 95% CI 0.69-0.83) and 92% for P. vivax (kappa 0.73, 95% CI 0.66-0.80)',
      sotaBy: 'Motic EasyScan GO; Noul miLab MAL reports P. falciparum and P. vivax with suggestions for other species',
      project: 'Binary parasitised versus uninfected only. Every infected donor in the NIH corpus carries P. falciparum, so the model has never seen another species',
      sotaValue: 93,
      projectValue: 0,
      unit: '% correctly speciated',
      higherIsBetter: true,
    },
    {
      name: 'Red cells examined per patient',
      sota: '200 000 red cells in 15 minutes, against roughly 1 000 in a manual read',
      sotaBy: 'Noul miLab MAL',
      project: 'About 75 000 cells in the same 15 minutes at the measured 12 ms per crop on one CPU core (modelled from the per-image latency, not benchmarked end to end), and only if an upstream segmenter supplies the crops, which this pipeline does not have',
      sotaValue: 200000,
      projectValue: 75000,
      unit: 'cells per 15 min',
      higherIsBetter: true,
    },
    {
      name: 'Encoder pretraining scale',
      sota: '100 402 whole-slide images and 100 130 900 tiles (UNI); 3.1 million whole-slide images (Virchow2)',
      sotaBy: 'Mahmood Lab; Paige',
      project: '27 558 single-cell crops from 200 donors at one hospital, on top of ImageNet weights. No whole-slide pretraining at all',
      sotaValue: 100402,
      projectValue: 0,
      unit: 'whole-slide images',
      higherIsBetter: true,
    },
  ],
  upgrades: [
    {
      title: 'Re-baseline every headline number at slide level',
      body: 'Relabel the current metrics as cell-level and stop presenting 0.97 AUC as a diagnostic figure. Build an evaluation harness whose unit is a slide, not a crop: sensitivity and specificity against an expert read, parasites per microlitre against a reference count, and a stratification by parasite density, since EasyScan GO fell to 57.1% sensitivity below 200 parasites per microlitre and that band contains the patients who benefit most from early treatment. Until this exists, no field claim is defensible.',
      impact: 'high',
      effort: 'weeks',
      status: 'planned',
    },
    {
      title: 'Add a detection stage and WHO-standard slide aggregation',
      body: 'Train a detector on BBBC041 bounding boxes and MP-IDB so the pipeline consumes whole fields rather than pre-segmented crops, then aggregate detections across at least ten fields per slide with soft counting into parasites per microlitre using the WHO 8 000 white cells per microlitre convention. arXiv:2608.08566 shows the payoff directly: per-image correlation of 0.812 becomes 0.951 once aggregation is applied. This is the single change that turns a classifier into something a clinician can act on.',
      impact: 'high',
      effort: 'months',
      status: 'planned',
    },
    {
      title: 'Build the thick-film path, and report density honestly',
      body: 'Thin films give morphology and species; thick films concentrate roughly ten to twenty times more blood per field and are where low parasitaemia and density actually come from. EasyScan GO runs on thick films only and still reached quantification competence level 4, with 3-10 fold density variation, so the correct posture is to publish Bland-Altman limits of agreement alongside any density number rather than a single point estimate. Pair the two film types in one report, as miLab MAL does.',
      impact: 'high',
      effort: 'months',
      status: 'planned',
    },
    {
      title: 'Swap the ImageNet backbone for a pathology foundation encoder',
      body: 'A frozen pathology encoder with a light head generalises across stains and cameras far better than a bespoke EfficientNet fine-tuned at one site. Licence dictates the choice: UNI and Virchow2 are CC-BY-NC-ND and gated, so they are research-only, while GigaPath-Flash ships open weights under Apache-2.0 at 22M parameters for the tile encoder, which is small enough to quantise and run offline. Benchmark a linear probe on GigaPath-Flash embeddings against the current ensemble on a held-out site before committing.',
      impact: 'high',
      effort: 'weeks',
      status: 'planned',
    },
    {
      title: 'Adopt a multi-site domain-shift protocol with continual learning',
      body: 'The NIH corpus is one camera, one stain, one hospital, so the current numbers say nothing about a second clinic. Follow arXiv:2507.23648 and treat each new acquisition site as a domain-incremental task, holding a rehearsal buffer of earlier sites so adaptation does not erase prior performance, and gate every model update on a per-site regression suite. Use the existing MC-dropout uncertainty as the drift alarm: a rising share of high-sigma crops at a site is the first observable sign of shift.',
      impact: 'high',
      effort: 'months',
      status: 'planned',
    },
    {
      title: 'Add species and life-cycle-stage heads',
      body: 'MP-IDB provides all four human species crossed with ring, trophozoite, schizont and gametocyte; BBBC041 provides the same four stages plus leukocytes and a difficult flag. Species determines therapy and stage determines whether a case is progressing, so a binary head is commercially and clinically insufficient. Expect the ring class to be hardest, which the existing Grad-CAM analysis already anticipates: agreement is lowest on small ring forms where the parasite occupies a few pixels.',
      impact: 'medium',
      effort: 'weeks',
      status: 'planned',
    },
    {
      title: 'Ship the browser demo on Transformers.js',
      body: 'A live in-browser cell demo removes the server from the loop and demonstrates the offline claim rather than asserting it. onnx-community/mobilenetv4_conv_small.e2400_r224_in1k is the smallest verified option and already backs the Xenova/webgpu-mobilenet Space; Xenova/vit-base-patch16-224 mirrors the ViT-B/16 half of the ensemble; Xenova/mobilevit-small is the hybrid middle ground; and Xenova/dinov2-small runs image-feature-extraction, which supports a nearest-neighbour lookup against a labelled reference cell bank instead of a bare softmax. Load them through the pipeline API in @huggingface/transformers with the WebGPU provider and a WASM fallback.',
      impact: 'medium',
      effort: 'days',
      status: 'planned',
    },
    {
      title: 'Write the intended-use statement and a change-control plan before any pilot',
      body: 'Position the system explicitly as decision support and a second reader, never as a diagnosis, unless and until it is cleared. Draft the intended-use statement, the human-review trigger and the audit trail now, and shape the retraining process as a Predetermined Change Control Plan under the FDA final guidance of August 2025 so that later model updates are anticipated rather than re-litigated. In the EU the same software is an in vitro diagnostic under Regulation (EU) 2017/746 and, through Annex I entry 12 of the AI Act, a high-risk AI system.',
      impact: 'medium',
      effort: 'months',
      status: 'planned',
    },
  ],
  compliance: [
    {
      name: 'FDA: software as a medical device, and second-reader intended use',
      body: 'The FDA maintains a public list of AI-enabled medical devices that have met applicable premarket requirements, most recently updated on 29 June 2026 and dominated by radiology. The agency notes the list is not comprehensive and that entries were identified largely from AI-related terms in device summaries. Nothing in this project is cleared, so the only lawful positioning in the United States is decision support presented alongside, and subordinate to, a qualified microscopist. A claim that the software diagnoses malaria converts it into an uncleared diagnostic device.',
      url: 'https://www.fda.gov/medical-devices/software-medical-device-samd/artificial-intelligence-enabled-medical-devices',
    },
    {
      name: 'FDA Predetermined Change Control Plan for AI-enabled device software',
      body: 'The final guidance of August 2025 lets a manufacturer describe planned modifications, the methodology to develop, validate and implement them, and an assessment of their impact, so that the FDA reviews the plan once and the described changes do not each require a new marketing submission. For a model that must be retrained per site to survive stain and camera drift, the PCCP is the difference between a maintainable product and a frozen one, and it should be drafted before the first pilot rather than after.',
      url: 'https://www.fda.gov/regulatory-information/search-fda-guidance-documents/marketing-submission-recommendations-predetermined-change-control-plan-artificial-intelligence',
    },
    {
      name: 'EU IVDR, Regulation (EU) 2017/746',
      body: 'Software intended to detect Plasmodium in a blood sample is an in vitro diagnostic medical device in the EU and is classified under the Annex VIII rules; detection of infectious agents sits in the higher classes, and recital 56 states that for class B, class C and class D devices an appropriate level of involvement of a notified body should be compulsory. That means conformity assessment by a notified body, a performance evaluation with clinical evidence, and post-market performance follow-up, none of which a single-site retrospective cell-classification study satisfies.',
      url: 'https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32017R0746',
    },
    {
      name: 'EU AI Act, Article 6(1) and Annex I',
      body: 'An AI system is high-risk when it is a safety component of, or is itself, a product covered by the Union harmonisation legislation listed in Annex I and that product must undergo third-party conformity assessment. Annex I Section A entry 12 is Regulation (EU) 2017/746, so a notified-body-assessed malaria IVD carrying this model is high-risk by construction rather than by the Annex III use-case route. Obligations for Annex I systems apply from 2 August 2028, against 2 December 2027 for Annex III systems, which sets the realistic compliance runway.',
      url: 'https://artificialintelligenceact.eu/article/6/',
    },
    {
      name: 'WHO prequalification and malaria microscopy quality assurance',
      body: 'WHO prequalified three pf-LDH rapid diagnostic tests in April 2026 precisely because parasites that have lost the HRP2 gene are invisible to HRP2-based tests, with up to 80% of cases missed in parts of the Horn of Africa. No AI or automated microscopy device appears in that announcement. WHO separately treats light microscopy as the standard against which other methods are compared while warning that the quality of microscopy-based diagnosis is frequently inadequate, and the WHO-TDR competence levels used to grade human microscopists (level 2 for detection, level 4 for quantification in the EasyScan GO evaluation) are the scale any automated reader will be measured on.',
      url: 'https://www.who.int/news/item/24-04-2026-who-prequalifies-first-ever-malaria-treatment-for-newborns-and-infants-adds-new-diagnostic-tests',
    },
  ],
  sources: [
    {
      title: 'World malaria report 2025',
      url: 'https://www.who.int/teams/global-malaria-programme/reports/world-malaria-report-2025',
      org: 'World Health Organization',
      date: '2025-12',
    },
    {
      title: 'New tools saved a million lives from malaria last year but progress under threat as drug resistance rises',
      url: 'https://www.who.int/news/item/04-12-2025-new-tools-saved-a-million-lives-from-malaria-last-year-but-progress-under-threat-as-drug-resistance-rises',
      org: 'World Health Organization',
      date: '2025-12',
    },
    {
      title: 'WHO prequalifies first-ever malaria treatment for newborns and infants, adds new diagnostic tests',
      url: 'https://www.who.int/news/item/24-04-2026-who-prequalifies-first-ever-malaria-treatment-for-newborns-and-infants-adds-new-diagnostic-tests',
      org: 'World Health Organization',
      date: '2026-04',
    },
    {
      title: 'Statement by the Malaria Policy Advisory Group on the urgent need to address the high prevalence of pfhrp2/3 gene deletions',
      url: 'https://www.who.int/news/item/28-05-2021-statement-by-the-malaria-policy-advisory-group-on-the-urgent-need-to-address-the-high-prevalence-of-pfhrp2-3-gene-deletions-in-the-horn-of-africa-and-beyond',
      org: 'World Health Organization',
      date: '2021-05',
    },
    {
      title: 'Field evaluation of the diagnostic performance of EasyScan GO: a digital malaria microscopy device based on machine-learning',
      url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC9004086/',
      org: 'Malaria Journal',
      date: '2022-04',
    },
    {
      title: 'Diagnosis of Plasmodium infections using artificial intelligence techniques versus standard microscopy in a reference laboratory',
      url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC11784024/',
      org: 'Journal of Clinical Microbiology',
      date: '2024-12',
    },
    {
      title: 'miLab MAL: digital microscopy-based malaria diagnostic solution',
      url: 'https://noul.com/en/product-mal/',
      org: 'Noul',
      date: '2026',
    },
    {
      title: 'On-Device Multi-Species Malaria Detection with Uncertainty-Calibrated Slide-Level Aggregation',
      url: 'https://arxiv.org/abs/2608.08566',
      org: 'arXiv:2608.08566',
      date: '2026-08',
    },
    {
      title: 'Towards Field-Ready AI-based Malaria Diagnosis: A Continual Learning Approach',
      url: 'https://arxiv.org/abs/2507.23648',
      org: 'arXiv:2507.23648',
      date: '2025-07',
    },
    {
      title: 'UNI: a general-purpose self-supervised model for computational pathology',
      url: 'https://huggingface.co/MahmoodLab/UNI',
      org: 'Mahmood Lab, Harvard Medical School (Nature Medicine 2024)',
      date: '2024',
    },
    {
      title: 'Virchow2: scaling self-supervised mixed magnification models in pathology',
      url: 'https://huggingface.co/paige-ai/Virchow2',
      org: 'Paige and Microsoft Research (arXiv:2408.00738)',
      date: '2024-08',
    },
    {
      title: 'GigaPath-Flash and GigaTIME-Flash: efficient pathology foundation models',
      url: 'https://arxiv.org/abs/2607.18218',
      org: 'arXiv:2607.18218',
      date: '2026-07',
    },
    {
      title: 'onnx-community/mobilenetv4_conv_small.e2400_r224_in1k',
      url: 'https://huggingface.co/onnx-community/mobilenetv4_conv_small.e2400_r224_in1k',
      org: 'Hugging Face',
      date: '2026',
    },
    {
      title: 'Xenova/vit-base-patch16-224',
      url: 'https://huggingface.co/Xenova/vit-base-patch16-224',
      org: 'Hugging Face',
      date: '2026',
    },
    {
      title: 'Marketing Submission Recommendations for a Predetermined Change Control Plan for Artificial Intelligence-Enabled Device Software Functions',
      url: 'https://www.fda.gov/regulatory-information/search-fda-guidance-documents/marketing-submission-recommendations-predetermined-change-control-plan-artificial-intelligence',
      org: 'US Food and Drug Administration',
      date: '2025-08',
    },
  ],
}

export default frontier
