import type { Frontier } from '../frontier'

const frontier: Frontier = {
  asOf: '2026-09',
  headline:
    'The detector is a competent 2023-generation closed-set baseline; the 2026 frontier has moved to open-vocabulary hazard prompting, small-VLM rule reasoning, and NMS-free backbones that reach higher accuracy at half the CPU latency.',
  summary: [
    'Closed-set PPE detection is close to saturated for high-visibility items, and the honest way to read any headline mAP is alongside the class vocabulary and the split it was measured on. SH17, the reference benchmark for industrial PPE, publishes 8,099 images and 75,994 annotated instances across 17 classes, together with a full sweep of detectors: YOLOv8-n reaches 58.0 mAP@50 and 36.6 mAP@50-95, and the best model in the paper, YOLOv9-e, reaches 70.9 and 48.7. This project reports mAP@0.5 0.89 on eight classes on its own split, and the two figures are not comparable. A narrower vocabulary and an in-domain split make the number look stronger than an equivalent seventeen-class result would; the fair statement is that the detector is strong on the classes it was trained for, not that it beats the published state of the art.',
    'Three lines have moved since the model was trained. Backbones: Ultralytics released YOLO26 in January 2026 with native end-to-end (NMS-free) inference, DFL removed and the MuSGD optimiser; YOLO26n reaches 40.9 mAP50-95 on COCO at 38.9 ms per frame on CPU ONNX, against YOLOv8n at 37.3 mAP50-95 and 80.4 ms. The DETR line is further ahead on accuracy: D-FINE-X reaches 55.8 AP at 78 FPS on a T4 (59.3 AP with Objects365 pre-training), and DEIM, published at CVPR 2025, lifts D-FINE-L and D-FINE-X to 54.7 and 56.5 AP at the same 124 and 78 FPS while halving training time. Open-vocabulary detection is the second line: Grounding DINO 1.5 Pro reports 54.3 COCO AP and 55.7 AP zero-shot on LVIS-minival, its Edge variant 36.2 AP at 75.2 FPS with TensorRT, and YOLO-World 35.4 LVIS AP at 52.0 FPS. A hazard that has never been labelled can now be described in words and detected the same day.',
    'The third line is language. MonitorVLM fine-tunes a vision-language model against 40 written mining regulations over 9,000 vision-question-answer samples and improves precision by 22.01%, recall by 34.22% and F1 by 28.37% over an unfine-tuned 72B baseline, with a clause-filter module cutting inference latency by 13.56%. An April 2026 paper pairs a YOLOv11n detector with small VLMs and reports Gemma-3 4B lifting hazard-identification F1 from 34.5% to 50.6% and explanation quality from BERTScore 0.61 to 0.82 for 2.5 ms of overhead per image. That is the shape of the 2026 system: a fast detector for the items that carry the volume, an open-vocabulary head for the long tail, and a small language model that reads the rule and writes the citation. Against that, this project is ahead of most published research on the parts research ignores - the zone rule engine, severity grading, alert routing and the discounted cash-flow model - and behind on vocabulary, backbone and the legal handling of worker identity. Its OSHA anchors are also stale: the $15,625 and $156,259 figures in the code are a prior schedule, and the amounts in force under 29 CFR 1903.15 are $16,550 and $165,514.',
  ],
  stateOfTheArt: [
    {
      name: 'YOLO26',
      org: 'Ultralytics',
      what: 'The 2026 Ultralytics release, with optional NMS-free end-to-end inference via a one-to-one head, Distribution Focal Loss removed, the MuSGD optimiser, and Progressive Loss plus STAL training aimed at small objects. It is the drop-in replacement for the YOLOv8n backbone this project fine-tunes.',
      metric: 'YOLO26n 40.9 mAP50-95 COCO at 38.9 ms CPU ONNX, vs YOLOv8n 37.3 at 80.4 ms',
      url: 'https://docs.ultralytics.com/models/yolo26/',
      year: '2026',
    },
    {
      name: 'D-FINE',
      org: 'Peng et al., arXiv 2410.13842',
      what: 'Redefines the DETR regression task as fine-grained distribution refinement, giving a real-time detector that beats every YOLO variant on COCO accuracy at comparable GPU latency. Relevant where a site has a GPU box and wants the small, occluded classes (gloves, eye protection) detected reliably.',
      metric: 'D-FINE-L 54.0 AP at 124 FPS, D-FINE-X 55.8 AP at 78 FPS on T4; 57.1 / 59.3 AP with Objects365 pre-training',
      url: 'https://arxiv.org/abs/2410.13842',
      year: '2024',
    },
    {
      name: 'DEIM',
      org: 'CVPR 2025, arXiv 2412.04234',
      what: 'A training framework that improves DETR matching for faster convergence. It is applied on top of RT-DETR and D-FINE rather than replacing them, which makes it the cheapest accuracy gain available to a team already training a DETR-family detector.',
      metric: 'DEIM-D-FINE-L 54.7 AP at 124 FPS and DEIM-D-FINE-X 56.5 AP at 78 FPS on T4, with training time halved',
      url: 'https://arxiv.org/abs/2412.04234',
      year: '2024',
    },
    {
      name: 'Grounding DINO 1.5',
      org: 'IDEA Research',
      what: 'Open-set detection at production quality, trained on over 20 million grounded images, with a Pro model for accuracy and an Edge model for on-site hardware. This is the mechanism that turns a new hazard from a labelling project into a text prompt.',
      metric: 'Pro: 54.3 COCO AP, 55.7 AP zero-shot on LVIS-minival. Edge: 36.2 AP on LVIS-minival at 75.2 FPS with TensorRT',
      url: 'https://arxiv.org/abs/2405.10300',
      year: '2024',
    },
    {
      name: 'YOLO-World',
      org: 'AILab-CVC',
      what: 'Real-time open-vocabulary detection built on a re-parameterisable vision-language path aggregation network, so the text encoder can be folded away at deployment. The practical option when open-vocabulary detection has to run at frame rate rather than on demand.',
      metric: '35.4 AP on LVIS at 52.0 FPS on V100',
      url: 'https://arxiv.org/abs/2401.17270',
      year: '2024',
    },
    {
      name: 'SH17 dataset',
      org: 'Mughees et al., arXiv 2407.04590',
      what: 'The reference open PPE benchmark for industrial settings: person, head, face, glasses, medical face mask, face guard, ear, earmuffs, hands, gloves, foot, shoes, safety vest, tools, helmet, medical suit and safety suit. Its published sweep is the only fair yardstick for a PPE detector, because it fixes both the vocabulary and the split.',
      metric: '8,099 images, 75,994 instances, 17 classes; YOLOv9-e 70.9 mAP@50 / 48.7 mAP@50-95; YOLOv8-n 58.0 / 36.6',
      url: 'https://arxiv.org/abs/2407.04590',
      year: '2024',
    },
    {
      name: 'MonitorVLM',
      org: 'arXiv 2510.03666',
      what: 'A vision-language framework for safety-violation detection in mining, fine-tuned against 40 high-frequency written regulations over 9,000 vision-question-answer samples. It demonstrates the pattern this project needs: the rule text itself is an input to the model, not a hard-coded table.',
      metric: 'Precision +22.01%, recall +34.22%, F1 +28.37% over an unfine-tuned 72B baseline; clause filter cuts inference latency 13.56%',
      url: 'https://arxiv.org/abs/2510.03666',
      year: '2025',
    },
    {
      name: 'Detector plus small-VLM hazard reasoning',
      org: 'Adil et al., arXiv 2604.05210',
      what: 'A April 2026 study pairing a YOLOv11n detector with small vision-language models (Gemma-3 4B, Qwen-3-VL 2B/4B, InternVL-3 1B/2B, SmolVLM-2B) so the detector supplies grounded objects and the VLM supplies the reasoning and the written rationale. The overhead is small enough to sit inside a per-frame budget.',
      metric: 'Gemma-3 4B: hazard-identification F1 50.6% vs 34.5% baseline; explanation BERTScore F1 0.61 to 0.82; 2.5 ms per image overhead',
      url: 'https://arxiv.org/abs/2604.05210',
      year: '2026',
    },
    {
      name: 'Browser-runnable ONNX detectors (Transformers.js)',
      org: 'Hugging Face',
      what: 'Four verified repositories make a live in-browser demo possible with no server: onnx-community/yolov10n and Xenova/yolos-tiny for closed-set object detection, and Xenova/owlvit-base-patch32 plus onnx-community/owlv2-base-patch16-ensemble-ONNX for zero-shot detection from text prompts. The OWL-ViT model card ships a candidate-label example that already includes "helmet", which is the demo this product needs: type a PPE item, get boxes, with no model training in between.',
      metric: 'pipeline("zero-shot-object-detection", "Xenova/owlvit-base-patch32") runs client-side; no hard-hat-specific ONNX repository exists on the Hub',
      url: 'https://huggingface.co/Xenova/owlvit-base-patch32',
      year: '2026',
    },
  ],
  benchmarks: [
    {
      name: 'Backbone accuracy, COCO mAP50-95',
      sota: '59.3 AP (D-FINE-X with Objects365 pre-training); 57.5 AP (YOLO26x)',
      sotaBy: 'D-FINE, arXiv 2410.13842',
      project: '37.3 AP - the published COCO figure for the YOLOv8n backbone this project fine-tunes',
      sotaValue: 59.3,
      projectValue: 37.3,
      unit: 'AP',
      higherIsBetter: true,
    },
    {
      name: 'CPU latency, ONNX, per 640 px frame',
      sota: '38.9 ms (YOLO26n, CPU ONNX)',
      sotaBy: 'Ultralytics YOLO26',
      project: 'under 60 ms (YOLOv8n exported to ONNX, project claim); the YOLOv8n reference figure in the Ultralytics table is 80.4 ms',
      sotaValue: 38.9,
      projectValue: 60,
      unit: 'ms',
      higherIsBetter: false,
    },
    {
      name: 'PPE detection, SH17 mAP@0.5',
      sota: '70.9 mAP@50 on 17 classes (YOLOv9-e); YOLOv8-n scores 58.0 on the same benchmark',
      sotaBy: 'SH17, arXiv 2407.04590',
      project: '89.0 on 8 classes on an in-house split - a different vocabulary and a different split, so the gap is not a like-for-like win',
      sotaValue: 70.9,
      projectValue: 89.0,
      unit: 'mAP@0.5 %',
      higherIsBetter: true,
    },
    {
      name: 'Open-vocabulary detection, zero-shot LVIS-minival AP',
      sota: '55.7 AP (Grounding DINO 1.5 Pro); 36.2 AP on the Edge variant at 75.2 FPS',
      sotaBy: 'IDEA Research',
      project: 'not supported - the model has a fixed 8-class vocabulary, so an unlabelled hazard cannot be detected at any accuracy',
      sotaValue: 55.7,
      projectValue: 0,
      unit: 'AP',
      higherIsBetter: true,
    },
    {
      name: 'Annotated PPE class vocabulary',
      sota: '17 classes covering head, face, ear, hand, foot, torso and tools',
      sotaBy: 'SH17',
      project: '8 classes (5 PPE items plus person and absent-PPE negatives)',
      sotaValue: 17,
      projectValue: 8,
      unit: 'classes',
      higherIsBetter: true,
    },
    {
      name: 'Training set scale',
      sota: '8,099 images and 75,994 annotated instances, 9.38 instances per image',
      sotaBy: 'SH17',
      project: '4,000 real construction images from the Roboflow Construction Site Safety export, supplemented by the 7,041-image Kaggle Hard Hat Detection set',
      sotaValue: 8099,
      projectValue: 4000,
      unit: 'images',
      higherIsBetter: true,
    },
  ],
  upgrades: [
    {
      title: 'Correct the OSHA penalty anchors to the schedule in force',
      body: 'The rule table and the ROI model use $15,625 per serious violation and $156,259 for willful or repeated. The amounts in force under 29 CFR 1903.15 are $16,550 for serious and other-than-serious, $165,514 for willful or repeated, $16,550 per day for failure to correct, and a $11,823 minimum for a willful violation. Every penalty-exposure figure the dashboard shows is understated by roughly 6% until these are updated, and a stale statutory number is the fastest way to lose a safety director in a demo.',
      impact: 'high',
      effort: 'days',
    },
    {
      title: 'Retrain the backbone on YOLO26n',
      body: 'YOLO26n reaches 40.9 mAP50-95 on COCO at 38.9 ms per frame on CPU ONNX against YOLOv8n at 37.3 and 80.4 ms, so the same fine-tuning recipe should yield a more accurate detector at less than half the CPU cost per camera. The NMS-free one-to-one head also removes a post-processing step from the ONNX graph, which simplifies the edge deployment. This is a re-run of an existing training pipeline, not new engineering.',
      impact: 'high',
      effort: 'days',
    },
    {
      title: 'Merge SH17 into the training corpus and adopt its evaluation protocol',
      body: 'SH17 adds 8,099 images and 75,994 instances across 17 classes, including the ear, earmuff, face-guard, medical-suit and safety-suit categories this model cannot see. Training on the union and reporting on the published SH17 split makes the results comparable with the literature for the first time, and gives an honest answer to the question a technical buyer will ask: how does 0.89 compare with YOLOv9-e at 70.9. Expect the headline number to fall as the vocabulary widens, which is the correct outcome.',
      impact: 'high',
      effort: 'weeks',
    },
    {
      title: 'Add an open-vocabulary second stage for unlabelled hazards',
      body: 'Run OWLv2 or Grounding DINO 1.5 Edge behind the closed-set detector so a safety lead can express a hazard as text - "worker without a harness within two metres of an unguarded edge" - and get candidate detections without a labelling round. Grounding DINO 1.5 Pro reports 55.7 AP zero-shot on LVIS-minival and the Edge model 36.2 AP at 75.2 FPS with TensorRT, which is accurate enough for review-queue triage even where it is not accurate enough to alert on directly.',
      impact: 'high',
      effort: 'weeks',
    },
    {
      title: 'Close the prompt-to-class promotion loop',
      body: 'Detections confirmed by a supervisor in the open-vocabulary review queue become labelled instances. Once a prompt accumulates enough confirmations it is promoted into the fast closed-set head by fine-tuning YOLO26n, and the prompt drops back to a fallback. This converts the open-vocabulary stage from a demo into a data engine, and gives the product a defensible reason for every additional camera to make the model better.',
      impact: 'high',
      effort: 'weeks',
    },
    {
      title: 'Ship a live in-browser demo on verified ONNX repositories',
      body: 'onnx-community/yolov10n and Xenova/yolos-tiny cover closed-set detection through the Transformers.js object-detection pipeline; Xenova/owlvit-base-patch32 and onnx-community/owlv2-base-patch16-ensemble-ONNX cover zero-shot detection from typed candidate labels. No hard-hat-specific ONNX repository exists on the Hub, so the honest demo is the open-vocabulary one: the visitor types "hard hat, safety vest, gloves" and watches boxes appear, which demonstrates the wedge rather than the fine-tune.',
      impact: 'medium',
      effort: 'days',
    },
    {
      title: 'Replace the hard-coded severity table with a small-VLM rule reader',
      body: 'MonitorVLM shows that fine-tuning a vision-language model against the written regulations themselves beats a large unfine-tuned baseline by 22.01% precision and 34.22% recall, and that filtering to the relevant clauses cuts latency by 13.56%. The April 2026 detector-plus-small-VLM study shows a 4B model raising hazard F1 from 34.5% to 50.6% for 2.5 ms of overhead. Feeding the site safety plan and the applicable CFR sections to a small VLM lets each customer state its own rules in prose instead of waiting for a code change.',
      impact: 'high',
      effort: 'months',
    },
    {
      title: 'Re-found repeat-offender tracking on a lawful identity model',
      body: 'A badge-linked ledger that scores individual workers is an AI system for monitoring and evaluating the behaviour of persons in work-related contractual relationships, which places it in Annex III of the EU AI Act. Where identity is derived from face or gait rather than a badge scan it also engages US state biometric statutes. The defensible design is pseudonymous crew-level aggregation by default, per-worker attribution only where there is a documented lawful basis and, in the EU, a works-council agreement, with a published retention schedule and an escalation path a human signs.',
      impact: 'high',
      effort: 'weeks',
    },
  ],
  compliance: [
    {
      name: 'OSHA civil penalties (29 CFR 1903.15)',
      body: 'The amounts in force are $16,550 for a serious or other-than-serious violation, $165,514 for a willful or repeated violation, $16,550 per day for failure to correct, and a minimum of $11,823 for a willful violation, effective for penalties proposed after 15 January 2025. The $15,625 and $156,259 figures used in the current rule table and ROI model belong to an earlier schedule and understate exposure. Penalties are indexed for inflation, so the figures must be read from the regulation each January rather than hard-coded.',
      url: 'https://www.law.cornell.edu/cfr/text/29/1903.15',
    },
    {
      name: 'OSHA recordkeeping (29 CFR 1904.4)',
      body: 'Employers covered by Part 1904 must record each fatality, injury and illness that is work-related, is a new case, and meets one or more of the general recording criteria. A detection is not a recordable case, and the product must not blur the two: automated observations are leading indicators that feed the safety programme, while the 300, 300A and 301 file is a legal record whose entries are made by a person. The shift report should be an input to that determination, clearly labelled as such.',
      url: 'https://www.law.cornell.edu/cfr/text/29/1904.4',
    },
    {
      name: 'EU AI Act Annex III, point 4(b) - worker monitoring is high-risk',
      body: 'Annex III classifies as high-risk any AI system "intended to be used to make decisions affecting terms of work-related relationships, the promotion or termination of work-related contractual relationships, to allocate tasks based on individual behaviour or personal traits or characteristics or to monitor and evaluate the performance and behaviour of persons in such relationships". A repeat-offender ledger that drives OSHA progressive discipline falls squarely inside this. Deployment in the EU therefore requires a risk-management system, data governance, logging, human oversight and technical documentation, not simply a better detector.',
      url: 'https://artificialintelligenceact.eu/annex/3/',
    },
    {
      name: 'EU AI Act Article 5 - the boundary the product must not cross',
      body: 'Article 5(1)(f) prohibits the use of AI systems "to infer emotions of a natural person in the areas of workplace and education institutions, except where the use of the AI system is intended to be put in place or into the market for medical or safety reasons", and Article 5(1)(g) prohibits biometric categorisation that deduces race, political opinions, trade union membership, religious or philosophical beliefs, sex life or sexual orientation. These prohibitions have applied since 2 February 2025. Fatigue and distraction analytics are a tempting adjacency for a safety product and sit close to the emotion-inference line; the safety exception is narrow and should not be assumed to cover behavioural scoring dressed as wellbeing.',
      url: 'https://artificialintelligenceact.eu/article/5/',
    },
    {
      name: 'Worker data: GDPR Article 88 and US biometric statutes',
      body: 'Article 88 lets Member States set more specific rules for employee data, including through collective agreements, and requires suitable and specific measures safeguarding human dignity, legitimate interests and fundamental rights, with particular regard to transparency. In practice a German or Dutch deployment needs a works-council agreement before a camera scores individual workers. In the United States the sharper constraint is the Illinois Biometric Information Privacy Act, which requires consent, timely destruction and secure storage of biometric identifiers and grants a private right of action with $1,000 per violation, or $5,000 where the violation is intentional or reckless. Identifying a worker from a badge scan is HR data; identifying the same worker from their face or gait converts the repeat-offender ledger into a biometric-law question with per-violation exposure.',
      url: 'https://gdpr-info.eu/art-88-gdpr/',
    },
  ],
  sources: [
    { title: 'SH17: A Dataset for Human Safety and Personal Protective Equipment Detection in Manufacturing Industry', url: 'https://arxiv.org/abs/2407.04590', org: 'arXiv', date: '2024-07' },
    { title: 'SH17dataset - class list and full detector benchmark table', url: 'https://github.com/ahmadmughees/SH17dataset/blob/master/README.md', org: 'GitHub', date: '2026-09' },
    { title: 'YOLO26 model documentation - COCO mAP and CPU ONNX latency table', url: 'https://docs.ultralytics.com/models/yolo26/', org: 'Ultralytics', date: '2026-01' },
    { title: 'YOLOv8 model documentation - COCO mAP, CPU ONNX latency, parameters', url: 'https://docs.ultralytics.com/models/yolov8/', org: 'Ultralytics', date: '2023-01' },
    { title: 'D-FINE: Redefine Regression Task in DETRs as Fine-grained Distribution Refinement', url: 'https://arxiv.org/abs/2410.13842', org: 'arXiv', date: '2024-10' },
    { title: 'DEIM: DETR with Improved Matching for Fast Convergence', url: 'https://arxiv.org/abs/2412.04234', org: 'arXiv / CVPR 2025', date: '2024-12' },
    { title: 'Grounding DINO 1.5: Advance the "Edge" of Open-Set Object Detection', url: 'https://arxiv.org/abs/2405.10300', org: 'IDEA Research', date: '2024-05' },
    { title: 'YOLO-World: Real-Time Open-Vocabulary Object Detection', url: 'https://arxiv.org/abs/2401.17270', org: 'arXiv', date: '2024-01' },
    { title: 'Using Vision Language Models for Safety Hazard Identification in Construction', url: 'https://arxiv.org/abs/2504.09083', org: 'arXiv', date: '2025-04' },
    { title: 'MonitorVLM: A Vision-Language Framework for Safety Violation Detection in Mining Operations', url: 'https://arxiv.org/abs/2510.03666', org: 'arXiv', date: '2025-10' },
    { title: 'Integration of Object Detection and Small VLMs for Construction Safety Hazard Identification', url: 'https://arxiv.org/abs/2604.05210', org: 'arXiv', date: '2026-04' },
    { title: 'onnx-community/yolov10n - ONNX weights for Transformers.js object detection', url: 'https://huggingface.co/onnx-community/yolov10n', org: 'Hugging Face', date: '2026-09' },
    { title: 'Xenova/owlvit-base-patch32 - in-browser zero-shot object detection', url: 'https://huggingface.co/Xenova/owlvit-base-patch32', org: 'Hugging Face', date: '2026-09' },
    { title: 'onnx-community/owlv2-base-patch16-ensemble-ONNX - OWLv2 for Transformers.js', url: 'https://huggingface.co/onnx-community/owlv2-base-patch16-ensemble-ONNX', org: 'Hugging Face', date: '2025-07' },
    { title: '29 CFR 1903.15 - adjusted OSHA civil monetary penalties', url: 'https://www.law.cornell.edu/cfr/text/29/1903.15', org: 'Cornell Legal Information Institute', date: '2025-01' },
  ],
}

export default frontier
