import type { Frontier } from '../frontier'

/**
 * Where LLM review categorisation stands in September 2026.
 * Every claim is backed by a source in `sources`; nothing here is estimated.
 */
const frontier: Frontier = {
  asOf: '2026-09',
  headline:
    'The classification quality is competitive and the cost per review is close to the vendor floor, but the architecture still pays a frontier model to do work a distilled encoder and a reranker would do more accurately and for a tenth of the price.',
  summary: [
    'Through 2024 the field assumed a large model prompted with a taxonomy was the best available text classifier. The 2024–2026 literature says otherwise. Bucher and Martini fine-tuned small encoders on 200 labelled examples and beat zero-shot GPT-4 and Claude Opus on every one of four case studies — F1 0.94 versus 0.51 on stance detection, 0.85 versus 0.18 on emotion — with the gap widening as the taxonomy becomes more specialised and more multi-class. The BTZSC benchmark published in March 2026 extends the finding to 22 datasets and 77-label cardinality: cross-encoder rerankers lead at macro-F1 0.72, a 0.6B reranker beats every NLI cross-encoder tested, and large instruction-tuned LLMs sit outside the accuracy-per-latency Pareto frontier entirely.',
    'What the frontier models are uniquely good at is the part that has no labels: proposing the taxonomy, naming the topics and explaining an unfamiliar cluster. TopicGPT reaches harmonic-mean purity 0.74 against human-annotated topics where the strongest classical baseline reaches 0.64, and BERTopic\'s LLM representation modules apply the same idea economically by calling the model once per topic rather than once per document. The 2026 production pattern is therefore two-stage: an LLM discovers and maintains the label set, a small distilled model applies it to every record.',
    'The cost side has moved just as fast. Cache reads settled at 0.1× base input across Anthropic, OpenAI and Google, batch submission takes a further uniform 50%, and the two discounts stack — Anthropic states a 5-minute cache pays for itself after a single read. DeepSeek prices a cache hit at roughly 3.2% of a cache miss and halves it again off-peak. This project already exploits caching (87% hit rate, $0.003 per review) but classifies interactively rather than in batch, and runs a general-purpose model on the hot path where a distilled encoder would be both cheaper and, on its own eight-category taxonomy, more accurate. Retrieval is a bi-encoder with no reranking stage, which is the single largest quality gap against the current retrieval state of the art.',
  ],
  stateOfTheArt: [
    {
      name: 'Fine-tuned small encoders vs. zero-shot frontier models',
      org: 'Bucher & Martini (arXiv 2406.08660)',
      what: 'Four case studies fine-tuning RoBERTa/DeBERTa/XLNet on only 200 labelled examples each, benchmarked against zero-shot GPT-4 and Claude Opus. The small supervised models win everywhere, and the margin grows with taxonomy specificity.',
      metric: 'DeBERTa V3 F1 0.94 vs GPT-4 0.51 (stance); XLNet 0.85 vs GPT-4 0.18 (emotion)',
      url: 'https://arxiv.org/html/2406.08660v1',
      year: '2024',
    },
    {
      name: 'BTZSC zero-shot text-classification benchmark',
      org: 'arXiv 2603.11991',
      what: 'Twenty-two English datasets across sentiment, topic, intent and emotion, with class cardinality from binary to 77 labels, comparing rerankers, instruction-tuned LLMs, embedding models and NLI cross-encoders on the same footing.',
      metric: 'Qwen3-Reranker-8B macro-F1 0.72; Qwen3-Reranker-0.6B 0.61 beats every NLI cross-encoder',
      url: 'https://arxiv.org/html/2603.11991',
      year: '2026',
    },
    {
      name: 'TopicGPT',
      org: 'Pham et al., NAACL 2024',
      what: 'Prompt-based topic modelling that generates interpretable, natural-language topic labels instead of bags of words, and assigns documents to them. The reference design for letting a model author the taxonomy rather than apply a fixed one.',
      metric: 'Harmonic mean purity 0.74 vs 0.64 for the strongest baseline',
      url: 'https://arxiv.org/abs/2311.01449',
      year: '2024',
    },
    {
      name: 'BERTopic LLM representation models',
      org: 'Maarten Grootendorst',
      what: 'Cluster first with embeddings, then call an LLM once per topic with the top keywords and the four most representative documents to produce a label. Supports OpenAI, Cohere, LlamaCPP, Ollama, Hugging Face and LiteLLM, with `doc_length` and tokenizer controls to bound spend.',
      metric: 'One model call per topic, not per document',
      url: 'https://maartengr.github.io/BERTopic/getting_started/representation/llm.html',
      year: '2026',
    },
    {
      name: 'Constrained decoding for guaranteed JSON',
      org: 'Anthropic structured outputs · XGrammar',
      what: 'Schema compliance is now enforced by the decoder rather than repaired afterwards. Anthropic compiles a grammar from the JSON Schema, caches it for 24 hours and constrains sampling; XGrammar shows the same technique is fast enough to be free at inference time.',
      metric: 'XGrammar: 3.5× faster than prior JSON-schema maskers, up to 14× end-to-end',
      url: 'https://platform.claude.com/docs/en/build-with-claude/structured-outputs',
      year: '2026',
    },
    {
      name: 'Prompt caching and batch economics',
      org: 'Anthropic · OpenAI · Google · DeepSeek',
      what: 'Cache reads converged on 0.1× base input at all three US frontier vendors; batch submission is a uniform further 50%; the two stack. DeepSeek prices a cache hit at $0.014/MTok against a $0.44 miss, halved again off-peak.',
      metric: 'Sonnet 4.6 cache read $0.30/MTok vs $3.00 input; Haiku 4.5 $0.10 vs $1.00',
      url: 'https://platform.claude.com/docs/en/about-claude/pricing',
      year: '2026',
    },
    {
      name: 'Cross-encoder reranking',
      org: 'Jina AI · BAAI',
      what: 'A second-stage cross-encoder over bi-encoder candidates is the standard way to lift retrieval precision. jina-reranker-v2-base-multilingual reaches parity with a model twice its size, at 278M parameters and a 1,024-token window — but ships under CC-BY-NC-4.0, which rules it out of a commercial product without a licence.',
      metric: 'BEIR nDCG@10 53.17 (jina v2, 278M) vs 53.65 (bge-reranker-v2-m3, 568M)',
      url: 'https://huggingface.co/jinaai/jina-reranker-v2-base-multilingual',
      year: '2026',
    },
    {
      name: 'Browser-side inference with Transformers.js',
      org: 'Hugging Face',
      what: 'ONNX Runtime in the browser with WASM by default and WebGPU on opt-in, `dtype` quantisation down to q4, and 40-plus supported tasks. Classification and embedding of a review can now happen on the reviewer\'s own machine at zero marginal cost and with no data leaving the page.',
      metric: 'Xenova/all-MiniLM-L6-v2 at 2.7M downloads/month; 384-dim embeddings in-browser',
      url: 'https://huggingface.co/docs/transformers.js',
      year: '2026',
    },
  ],
  benchmarks: [
    {
      name: 'In-domain taxonomy classification (F1 / accuracy)',
      sota: '0.94 F1 — DeBERTa V3 fine-tuned on 200 labelled examples',
      sotaBy: 'Bucher & Martini 2024 (stance, 2-class)',
      project: '0.942 accuracy — Claude Sonnet 4.6, few-shot, 8-class taxonomy',
      sotaValue: 0.94,
      projectValue: 0.942,
      unit: 'F1 / accuracy',
      higherIsBetter: true,
    },
    {
      name: 'Zero-shot onto an unseen taxonomy (macro-F1)',
      sota: '0.72 macro-F1 across 22 datasets',
      sotaBy: 'Qwen3-Reranker-8B, BTZSC 2026',
      project: 'Not evaluated — the taxonomy is fixed at eight categories and supplied in the prompt',
      sotaValue: 0.72,
      unit: 'macro-F1',
      higherIsBetter: true,
    },
    {
      name: 'Cost per classified review (USD)',
      sota: '$0.0019 — Haiku 4.5 at Anthropic\'s own worked rate for a 3,700-token record ($0.0037), halved by the Batch API',
      sotaBy: 'Anthropic pricing, September 2026',
      project: '$0.003 — Sonnet 4.6 with an 87% prompt-cache hit rate, interactive',
      sotaValue: 0.0019,
      projectValue: 0.003,
      unit: 'USD / review',
      higherIsBetter: false,
    },
    {
      name: 'Cached read as a share of uncached input price',
      sota: '3.2% — DeepSeek v4-flash, $0.014 hit vs $0.44 miss',
      sotaBy: 'DeepSeek API pricing',
      project: '10% — Sonnet 4.6, $0.30 read vs $3.00 input',
      sotaValue: 3.2,
      projectValue: 10,
      unit: '% of input price',
      higherIsBetter: false,
    },
    {
      name: 'Retrieval quality (BEIR nDCG@10)',
      sota: '53.65 — bge-reranker-v2-m3 cross-encoder',
      sotaBy: 'Jina AI comparison table, 2026',
      project: 'No reranking stage — bi-encoder only (all-MiniLM-L6-v2, Precision@5 0.891 on similar-review lookup)',
      sotaValue: 53.65,
      unit: 'nDCG@10',
      higherIsBetter: true,
    },
  ],
  upgrades: [
    {
      title: 'Move bulk classification onto the Batch API with a 1-hour cache TTL',
      body: 'Reviews arrive continuously but almost nothing about them is latency-sensitive; only the live triage path needs a synchronous answer. Submitting the backlog through the Batch API takes a flat 50% off input and output, and Anthropic confirms the discount stacks with prompt caching. Switching the 6,000-token taxonomy prefix from the 5-minute to the 1-hour TTL costs 2× on write and pays back after two reads, which a batch of any size clears immediately. Nothing about the prompt or the schema changes.',
      impact: 'high',
      effort: 'days',
      status: 'planned',
    },
    {
      title: 'Replace JSON repair with constrained decoding',
      body: 'The pipeline currently validates the eight-field payload and falls back to a rule-based classifier when the JSON is malformed, which silently degrades a fraction of records. Anthropic\'s `output_config.format` with a JSON Schema compiles a grammar and constrains sampling, so schema violations become impossible rather than caught; the compiled grammar is cached for 24 hours, so only the first call of the day pays compilation latency. The rule-based path stays, but for provider outages rather than parse failures.',
      impact: 'medium',
      effort: 'days',
      status: 'planned',
    },
    {
      title: 'Distil the LLM labels into a fine-tuned encoder for the hot path',
      body: 'The 500k corpus already carries gold issue labels and the LLM has produced a large agreeing set on top of them. Bucher and Martini show 200 labelled examples are enough for DeBERTa V3 to beat zero-shot frontier prompting on a bespoke taxonomy, and BTZSC shows a 0.6B reranker outperforming every NLI cross-encoder tested. Fine-tuning a DeBERTa-v3 or Qwen3-Reranker-0.6B head on the accumulated labels moves per-record cost to effectively zero, removes the provider from the critical path, and — on this specific eight-class taxonomy — should raise accuracy rather than trade it away. The frontier model stays for the residual it is uncertain about.',
      impact: 'high',
      effort: 'weeks',
      status: 'planned',
    },
    {
      title: 'Add a cross-encoder reranking stage to RAG retrieval',
      body: 'Retrieval is a single bi-encoder pass over 384-dimensional MiniLM vectors; Precision@5 of 0.891 is respectable but there is no second opinion on ordering. Retrieving 50 candidates and reranking to five with bge-reranker-v2-m3 is the standard fix and the published BEIR gap between bi-encoder and cross-encoder retrieval is large. Note the licence constraint: jina-reranker-v2 is CC-BY-NC-4.0 and cannot be shipped commercially without a separate agreement, so bge-reranker-v2-m3 or a Qwen3 reranker is the productisable choice.',
      impact: 'high',
      effort: 'weeks',
      status: 'planned',
    },
    {
      title: 'Let the model author the taxonomy, then version it',
      body: 'The eight issue categories are hand-written, so the classifier can only ever find what the taxonomy already names — the exact failure the BERTopic radar exists to compensate for. TopicGPT\'s pattern (generate natural-language topic labels, then assign) reaches purity 0.74 against human-annotated topics versus 0.64 for the best classical baseline, and BERTopic\'s LLM representation modules make it cheap by calling the model once per topic instead of once per document. The product move is a proposed-taxonomy diff that a category manager approves, with every historical record re-labelled under a versioned taxonomy id so trend lines survive the change.',
      impact: 'high',
      effort: 'weeks',
      status: 'planned',
    },
    {
      title: 'Stand up an LLM-as-judge evaluation loop with a frozen gold set',
      body: 'A single 94.2% accuracy figure against a human gold standard is a point-in-time measurement; provider model updates, prompt edits and taxonomy changes all move it, and nothing currently notices. A frozen stratified gold set scored nightly, plus a judge model that rates the free-text `summary` and `key_issues` fields for faithfulness against the source review, converts silent drift into an alert. This is also the artefact an auditor asks for under the EU AI Act.',
      impact: 'medium',
      effort: 'weeks',
      status: 'planned',
    },
    {
      title: 'Push first-pass triage into the browser',
      body: 'Transformers.js runs ONNX Runtime with WASM by default and WebGPU on opt-in, with q4 quantisation. Xenova/distilbert-base-uncased-finetuned-sst-2-english gives polarity, Xenova/nli-deberta-v3-xsmall gives zero-shot routing against an arbitrary label set, and Xenova/all-MiniLM-L6-v2 gives the same 384-dimensional embedding the server index uses. Running these client-side makes the demo, the pre-filter and any privacy-sensitive first pass cost nothing per record and keeps the text on the reviewer\'s machine.',
      impact: 'medium',
      effort: 'weeks',
      status: 'planned',
    },
    {
      title: 'Take the taxonomy multilingual',
      body: 'The corpus and the prompt are English-only, which is the binding constraint on selling into European and APAC catalogues. onnx-community/embeddinggemma-300m-ONNX covers 100-plus languages at 768 dimensions with Matryoshka truncation to 512/256/128, and Xenova/multilingual-e5-small is the smaller browser-side option; both run under Transformers.js. The taxonomy stays language-independent, the embeddings and the few-shot examples become per-locale.',
      impact: 'medium',
      effort: 'months',
      status: 'planned',
    },
  ],
  compliance: [
    {
      name: 'EU AI Act Article 50 — transparency, from 2 August 2026',
      body: 'Article 50 applies from 2 August 2026. Text generated by the system — the one-sentence summaries, the RAG answers, the executive report — must be marked in a machine-readable format and detectable as artificially generated, and the marking must be "effective, interoperable, robust and reliable as far as this is technically feasible". Paragraph 3 obliges deployers of emotion-recognition systems to inform the people exposed to them, which is a live question for sentiment scoring applied to identifiable customers rather than to aggregate volumes.',
      url: 'https://artificialintelligenceact.eu/article/50/',
    },
    {
      name: 'FTC 16 CFR Part 465 — consumer reviews and testimonials',
      body: 'The FTC\'s Rule on the Use of Consumer Reviews and Testimonials was announced on 14 August 2024 and took effect on 21 October 2024. It bans creating, buying or selling reviews that misrepresent their author — explicitly including AI-generated fake reviews — bans compensation conditioned on expressing a particular sentiment, and bans suppressing negative reviews by threat or intimidation. Courts may impose civil penalties for knowing violations. Any system that drafts review responses, or that surfaces a "suppress" action, has to be designed so it cannot be used to do either of those things.',
      url: 'https://www.ftc.gov/business-guidance/resources/consumer-reviews-testimonials-rule-questions-answers',
    },
    {
      name: 'GDPR Article 22 — solely automated decisions',
      body: 'Where a classification drives a decision producing legal or similarly significant effects on an individual — a seller suspension, a warranty refusal, a refund denial — Article 22 gives the data subject the right not to be subject to it on a solely automated basis, and requires human intervention, the right to express a point of view and the right to contest. In practice the priority and action_required fields must route to a person before they reach an outcome of that kind.',
      url: 'https://gdpr-info.eu/art-22-gdpr/',
    },
    {
      name: 'Review-platform terms bar building a corpus by crawling',
      body: 'Trustpilot\'s consumer terms (version 7.0, February 2025) prohibit accessing, searching or collecting content by any automated means except as provided on the platform, and prohibit text mining, data mining or web scraping "for any purpose" without express permission — a ban that names the training and development of artificial intelligence systems or models explicitly. A review-analytics product has to be built on the customer\'s own first-party feedback or on licensed feeds, never on a crawl.',
      url: 'https://corporate.trustpilot.com/legal/for-reviewers/terms-of-use-for-consumers',
    },
  ],
  sources: [
    { title: 'Fine-Tuned "Small" LLMs (Still) Significantly Outperform Zero-Shot Generative AI', url: 'https://arxiv.org/html/2406.08660v1', org: 'Bucher & Martini', date: '2024-06' },
    { title: 'BTZSC: A Benchmark for Zero-Shot Text Classification', url: 'https://arxiv.org/html/2603.11991', org: 'arXiv', date: '2026-03' },
    { title: 'TopicGPT: A Prompt-based Topic Modeling Framework', url: 'https://arxiv.org/abs/2311.01449', org: 'Pham et al., NAACL', date: '2024-04' },
    { title: 'BERTopic — LLM & Generative AI representation models', url: 'https://maartengr.github.io/BERTopic/getting_started/representation/llm.html', org: 'Maarten Grootendorst', date: '2026-09' },
    { title: 'Prompt caching', url: 'https://platform.claude.com/docs/en/build-with-claude/prompt-caching', org: 'Anthropic', date: '2026-09' },
    { title: 'Claude API pricing', url: 'https://platform.claude.com/docs/en/about-claude/pricing', org: 'Anthropic', date: '2026-09' },
    { title: 'Structured outputs', url: 'https://platform.claude.com/docs/en/build-with-claude/structured-outputs', org: 'Anthropic', date: '2026-09' },
    { title: 'Prompt caching guide', url: 'https://developers.openai.com/api/docs/guides/prompt-caching', org: 'OpenAI', date: '2026-09' },
    { title: 'API pricing', url: 'https://developers.openai.com/api/docs/pricing', org: 'OpenAI', date: '2026-09' },
    { title: 'Context caching', url: 'https://ai.google.dev/gemini-api/docs/caching', org: 'Google', date: '2026-09' },
    { title: 'DeepSeek API pricing', url: 'https://api-docs.deepseek.com/quick_start/pricing/', org: 'DeepSeek', date: '2026-09' },
    { title: 'Achieving efficient, flexible, portable structured generation with XGrammar', url: 'https://blog.mlc.ai/2024/11/22/achieving-efficient-flexible-portable-structured-generation-with-xgrammar', org: 'MLC / CMU', date: '2024-11' },
    { title: 'jina-reranker-v2-base-multilingual', url: 'https://huggingface.co/jinaai/jina-reranker-v2-base-multilingual', org: 'Jina AI', date: '2026-09' },
    { title: 'Transformers.js documentation', url: 'https://huggingface.co/docs/transformers.js', org: 'Hugging Face', date: '2026-09' },
    { title: 'onnx-community/embeddinggemma-300m-ONNX', url: 'https://huggingface.co/onnx-community/embeddinggemma-300m-ONNX', org: 'Google / ONNX Community', date: '2026-09' },
    { title: 'EU AI Act Article 50 — Transparency obligations', url: 'https://artificialintelligenceact.eu/article/50/', org: 'EU AI Act', date: '2026-09' },
    { title: 'Consumer Reviews and Testimonials Rule: Questions and Answers', url: 'https://www.ftc.gov/business-guidance/resources/consumer-reviews-testimonials-rule-questions-answers', org: 'FTC', date: '2024-10' },
    { title: 'Terms of Use for Consumers, version 7.0', url: 'https://corporate.trustpilot.com/legal/for-reviewers/terms-of-use-for-consumers', org: 'Trustpilot', date: '2025-02' },
  ],
}

export default frontier
